// UI strings: key -> [español, English, tier]. A string turns English once she has learned TIER[tier] lessons (see i18n.jsx).
// tier 1 = single everyday words … tier 6 = long explanations. Values may be functions of the variables.
const plural = (n, one, many) => (n === 1 ? one : many)

export const STR = {
  // ---------- common ----------
  'common.continue': ['Continuar', 'Continue', 1],
  'common.close': ['Cerrar', 'Close', 1],
  'common.back': ['Volver', 'Back', 1],
  'common.pause': ['Pausar', 'Pause', 2],
  'common.open': ['Abrir', 'Open', 2],
  'lock.lesson': ['Se abre al terminar la lección {n} · {title}', 'Opens when you finish lesson {n} · {title}', 4],

  // ---------- shell ----------
  'nav.today': ['Hoy', 'Today', 1],
  'nav.path': ['Ruta', 'Path', 1],
  'nav.review': ['Memoria', 'Memory', 1],
  'nav.free': ['Libre', 'Free', 1],
  'nav.studio': ['Tutora', 'Tutor', 2],
  'nav.me': ['Yo', 'Me', 1],
  'nav.admin': ['Admin', 'Admin', 1],
  'nav.aria': ['Navegación principal', 'Main', 3],
  'chip.streak': ['Racha de días', 'Day streak', 3],
  'chip.points': ['Puntos', 'Points', 2],
  'timer.theory': ['Teoría', 'Theory', 2],
  'timer.free': ['Inglés libre', 'Free English', 3],
  'timer.theoryAria': ['Cronómetro de teoría', 'Theory timer', 3],
  'timer.freeAria': ['Cronómetro de inglés libre', 'Free English timer', 3],
  'toast.stamp': ['Nuevo sello: {title}', 'New stamp: {title}', 3],
  'toast.level': ['Nivel {n}: {title}', 'Level {n}: {title}', 3],
  'toast.chapter': ['Empieza un nuevo capítulo.', 'A new chapter begins.', 4],

  // ---------- greetings & date parts ----------
  'greet.morning': ['Buenos días', 'Good morning', 2],
  'greet.afternoon': ['Buenas tardes', 'Good afternoon', 2],
  'greet.evening': ['Buenas noches', 'Good evening', 2],
  'week.aria': ['Esta semana', 'This week', 3],
  'week.met': ['Meta cumplida', 'Goal met', 3],
  'week.frozen': ['Protegido por un marcador', 'Protected by a bookmark', 5],
  'ring.of': ['de 20 min', 'of 20 min', 3],
  'morph.go': ['Transformar →', 'Transform →', 3],
  'morph.back': ['↺ Ver antes', '↺ Show before', 3],

  // ---------- level titles & stamps ----------
  'lvl.0': ['Página en blanco', 'Blank Page', 3], 'lvl.1': ['Boceto a lápiz', 'Pencil Sketch', 3], 'lvl.2': ['Carta de amor', 'Love Letter', 3],
  'lvl.3': ['Flor prensada', 'Pressed Flower', 3], 'lvl.4': ['Tinta y pluma', 'Ink & Quill', 3], 'lvl.5': ['Rincón de poesía', 'Poetry Corner', 3],
  'lvl.6': ['Musa de galería', 'Gallery Muse', 3], 'lvl.7': ['Cuaderno de París', 'Paris Notebook', 3], 'lvl.8': ['Editora en Manhattan', 'Manhattan Editor', 3],
  'lvl.9': ['Narradora de marcas', 'Brand Storyteller', 3], 'lvl.10': ['Directora creativa', 'Creative Director', 3], 'lvl.11': ['Musa de las palabras', 'Muse of Words', 3],
  'ach.first.t': ['Primera página', 'First page', 3], 'ach.first.d': ['Completa tu primera lección', 'Complete your first lesson', 4],
  'ach.s3.t': ['Tres velas', 'Three candles', 3], 'ach.s3.d': ['Racha de 3 días', '3-day streak', 3],
  'ach.s7.t': ['Una semana de amor', 'One week of love', 3], 'ach.s7.d': ['Racha de 7 días', '7-day streak', 3],
  'ach.s30.t': ['Un mes de rosas', 'A month of roses', 3], 'ach.s30.d': ['Racha de 30 días', '30-day streak', 3],
  'ach.s100.t': ['Cien días', 'One hundred days', 3], 'ach.s100.d': ['Racha de 100 días', '100-day streak', 3],
  'ach.c10.t': ['En llamas', 'On fire', 3], 'ach.c10.d': ['10 aciertos seguidos', '10 correct in a row', 4],
  'ach.c25.t': ['Sinfonía', 'Symphony', 3], 'ach.c25.d': ['25 aciertos seguidos', '25 correct in a row', 4],
  'ach.exam1.t': ['Sellado', 'Sealed', 3], 'ach.exam1.d': ['Aprueba tu primer examen de módulo', 'Pass your first module exam', 4],
  'ach.a2.t': ['¡Hola, A2!', 'Hello A2', 3], 'ach.a2.d': ['Aprueba el módulo 4', 'Pass module 4', 3],
  'ach.b1.t': ['¡Por fin B1!', 'B1 at last', 3], 'ach.b1.d': ['Aprueba el módulo 12', 'Pass module 12', 3],
  'ach.w100.t': ['Cien palabras', 'Hundred words', 3], 'ach.w100.d': ['100 palabras en tu caja de memoria', '100 words in your memory box', 4],
  'ach.r100.t': ['Guardiana de la memoria', 'Memory keeper', 4], 'ach.r100.d': ['100 respuestas de repaso', '100 review answers', 4],
  'ach.free10.t': ['Noche de cine', 'Movie night', 3], 'ach.free10.d': ['10 horas de inglés libre', '10 hours of free English', 3],
  'ach.theory20.t': ['Erudita', 'Scholar', 3], 'ach.theory20.d': ['20 horas de teoría', '20 hours of theory', 3],
  'ach.owl.t': ['Búho nocturno', 'Night owl', 3], 'ach.owl.d': ['Estudia después de las 10 p. m.', 'Study after 10 p.m.', 4],
  'ach.bird.t': ['Madrugadora', 'Early bird', 3], 'ach.bird.d': ['Estudia antes de las 7 a. m.', 'Study before 7 a.m.', 4],
  'ach.pen.t': ['Escritora', 'Writer', 3], 'ach.pen.d': ['Envía 5 textos a tu tutora', 'Send 5 texts to your tutor', 4],
  'ach.story.t': ['Cartas desde Nueva York', 'Letters from New York', 3], 'ach.story.d': ['Lee 6 capítulos de la historia', 'Read 6 story chapters', 4],

  // ---------- Today ----------
  'today.letter': ['Una carta para ti', 'A letter for you', 2],
  'today.letters': ['{n} cartas para ti', '{n} letters for you', 3],
  'today.note': ['Alguien te dejó una nota…', 'Someone left you a note…', 4],
  'today.goal': ['Meta de hoy', 'Today’s goal', 3],
  'today.theory': ['Teoría', 'Theory', 2],
  'today.free': ['Inglés libre', 'Free English', 3],
  'today.metMsg': ['¡Meta cumplida! Estoy orgullosa de ti.', 'Goal met. Proud of you!', 5],
  'today.left': ['Faltan {n} min para mantener la vela encendida', '{n} min to keep the candle lit', 5],
  'today.pick': [
    v => `Hoy haré **${v.t} min de teoría**${v.f ? ` + **${v.f} min de inglés libre**` : ' (hoy todo es teoría)'}`,
    v => `Today I’ll do **${v.t} min of theory**${v.f ? ` + **${v.f} min of free English**` : ' (all theory today)'}`, 5],
  'today.slider': ['Minutos de teoría hoy', 'Theory minutes today', 3],
  'today.streak': ['días de racha', 'day streak', 3],
  'today.protectors': [v => `${v.n} ${plural(v.n, 'protector', 'protectores')}`, v => `${v.n} protector${v.n === 1 ? '' : 's'}`, 3],
  'today.protectorsTip': ['Los protectores salvan tu racha si faltas un día. Ganas uno cada 7 días (máx. 2).', 'Protectors save your streak if you miss a day. You earn one every 7 days (max 2).', 5],
  'today.plan': ['Plan de hoy', 'Today’s plan', 3],
  'today.level': ['Nivel {n}', 'Level {n}', 2],
  'today.pts': ['pts', 'pts', 1],
  'today.keep': ['Guardarla ♥', 'Keep it ♥', 3],
  'today.metToast': ['🌸 ¡Lograste la meta de hoy! Tu racha está a salvo.', '🌸 Today’s goal is met. Your streak is safe!', 5],
  'plan.warm': ['Calienta tu memoria', 'Warm up your memory', 3],
  'plan.warmSub': [v => `${v.n} ${plural(v.n, 'palabra te espera', 'palabras te esperan')} en tu caja de memoria`, v => `${v.n} word${v.n === 1 ? ' is' : 's are'} waiting in your memory box`, 4],
  'plan.warmNone': ['Nada pendiente: prueba un repaso de hilos', 'Nothing due — try a thread review', 4],
  'plan.lessonSub': ['Lección {n} · {topic}', 'Lesson {n} · {topic}', 2],
  'plan.exam': ['{title} — examen', '{title} — exam', 3],
  'plan.examSub': ['Terminaste todas las lecciones. ¡Sella el módulo!', 'All lessons done. Seal the module!', 5],
  'plan.free': ['Inglés libre: {title}', 'Free English: {title}', 3],
  'plan.freeOpen': ['Inglés libre', 'Free English', 3],
  'plan.freeSub': ['Mira o escucha lo que quieras en inglés; las recomendaciones se abren con tus lecciones.', 'Watch or listen to anything in English; recommendations open as you learn.', 6],
  'plan.write': ['Escribe algo', 'Write something', 3],
  'plan.writeSub': ['Tu tutora te espera con un café', 'Your tutor is waiting with a coffee', 5],
  'plan.writeLocked': ['Se abre al terminar tu primera lección', 'Opens when you finish your first lesson', 5],
  'plan.continueSub': ['{what} · pregunta {i} de {n}', '{what} · question {i} of {n}', 4],
  'cont.lesson': ['Lección {n}', 'Lesson {n}', 2],
  'cont.exam': ['Examen del módulo {n}', 'Module {n} exam', 3],
  'cont.review': ['Repaso de memoria', 'Memory review', 3],
  'art.title': ['Pintura del día', 'Painting of the day', 3],
  'art.pd': ['dominio público', 'public domain', 4],
  'art.describe': ['Descríbela en inglés', 'Describe it in English', 3],
  'art.thread': ['hilo {n}', 'thread {n}', 4],
  'art.locked': ['Cada día aparecerá aquí una pintura para describirla en inglés. Todavía no tienes las palabras para hacerlo.',
    'A painting to describe in English will appear here every day. You don’t have the words for it yet.', 6],
  'poem.title': ['Poema del día', 'Poem of the day', 3],
  'poem.read': ['Leer el poema completo', 'Read the whole poem', 3],
  'poem.aloud': ['Leer en voz alta', 'Read aloud', 3],
  'poem.spot': ['Gramática en foco', 'Grammar spotlight', 4],
  'poem.see': ['— mira la lección {n}, {title}', '— see lesson {n}, {title}', 4],
  'poem.pd': ['Dominio público. Léelo en voz alta dos veces: una despacio y otra como una actriz.', 'Public domain. Read it aloud twice: once slowly, once like an actress.', 6],
  'poem.locked': ['Cada día aparecerá aquí un poema para leer en voz alta.', 'A poem to read aloud will appear here every day.', 6],

  // ---------- Path ----------
  'path.eyebrow': ['Tu ruta · A1 → B1', 'Your path · A1 → B1', 3],
  'path.h': ['El archivero', 'The cabinet', 3],
  'path.intro': ['Doce cajones, una historia. Aprueba el examen de cada módulo para abrir el siguiente, o hazlo antes si ya lo sabes.', 'Twelve drawers, one story. Pass each module’s exam to open the next one — or test out early if you already know it.', 6],
  'path.modules': ['Módulos', 'Modules', 2],
  'path.map': ['Mapa de hilos', 'Thread map', 3],
  'path.lessons': ['{done}/{n} lecciones', '{done}/{n} lessons', 3],
  'path.examBest': ['mejor examen {n}%', 'exam best {n}%', 4],
  'path.back': ['Volver a la ruta', 'Back to the path', 3],
  'module.eyebrow': ['Módulo {n} · {level}', 'Module {n} · {level}', 2],
  'lesson.label': ['Lección {n}', 'Lesson {n}', 2],
  'lesson.story': ['Capítulo de la historia', 'Story chapter', 3],
  'module.examEyebrow': ['Examen del módulo · aprueba con 70 %', 'Module exam · pass with 70%', 4],
  'module.sealed': ['Sellado ✓', 'Sealed ✓', 3],
  'module.ready': ['Estás lista', 'You’re ready', 4],
  'module.early': ['Hazlo antes', 'Test out early', 3],
  'module.best': ['Mejor: {n}%', 'Best: {n}%', 3],
  'module.questions': ['{n} preguntas, sin ayudas', '{n} questions, no hints', 5],
  'map.help': ['Cada punto es una lección; cada línea, una idea que vuelve. Toca un punto para ver sus hilos y tócalo otra vez para abrirlo.', 'Each dot is a lesson; each line, an idea that comes back. Tap a dot to see its threads, tap again to open it.', 6],
  'map.aria': ['Mapa de lecciones conectadas', 'Map of linked lessons', 5],

  // ---------- Lesson ----------
  'lesson.header': ['Lección {n} · {topic}', 'Lesson {n} · {topic}', 2],
  'lesson.notFound': ['No encontré esa lección.', 'Lesson not found.', 4],
  'lesson.lockedH': ['Este cajón sigue cerrado', 'This drawer is still locked', 4],
  'lesson.lockedP': ['Termina la lección anterior o aprueba el examen del módulo previo.', 'Finish the lesson before it — or pass the previous module’s exam.', 6],
  'lesson.esChip': ['ES · Explicación', 'ES · Explanation', 2],
  'lesson.esAria': ['Ver la explicación en español', 'Show the explanation in Spanish', 4],
  'resume.eyebrow': ['Sesión a medias', 'Session in progress', 3],
  'resume.h': ['Tu avance está guardado', 'Your progress is saved', 4],
  'resume.at': ['Vas en la pregunta {i} de {n}.', 'You’re on question {i} of {n}.', 5],
  'resume.continue': ['Continuar donde lo dejé', 'Continue where I left off', 5],
  'resume.restart': ['Empezar la lección de nuevo', 'Start the lesson over', 5],
  'brief.eyebrow': ['Antes de empezar', 'Before you begin', 2],
  'brief.forms': ['Forma correcta · error típico · por qué', 'Right form · typical mistake · why', 4],
  'brief.right': ['Correcto', 'Correct', 2],
  'brief.wrong': ['Incorrecto', 'Incorrect', 3],
  'brief.ojo': ['Ojo', 'Watch out', 3],
  'brief.cta': ['Entendido, empecemos', 'Got it, let’s start', 3],
  'brief.back': ['Volver a la lección', 'Back to the lesson', 3],
  'story.eyebrow': ['Cartas desde Nueva York', 'Letters from New York', 3],
  'story.aloud': ['Leer en voz alta', 'Read aloud', 3],
  'story.tip': ['Consejo: léela una vez sola; luego toca 🔊 y léela junto con el audio. Toca cualquier frase que te guste y dila en voz alta.', 'Tip: read it once alone, then tap 🔊 and read along. Tap any sentence you like and say it out loud.', 6],
  'story.done': ['Ya la leí', 'I’ve read it', 3],
  'theory.threads': ['Hilos', 'Threads', 4],
  'theory.builds': ['— esta lección se apoya en', '— this lesson builds on', 5],
  'theory.esAria': ['Ver en español', 'Show in Spanish', 3],
  'theory.esLabel': ['En español', 'In Spanish', 2],
  'theory.later': ['Más adelante, esta idea vuelve en: {list}', 'Coming later, this idea returns in: {list}', 5],
  'theory.words': ['Palabras nuevas', 'New words', 2],
  'words.tip': ['Toca una tarjeta para ver su significado. Estas palabras pasan a tu caja de memoria cuando termines.', 'Tap a card to see its meaning. These words go into your memory box when you finish.', 6],
  'words.flip': ['toca para voltear', 'tap to flip', 2],
  'words.reveal': ['toca para ver', 'tap to reveal', 2],
  'words.practice': ['Empezar la práctica', 'Start practice', 2],
  'done.h90': ['Exquisito.', 'Exquisite.', 3],
  'done.h70': ['Qué bien hecho.', 'Beautifully done.', 3],
  'done.h': ['Terminada, y eso cuenta.', 'Done — and that counts.', 4],
  'done.first': ['al primer intento', 'first try', 3],
  'done.points': ['puntos', 'points', 2],
  'done.combo': ['mejor racha', 'best combo', 3],
  'done.words': ['🗝️ {n} palabras nuevas entraron en tu caja de memoria. Volverán mañana.', '🗝️ {n} new words went into your memory box. They’ll come back tomorrow.', 6],
  'done.best': ['Tu mejor resultado en esta lección sigue siendo {n}%.', 'Your best on this lesson is still {n}%.', 5],
  'done.next': ['Siguiente: {title}', 'Next: {title}', 3],
  'done.exam': ['Hacer el examen del módulo', 'Take the module exam', 4],
  'done.again': ['Practicar otra vez', 'Practice again', 3],
  'done.today': ['Volver a hoy', 'Back to today', 3],

  // ---------- Exercises ----------
  'ex.mc': ['Elige la respuesta correcta', 'Choose the right answer', 3],
  'ex.read': ['Lectura', 'Reading', 2],
  'ex.fill': ['Completa el espacio', 'Fill in the blank', 3],
  'ex.fix': ['Encuentra y corrige el error', 'Find and fix the mistake', 4],
  'ex.type': ['Escríbelo', 'Type it', 3],
  'ex.order': ['Ordena las palabras', 'Put the words in order', 3],
  'ex.listen': ['Escucha y arma la frase', 'Listen and build the sentence', 4],
  'ex.speak': ['Dilo en voz alta', 'Say it out loud', 3],
  'ex.match': ['Une las parejas', 'Match the pairs', 3],
  'ex.card': ['Caja de memoria', 'Memory box', 3],
  'praise.0': ['¡Precioso!', 'Lovely!', 3], 'praise.1': ['¡Perfecto!', 'Perfect!', 3], 'praise.2': ['¡Brillante!', 'Brilliant!', 3], 'praise.3': ['¡Sí!', 'Yes!', 2],
  'praise.4': ['¡Hermoso!', 'Beautiful!', 3], 'praise.5': ['¡Exacto!', 'Exactly!', 3], 'praise.6': ['¡Chic!', 'Chic!', 3],
  'ex.reread': ['Leer el texto otra vez', 'Read the text again', 3],
  'ex.notQuite': ['Casi.', 'Not quite.', 3],
  'ex.answer': ['Respuesta:', 'Answer:', 3],
  'ex.listenBtn': ['escuchar', 'listen', 1],
  'ex.play': ['Reproducir la frase', 'Play sentence', 2],
  'ex.slow': ['Reproducir despacio', 'Play slowly', 2],
  'ex.rewrite': ['Reescribe la frase correctamente', 'Rewrite the sentence correctly', 4],
  'ex.missing': ['Escribe la palabra que falta', 'Type the missing word', 4],
  'ex.yourAnswer': ['Tu respuesta', 'Your answer', 3],
  'ex.yourSentence': ['Tu frase', 'Your sentence', 3],
  'ex.check': ['Comprobar', 'Check', 1],
  'ex.listenFirst': ['Escucha primero', 'Listen first', 2],
  'ex.startSpeak': ['Empezar a hablar', 'Start speaking', 3],
  'ex.listening': ['Escuchando…', 'Listening…', 3],
  'ex.almost': ['¡Casi! Inténtalo otra vez', 'Almost! Try once more', 4],
  'ex.tapMic': ['Toca el micrófono y lee la frase', 'Tap the mic and read the sentence', 5],
  'ex.heard': ['Escuché:', 'I heard:', 4],
  'ex.noMic': ['El micrófono no está disponible.', 'The microphone isn’t available.', 5],
  'ex.selfCheck': ['Léela en voz alta: primero despacio, luego natural. Sé honesta 💛', 'Read it out loud — slowly, then naturally. Be honest 💛', 6],
  'ex.said': ['La dije', 'I said it', 3],
  'ex.cantSpeak': ['Ahora no puedo hablar', 'Can’t speak right now', 4],
  'ex.explain': ['Explícame', 'Explain it', 3],
  'ex.thinking': ['Tu tutora está pensando…', 'Your tutor is thinking…', 4],
  'ex.tutorSays': ['Tu tutora explica', 'Your tutor explains', 4],
  'ex.trick': ['Truco:', 'Trick:', 4],
  'run.leaveAria': ['Salir', 'Leave', 1],
  'run.second': ['Segunda oportunidad: esta pregunta volvió para ti.', 'Second chance — this one came back for you.', 5],
  'run.comboTip': ['Las respuestas correctas seguidas multiplican tus puntos', 'Correct answers in a row multiply your points', 5],
  'run.inkTip': ['Llena la tinta para subir tu multiplicador', 'Fill the ink to raise your multiplier', 5],
  'run.correct': ['Correcto', 'Correct', 2],
  'run.oops': ['Ups', 'Oops', 2],
  'run.leaveH': ['¿Salir de esta sesión?', 'Leave this session?', 4],
  'run.leaveP': ['Tu avance queda guardado: podrás continuar justo donde lo dejaste.', 'Your progress is saved — you can pick up exactly where you left off.', 5],
  'run.keep': ['Seguir', 'Keep going', 2],
  'run.exit': ['Salir', 'Leave', 1],
  'card.howSay': ['¿Cómo se dice «{es}» en inglés?', 'How do you say “{es}” in English?', 3],

  // ---------- Review ----------
  'rev.eyebrow': ['Recuerda lo aprendido', 'Remember what you learned', 4],
  'rev.h': ['Caja de memoria', 'Memory box', 3],
  'rev.intro': ['Las palabras viajan del cajón 1 al 6. Cada acierto sube una palabra un cajón y vuelve más tarde; un error la devuelve al cajón 1.', 'Words travel from drawer 1 to drawer 6. Each correct answer moves a word one drawer up and it comes back later; a mistake sends it back to drawer 1.', 6],
  'rev.remembered': ['{n}% recordado', '{n}% remembered', 4],
  'rev.donePts': ['+{n} puntos · mejor racha {c}', '+{n} points · best combo {c}', 4],
  'rev.inBox': ['{n} palabras en tu caja · {m} dominadas', '{n} words in your box · {m} mastered', 4],
  'rev.continue': ['Continuar tu repaso', 'Continue your review', 4],
  'rev.contSub': ['Vas en la pregunta {i} de {n}', 'You’re on question {i} of {n}', 5],
  'rev.daily': ['Repaso diario', 'Daily review', 3],
  'rev.dailyDue': ['{n} palabras pendientes + hilos de lecciones pasadas', '{n} words due + threads from past lessons', 5],
  'rev.dailyThreads': ['Sin palabras pendientes: solo hilos', 'No words due — threads only', 5],
  'rev.dailyNone': ['Termina tu primera lección para llenar la caja', 'Finish your first lesson to fill the box', 5],
  'rev.threads': ['Tira de los hilos', 'Pull the threads', 4],
  'rev.threadsSub': ['Repasa {list} antes de «{title}»', 'Refresh {list} before “{title}”', 5],
  'rev.threadsMixed': ['Preguntas mezcladas de las lecciones que terminaste', 'Mixed questions from lessons you finished', 5],
  'rev.mistakes': ['Cuaderno de errores', 'Mistakes notebook', 4],
  'rev.mistakesSub': [v => `${v.n} ${plural(v.n, 'pregunta que fallaste', 'preguntas que fallaste')}: inténtalas otra vez`, v => `${v.n} question${v.n === 1 ? '' : 's'} you missed — try them again`, 5],
  'rev.noMistakes': ['Aún sin errores. Sospechosamente perfecto.', 'No mistakes yet. Suspiciously perfect.', 5],
  'rev.shuffle': ['Mezclar todas mis palabras', 'Shuffle all my words', 4],
  'rev.toLessons': ['Ir a las lecciones', 'Go to lessons', 3],

  // ---------- Exam ----------
  'exam.locked': ['Bloqueado', 'Locked', 2],
  'exam.lockedP': ['Aprueba antes el módulo anterior.', 'Pass the previous module first.', 5],
  'exam.eyebrow': ['Módulo {n} · examen', 'Module {n} · exam', 3],
  'exam.sealed': ['«{title}» quedó sellado.', '“{title}” is sealed.', 4],
  'exam.notSealed': ['Aún sin sellar, y está bien.', 'Not sealed yet — and that’s okay.', 5],
  'exam.nextOpen': ['El módulo {n}, «{title}», ya está abierto.', 'Module {n}, “{title}”, is now open.', 5],
  'exam.finished': ['Terminaste todo el recorrido. Eso es B1. 🗼', 'You finished the whole path. That’s B1. 🗼', 6],
  'exam.need70': ['Necesitas 70 %. Repasa los hilos y vuelve a intentarlo mañana: las preguntas cambian cada vez.', 'You need 70%. Review the threads below and try again tomorrow — the questions change every time.', 6],
  'exam.review': ['Revisa tus errores', 'Review your mistakes', 4],
  'exam.you': ['Tú:', 'You:', 3],
  'exam.ans': ['Respuesta:', 'Answer:', 3],
  'exam.openMod': ['Abrir el módulo {n}', 'Open module {n}', 3],
  'exam.reviewThreads': ['Repasar los hilos', 'Review the threads', 4],
  'exam.backModule': ['Volver al módulo', 'Back to the module', 3],
  'exam.seal': ['Sella este cajón', 'Seal this drawer', 4],
  'exam.b1': ['{n} preguntas de todo el módulo', '{n} questions from the whole module', 5],
  'exam.b2': ['Sin ayudas y sin racha: solo tú', 'No hints and no combo — just you', 5],
  'exam.b3': ['70 % abre el siguiente módulo (+150 puntos)', '70% opens the next module (+150 points)', 6],
  'exam.b4': ['Las preguntas cambian en cada intento', 'The questions change on every attempt', 6],
  'exam.resume': ['Tienes un examen a medias: vas en la pregunta {i} de {n}.', 'You have an exam in progress: question {i} of {n}.', 5],
  'exam.resumeBtn': ['Continuar el examen', 'Continue the exam', 4],
  'exam.restart': ['Empezar de nuevo', 'Start over', 3],
  'exam.begin': ['Comenzar', 'Begin', 2],

  // ---------- Free ----------
  'free.eyebrow': ['Inglés en la vida real', 'Input in the wild', 4],
  'free.h': ['Inglés libre', 'Free English', 3],
  'free.intro': ['Series, canciones, podcasts, libros. Inicia el cronómetro y ve a disfrutar: sigue contando mientras miras en otra app.', 'Series, songs, podcasts, books. Start the stopwatch, then go enjoy — it keeps counting while you watch in another app.', 6],
  'free.counting': ['Contando tu inglés libre', 'Counting your free English', 4],
  'free.stopwatch': ['Cronómetro', 'Stopwatch', 3],
  'free.goalMet': ['Meta de inglés libre cumplida ✓', 'Free-English goal met ✓', 5],
  'free.minLeft': ['Faltan {n} min para la meta de hoy', '{n} min left for today’s goal', 5],
  'free.bonus': ['Hoy es todo teoría: esto es un extra ✨', 'Today is all theory — this is a bonus ✨', 6],
  'free.act.series': ['📺 Series / película', '📺 Series / film', 3],
  'free.act.song': ['🎵 Canciones', '🎵 Songs', 3],
  'free.act.podcast': ['🎧 Podcast', '🎧 Podcast', 2],
  'free.act.video': ['▶️ YouTube', '▶️ YouTube', 1],
  'free.act.book': ['📖 Lectura', '📖 Reading', 3],
  'free.act.talk': ['💬 Conversación', '💬 Conversation', 3],
  'free.what': ['¿Qué estás viendo o escuchando? (opcional)', 'What are you watching / listening to? (optional)', 5],
  'free.pause': ['Pausar', 'Pause', 2],
  'free.start': ['Iniciar', 'Start', 1],
  'free.today': ['Hoy', 'Today', 1],
  'free.recommended': ['Recomendado para ti', 'Recommended for you', 4],
  'free.level': ['Nivel {l} · {m}', 'Level {l} · {m}', 3],
  'free.mission': ['Misión:', 'Mission:', 3],
  'free.thread': ['· hilo: módulo {n}', '· thread: module {n}', 4],
  'free.upcoming': ['Próximamente', 'Coming up', 3],
  'free.upcomingP': ['Se irán abriendo a medida que aprendas lo necesario para disfrutarlos.', 'They open as you learn what you need to enjoy them.', 6],
  'free.more': ['…y {n} más se irán abriendo.', '…and {n} more will open.', 4],
  'free.noneYet': ['Termina tu primera lección y aquí empezarán a aparecer recomendaciones.', 'Finish your first lesson and recommendations will start to appear here.', 6],
  'free.poems': ['Poemas para leer en voz alta', 'Poems to read aloud', 4],
  'free.toolbox': ['Caja de herramientas', 'Toolbox', 3],
  'free.openAria': ['Abrir {title}', 'Open {title}', 2],
  'kind.all': ['todo', 'all', 1], 'kind.series': ['series', 'series', 1], 'kind.film': ['películas', 'films', 2], 'kind.song': ['canciones', 'songs', 2],
  'kind.podcast': ['podcasts', 'podcasts', 1], 'kind.video': ['videos', 'videos', 1], 'kind.book': ['libros', 'books', 2], 'kind.tool': ['herramientas', 'tools', 3],
  'kind.site': ['sitios', 'sites', 3], 'kind.playlist': ['listas', 'playlists', 3],
  'kind1.series': ['serie', 'series', 1], 'kind1.film': ['película', 'film', 2], 'kind1.song': ['canción', 'song', 2], 'kind1.podcast': ['podcast', 'podcast', 1],
  'kind1.video': ['video', 'video', 1], 'kind1.book': ['libro', 'book', 2], 'kind1.tool': ['herramienta', 'tool', 3], 'kind1.site': ['sitio', 'site', 3], 'kind1.playlist': ['lista', 'playlist', 3],

  // ---------- Studio ----------
  'studio.eyebrow': ['Tu escritorio de escritura', 'Your writing desk', 4],
  'studio.h': ['Estudio', 'Studio', 3],
  'studio.intro': ['Escribe lo que quieras (un texto para redes, un poema, un correo) y tu tutora lo pule. O charla con Sam, de Maison Lumière, mientras toman un café.', 'Write anything — a caption, a poem, an email — and your tutor polishes it. Or have a coffee chat with Sam from Maison Lumière.', 6],
  'studio.tabWrite': ['Pule mi texto', 'Polish my writing', 4],
  'studio.tabChat': ['Charla con café', 'Coffee chat', 4],
  'studio.lockedH': ['Tu escritorio se abre pronto', 'Your desk opens soon', 4],
  'studio.lockedP': ['Primero aprende tus primeras frases: el escritorio y la charla con Sam se abren al terminar la lección {n} · {title}.', 'Learn your first sentences first: the desk and the chat with Sam open when you finish lesson {n} · {title}.', 6],
  'studio.prompt': ['Consigna', 'Prompt', 2],
  'studio.another': ['Otra consigna', 'Another prompt', 3],
  'studio.placeholder': ['Escribe aquí, en inglés. Los errores son bienvenidos.', 'Write here, in English. Mistakes are welcome.', 5],
  'studio.yourText': ['Tu texto', 'Your text', 3],
  'studio.words': ['{n} palabras', '{n} words', 3],
  'studio.counts': ['Escribir cuenta como teoría', 'Writing counts as theory time', 5],
  'studio.polish': ['Púlelo', 'Polish it', 3],
  'studio.reading': ['Tu tutora está leyendo…', 'Your tutor is reading…', 4],
  'studio.polished': ['Versión pulida', 'Polished version', 4],
  'studio.aloud': ['Leer en voz alta', 'Read aloud', 3],
  'studio.notice': ['Para fijarte', 'What to notice', 4],
  'studio.thread': ['Hilo: {n} {title}', 'Thread: {n} {title}', 4],
  'studio.native': ['Dilo como una nativa', 'Say it like a native', 5],
  'chat.typing': ['Sam está escribiendo…', 'Sam is typing…', 3],
  'chat.placeholder': ['Escríbele a Sam…', 'Write to Sam…', 3],
  'chat.send': ['Enviar', 'Send', 2],
  'chat.message': ['Mensaje', 'Message', 2],
  'chat.end': ['Terminar la charla y guardarla', 'End chat & save it', 4],

  // ---------- Me ----------
  'me.eyebrow': ['Nivel {n} · {xp} puntos', 'Level {n} · {xp} points', 3],
  'me.streak': ['Racha actual', 'Current streak', 3],
  'me.longest': ['mejor {n}', 'longest {n}', 4],
  'me.theory': ['Teoría', 'Theory', 2],
  'me.free': ['Inglés libre', 'Free English', 3],
  'me.allTime': ['en total', 'all time', 3],
  'me.accuracy': ['Precisión', 'Accuracy', 3],
  'me.answers': ['{n} respuestas', '{n} answers', 3],
  'me.words': ['Palabras', 'Words', 2],
  'me.inBox': ['en tu caja de memoria', 'in memory box', 4],
  'me.combo': ['Mejor racha', 'Best combo', 3],
  'me.inRow': ['seguidas', 'in a row', 4],
  'me.envelopes': ['Sobres sellados', 'Sealed envelopes', 4],
  'me.noEnv': ['Aún no hay sobres. Quizás alguien está preparando una sorpresa… 💌', 'No envelopes yet. Someone might be preparing a surprise… 💌', 6],
  'me.ready': ['¡Listo para abrir!', 'Ready to open!', 4],
  'me.surprise': ['Una sorpresa sellada', 'A sealed surprise', 4],
  'me.unlocksAt': ['Se abre con {n} {what}', 'Unlocks at {n} {what}', 5],
  'me.break': ['Romper el sello', 'Break the seal', 4],
  'me.stamps': ['Colección de sellos', 'Stamp collection', 4],
  'me.letters': ['Cartas', 'Letters', 3],
  'me.settings': ['Ajustes', 'Settings', 3],
  'me.target': ['Minutos de teoría por día (por defecto): {n}', 'Default theory minutes per day: {n}', 5],
  'me.admin': ['Panel de administración', 'Admin dashboard', 4],
  'me.signOut': ['Cerrar sesión', 'Sign out', 3],
  'me.unlocked': ['Desbloqueaste', 'You unlocked', 4],
  'me.lang': ['Idioma de la app', 'App language', 3],
  'me.langAuto': ['Automático: pasa al inglés mientras aprendes', 'Automatic: turns English as you learn', 5],
  'me.langEs': ['Todo en español', 'All in Spanish', 3],
  'me.langEn': ['All in English', 'All in English', 0],
  'me.langPct': ['Tu app ya habla inglés en un {n} %.', 'Your app already speaks {n}% English.', 5],
  'kl.streak': ['días de racha', 'day streak', 3], 'kl.xp': ['puntos', 'points', 2], 'kl.lessons': ['lecciones', 'lessons', 2],
  'kl.exams': ['exámenes de módulo', 'module exams', 4], 'kl.days': ['días con la meta cumplida', 'days with goal met', 5],

  // ---------- Auth ----------
  'auth.tag': ['Veinte minutos al día. Una historia. A1 → B1.', 'Twenty minutes a day. One story. A1 → B1.', 5],
  'auth.name': ['Tu nombre', 'Your name', 3],
  'auth.email': ['Correo electrónico', 'Email', 2],
  'auth.pass': ['Contraseña', 'Password', 2],
  'auth.in': ['Abrir mi cuaderno', 'Open my notebook', 3],
  'auth.up': ['Crear mi cuaderno', 'Create my notebook', 3],
  'auth.toUp': ['¿Primera vez? Crea una cuenta', 'First time? Create an account', 4],
  'auth.toIn': ['Ya tengo cuenta', 'I already have an account', 4],
  'auth.check': ['Revisa tu correo para confirmar tu cuenta 💌', 'Check your email to confirm your account 💌', 5],
  'auth.unconfirmed': ['Todavía no has confirmado tu correo. Abre el enlace que te enviamos, o pide uno nuevo.', 'You have not confirmed your email yet. Open the link we sent you, or ask for a new one.', 5],
  'auth.resend': ['Reenviar correo de confirmación', 'Resend confirmation email', 5],
  'auth.resendIn': ['Reenviar en {n} s', 'Resend in {n} s', 4],
  'auth.resent': ['Listo, te enviamos otro correo 💌', 'Done, we sent you another email 💌', 5],
  'auth.needEmail': ['Escribe tu correo arriba.', 'Type your email above.', 4],
  'auth.expired': ['Ese enlace ya venció o ya se usó. Pide uno nuevo.', 'That link has expired or was already used. Ask for a new one.', 5],
}
