// Free-English library. Links only (no copyrighted media is hosted here).
const yt = q => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`
const sp = q => `https://open.spotify.com/search/${encodeURIComponent(q)}`
const nf = q => `https://www.netflix.com/search?q=${encodeURIComponent(q)}`
const jw = q => `https://www.justwatch.com/us/search?q=${encodeURIComponent(q)}`

// level = minimum level where it becomes enjoyable; link = grammar module it trains
export const LIBRARY = [
  // Series & films — romance, New York, the 2000s, marketing
  { kind: 'series', title: 'Emily in Paris', level: 'A2', link: 'm4', needs: 'm3l5', why_es: 'Una estratega de marketing en el extranjero: literalmente tu futuro trabajo, con campañas y publicaciones.', mission_es: 'Mira 1 episodio con subtítulos en inglés. Anota 3 palabras de marketing que use Emily.', url: nf('Emily in Paris'), why: 'A marketing strategist abroad — literally your future job, with captions and campaigns.', mission: 'Watch 1 episode with English subtitles. Write down 3 marketing words Emily uses.' },
  { kind: 'film', title: 'How to Lose a Guy in 10 Days', level: 'A2', link: 'm7', needs: 'm7l2', why_es: 'Una periodista de revista contra un publicista en Nueva York de los 2000. ¡Hay pitches por todas partes!', mission_es: 'Encuentra 2 frases con "going to" o "will" en las escenas de la presentación.', url: jw('How to Lose a Guy in 10 Days'), why: 'A magazine writer vs. an ad executive in 2000s New York. Pitches everywhere!', mission: 'Find 2 sentences with "going to" or "will" in the pitch scenes.' },
  { kind: 'film', title: '13 Going on 30', level: 'A2', link: 'm5', needs: 'm5l3', why_es: 'Nueva York, una revista de moda y un relanzamiento creativo: pura década del 2000.', mission_es: 'Pausa cuando Jenna recuerda su pasado. Di una frase en pasado simple.', url: jw('13 Going on 30'), why: 'NYC, a fashion magazine and a creative relaunch — pure 2000s.', mission: 'Pause when Jenna remembers her past. Say one sentence with "used to" or past simple.' },
  { kind: 'film', title: 'The Devil Wears Prada', level: 'B1', link: 'm9', needs: 'm9l2', why_es: 'Moda, comunicación y la jefa más exigente de Nueva York.', mission_es: 'Escucha las reglas y obligaciones: must, have to, don’t.', url: jw('The Devil Wears Prada'), why: 'Fashion, communication and the toughest boss in New York.', mission: 'Listen for rules and obligations: must, have to, don’t.' },
  { kind: 'film', title: "You've Got Mail", level: 'B1', link: 'm10', needs: 'm9l5', why_es: 'Cartas, una pequeña librería y Nueva York en otoño. Muy Meri.', mission_es: 'Elige un correo de la película y reescríbelo con tus palabras.', url: jw("You've Got Mail"), why: 'Letters, a little bookshop and New York in autumn. Very Meri.', mission: 'Pick one email from the film and rewrite it in your own words.' },
  { kind: 'film', title: 'The Intern', level: 'A2', link: 'm8', needs: 'm8l1', why_es: 'Una startup de moda en Brooklyn; diálogos lentos y claros.', mission_es: 'Encuentra 3 frases con "have you ever / I’ve…".', url: jw('The Intern'), why: 'A fashion startup in Brooklyn; slow, clear dialogue.', mission: 'Find 3 sentences with "have you ever / I’ve…".' },
  { kind: 'series', title: 'Friends', level: 'A2', link: 'm2', needs: 'm2l3', why_es: 'El clásico para estudiantes: escenas cortas, inglés cotidiano, Nueva York.', mission_es: 'Mira un episodio y anota 5 rutinas que mencionan los personajes.', url: jw('Friends'), why: 'The classic for learners: short scenes, everyday English, New York.', mission: 'Watch one episode and list 5 routines the characters mention.' },
  { kind: 'series', title: 'Ugly Betty', level: 'B1', link: 'm6', needs: 'm6l3', why_es: 'Una latina en una revista de moda de Nueva York, años 2000. ¡Comparativos por todos lados!', mission_es: 'Escribe 3 comparaciones entre Betty y las otras editoras.', url: jw('Ugly Betty'), why: 'A Latina in a NYC fashion magazine, 2000s. Comparatives everywhere!', mission: 'Write 3 comparisons between Betty and the other editors.' },
  { kind: 'series', title: 'Gilmore Girls', level: 'B1', link: 'm11', needs: 'm11l1', why_es: 'Rápida, ingeniosa y llena de libros. Un gran reto en B1.', mission_es: 'Usa subtítulos en inglés. Atrapa una frase con "if" y anótala.', url: jw('Gilmore Girls'), why: 'Fast, witty and full of books. A great challenge at B1.', mission: 'Use English subtitles. Catch one "if" sentence and write it down.' },
  { kind: 'film', title: 'Midnight in Paris', level: 'B1', link: 'm11', needs: 'm11l3', why_es: 'Un escritor conoce a los artistas del París de los años 20. Arte + poesía + nostalgia.', mission_es: 'Responde: si pudieras visitar cualquier década, ¿cuál sería y por qué?', url: jw('Midnight in Paris'), why: 'A writer meets the artists of 1920s Paris. Art + poetry + nostalgia.', mission: 'Answer: if you could visit any decade, which one would it be and why?' },
  { kind: 'film', title: 'Little Women (2019)', level: 'B1', link: 'm12', needs: 'm12l4', why_es: 'Hermanas, escritura y cartas, como Rosa.', mission_es: 'Cuenta una escena usando "she said that…".', url: jw('Little Women 2019'), why: 'Sisters, writing and letters — like Rosa.', mission: 'Retell one scene using "she said that…".' },

  // Songs — if you love Camilo & Morat, try…
  { kind: 'song', title: "Jason Mraz — I'm Yours", level: 'A1', link: 'm7', needs: 'm1l2', why_es: 'Pop acústico y soleado: si te encanta la calidez de Camilo.', mission_es: 'Cuenta cuántas veces oyes "you". Luego canta el coro una vez.', url: yt("Jason Mraz I'm Yours lyrics"), why: 'Sunny acoustic pop — if you love Camilo’s warmth.', mission: 'Count how many times you hear "you". Then sing the chorus once.' },
  { kind: 'song', title: 'The Lumineers — Ho Hey', level: 'A1', link: 'm1', needs: 'm1l1', why_es: 'Banjo y palmas: el primo inglés más cercano de Morat.', mission_es: 'Escribe 3 palabras que reconozcas.', url: yt('The Lumineers Ho Hey lyrics'), why: 'Banjo and claps — the closest English cousin of Morat.', mission: 'Write 3 words you recognize.' },
  { kind: 'song', title: 'Ed Sheeran — Perfect', level: 'A2', link: 'm4', needs: 'm4l1', why_es: 'Lenta y clara; un clásico de las bodas.', mission_es: 'Encuentra los verbos con -ing (presente continuo).', url: yt('Ed Sheeran Perfect lyrics'), why: 'Slow and clear; a wedding classic.', mission: 'Find the -ing verbs (present continuous).' },
  { kind: 'song', title: 'Vance Joy — Riptide', level: 'A2', link: 'm2', needs: 'm2l1', why_es: 'Folk-pop con ukelele y una historia.', mission_es: 'Anota 2 frases en presente simple.', url: yt('Vance Joy Riptide lyrics'), why: 'Ukulele folk-pop with a story.', mission: 'Write down 2 sentences in present simple.' },
  { kind: 'song', title: 'Norah Jones — Don’t Know Why', level: 'A2', link: 'm5', needs: 'm5l2', why_es: 'Jazz suave para estudiar de noche.', mission_es: 'Encuentra los verbos en pasado simple.', url: yt('Norah Jones Dont Know Why lyrics'), why: 'Soft jazz for evening study.', mission: 'Find the past simple verbs.' },
  { kind: 'song', title: 'Laufey — From The Start', level: 'B1', link: 'm8', needs: 'm8l1', why_es: 'Bossa nova + poesía. Muy tú.', mission_es: 'Escucha con la letra. Encuentra un present perfect o un used to.', url: yt('Laufey From The Start lyrics'), why: 'Bossa nova + poetry. Very you.', mission: 'Listen with lyrics. Find one present perfect or used to.' },
  { kind: 'song', title: 'John Legend — All of Me', level: 'A2', link: 'm6', needs: 'm2l2', why_es: 'Balada de piano con pronunciación clara.', mission_es: 'Haz shadowing de la primera estrofa: escucha, pausa, repite.', url: yt('John Legend All of Me lyrics'), why: 'Piano ballad with clear pronunciation.', mission: 'Shadow the first verse: listen, pause, repeat.' },
  { kind: 'song', title: 'Jack Johnson — Better Together', level: 'A2', link: 'm6', needs: 'm6l3', why_es: 'Guitarra de domingo perezoso.', mission_es: 'Encuentra el comparativo del título y 2 más en la canción.', url: yt('Jack Johnson Better Together lyrics'), why: 'Lazy Sunday guitar.', mission: 'Find the comparative in the title and 2 more in the song.' },
  { kind: 'song', title: 'Bruno Mars — Just the Way You Are', level: 'A1', link: 'm1', needs: 'm1l1', why_es: 'Pop dulce lleno de to be.', mission_es: 'Cuenta las veces que oyes "is" o "are".', url: yt('Bruno Mars Just the Way You Are lyrics'), why: 'Sweet pop full of to be.', mission: 'Count the times you hear "is" or "are".' },
  { kind: 'playlist', title: 'Acoustic love songs (Spotify)', level: 'A1', link: 'm2', needs: 'm1l2', why_es: 'Inglés de fondo mientras ordenas tu escritorio.', mission_es: 'Ponla 10 minutos. Escribe 1 línea que hayas entendido.', url: sp('acoustic love songs'), why: 'Background English while you tidy your desk.', mission: 'Play it for 10 minutes. Write 1 line you understood.' },
  { kind: 'tool', title: 'LyricsTraining', level: 'A1', link: 'm4', needs: 'm1l2', why_es: 'Juego de completar letras con videos musicales reales. Adictivo.', mission_es: 'Juega una canción en modo Beginner.', url: 'https://lyricstraining.com/', why: 'Fill-in-the-lyrics game with real music videos. Addictive.', mission: 'Play one song in Beginner mode.' },

  // Podcasts & listening
  { kind: 'podcast', title: 'BBC 6 Minute English', level: 'A2', link: 'm2', needs: 'm3l5', why_es: 'Seis minutos, dos presentadores, un tema. Duración perfecta.', mission_es: 'Escúchalo una vez sin la transcripción y otra con ella.', url: 'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english', why: 'Six minutes, two hosts, one topic. Perfect length.', mission: 'Listen once without the transcript, once with it.' },
  { kind: 'podcast', title: 'VOA Learning English', level: 'A1', link: 'm1', needs: 'm1l5', why_es: 'Noticias en inglés americano, lento y claro.', mission_es: 'Lee y escucha una historia corta.', url: 'https://learningenglish.voanews.com/', why: 'Slow, clear American English news.', mission: 'Read and listen to one short story.' },
  { kind: 'podcast', title: 'BBC The English We Speak', level: 'B1', link: 'm10', needs: 'm9l5', why_es: 'Una expresión moderna en tres minutos.', mission_es: 'Aprende la expresión y úsala hoy en un mensaje.', url: 'https://www.bbc.co.uk/learningenglish/english/features/the-english-we-speak', why: 'One modern expression in three minutes.', mission: 'Learn the expression and use it in a message today.' },
  { kind: 'podcast', title: 'All Ears English', level: 'B1', link: 'm9', needs: 'm9l5', why_es: 'Conversación natural en inglés americano: carreras y conexión.', mission_es: 'Escucha un episodio sobre trabajo o entrevistas.', url: sp('All Ears English'), why: 'Natural American conversation, careers and connection.', mission: 'Listen to one episode about work or interviews.' },
  { kind: 'video', title: 'Vogue — 73 Questions', level: 'B1', link: 'm8', needs: 'm8l1', why_es: 'Famosos responden preguntas rápidas en casa. Belleza, hogares, estilo.', mission_es: 'Responde en voz alta 5 de las preguntas sobre ti.', url: yt('Vogue 73 Questions'), why: 'Celebrities answer quick questions at home. Beauty, homes, style.', mission: 'Answer 5 of the questions about yourself, out loud.' },
  { kind: 'video', title: 'Vogue — Beauty Secrets', level: 'A2', link: 'm6', needs: 'm6l2', why_es: 'Rutinas de skincare = imperativos + cantidades. Tu futura industria.', mission_es: 'Anota 5 productos y una palabra de cantidad (some, a little…).', url: yt('Vogue Beauty Secrets'), why: 'Skincare routines = imperatives + quantities. Your future industry.', mission: 'List 5 products and one quantity word (some, a little…).' },
  { kind: 'video', title: 'English with Lucy', level: 'A2', link: 'm3', needs: 'm2l1', why_es: 'Profesora británica elegante; gramática y pronunciación.', mission_es: 'Mira un video de gramática relacionado con tu módulo actual.', url: yt('English with Lucy'), why: 'Elegant British teacher; grammar and pronunciation.', mission: 'Watch one grammar video connected to your current module.' },
  { kind: 'video', title: "Rachel's English", level: 'A2', link: 'm5', needs: 'm5l2', why_es: 'Pronunciación americana, paso a paso.', mission_es: 'Practica las terminaciones -ed (/t/ /d/ /ɪd/).', url: yt("Rachel's English"), why: 'American pronunciation, step by step.', mission: 'Practice the -ed endings (/t/ /d/ /ɪd/).' },
  { kind: 'video', title: 'Isabel Allende on TED', level: 'B1', link: 'm10', needs: 'm12l4', why_es: 'Tu autora favorita habla inglés con acento latino, como lo harás tú.', mission_es: 'Míralo con subtítulos en inglés. Escribe 2 frases que dijo, en reported speech: "She said that…".', url: 'https://www.ted.com/search?q=Isabel+Allende', why: 'Your favorite author speaks English with a Latin American accent — like you will.', mission: 'Watch with English subtitles. Write 2 sentences she said, reported: "She said that…".' },

  // Reading
  { kind: 'book', title: 'Isabel Allende — Eva Luna (English)', level: 'B1', link: 'm10', needs: 'm10l1', why_es: 'Lee un capítulo que ya conoces en español, ahora en inglés.', mission_es: 'Lee 2 páginas. Subraya cada past continuous.', url: 'https://www.google.com/search?tbm=bks&q=Eva+Luna+Isabel+Allende+English', why: 'Read a chapter you already know in Spanish — now in English.', mission: 'Read 2 pages. Underline every past continuous.' },
  { kind: 'book', title: 'Rupi Kaur — milk and honey', level: 'A2', link: 'm1', needs: 'm1l5', why_es: 'Poemas modernos, cortos y sencillos.', mission_es: 'Copia tu poema favorito en tu cuaderno y tradúcelo.', url: 'https://www.google.com/search?tbm=bks&q=Rupi+Kaur+milk+and+honey', why: 'Short, simple modern poems.', mission: 'Copy your favorite poem in your notebook and translate it.' },
  { kind: 'book', title: 'The Little Prince (English)', level: 'A2', link: 'm5', needs: 'm5l3', why_es: 'Una historia que sabes de memoria: el puente perfecto.', mission_es: 'Lee un capítulo al día.', url: 'https://www.google.com/search?tbm=bks&q=The+Little+Prince+English', why: 'A story you know by heart — perfect bridge.', mission: 'Read one chapter a day.' },
  { kind: 'book', title: 'Graded readers (Oxford Bookworms / Penguin Readers)', level: 'A2', link: 'm5', needs: 'm5l2', why_es: 'Novelas clásicas reescritas para tu nivel.', mission_es: 'Elige un romance de nivel 2.', url: 'https://www.google.com/search?q=Oxford+Bookworms+level+2', why: 'Classic novels rewritten for your level.', mission: 'Choose one romance at level 2.' },
  { kind: 'site', title: 'Poetry Foundation', level: 'B1', link: 'm12', needs: 'm10l5', why_es: 'Miles de poemas con audio.', mission_es: 'Busca un poema de Mary Oliver y léelo en voz alta.', url: 'https://www.poetryfoundation.org/', why: 'Thousands of poems with audio.', mission: 'Find one poem by Mary Oliver and read it aloud.' },
  { kind: 'site', title: 'Google Arts & Culture', level: 'A2', link: 'm3', needs: 'm3l1', why_es: 'Recorridos por museos con descripciones en inglés.', mission_es: 'Describe una pintura: "There is… / There are…".', url: 'https://artsandculture.google.com/', why: 'Museum tours with English descriptions.', mission: 'Describe one painting: "There is… / There are…".' },
]

export const KINDS = ['all', 'series', 'film', 'song', 'podcast', 'video', 'book', 'tool', 'site', 'playlist']

export const TOOLS = [
  { title: 'Cambridge Dictionary', url: 'https://dictionary.cambridge.org/dictionary/english-spanish/', why: 'English–Spanish with audio (UK & US).', why_es: 'Inglés–español con audio (británico y americano).' },
  { title: 'YouGlish', url: 'https://youglish.com/', why: 'Hear any word in real YouTube videos.', why_es: 'Escucha cualquier palabra dentro de videos reales de YouTube.' },
  { title: 'Reverso Context', url: 'https://context.reverso.net/translation/english-spanish/', why: 'See words inside real sentences.', why_es: 'Mira las palabras dentro de frases reales.' },
  { title: 'DeepL', url: 'https://www.deepl.com/translator', why: 'The most natural translator.', why_es: 'El traductor más natural.' },
  { title: 'LanguageTool', url: 'https://languagetool.org/', why: 'Grammar checker for emails and posts.', why_es: 'Corrector de gramática para correos y publicaciones.' },
  { title: 'Forvo', url: 'https://forvo.com/', why: 'Pronunciation by native speakers.', why_es: 'Pronunciación de hablantes nativos.' },
  { title: 'British Council LearnEnglish', url: 'https://learnenglish.britishcouncil.org/', why: 'Free graded lessons and exercises.', why_es: 'Lecciones y ejercicios graduados y gratuitos.' },
  { title: 'LyricsTraining', url: 'https://lyricstraining.com/', why: 'Learn with songs, as a game.', why_es: 'Aprende con canciones, como un juego.' },
]

// Tips of the day. needs = lesson that makes the tip usable
export const TIPS = [
  { t: 'Change your phone language to English for one week. Your brain will adapt.', es: 'Cambia el idioma de tu celular a inglés por una semana. Tu cerebro se adaptará.', needs: 'm1l1' },
  { t: 'Write tomorrow’s to-do list in English tonight.', es: 'Escribe esta noche en inglés tu lista de pendientes de mañana.', needs: 'm1l5' },
  { t: 'Shadowing: play one sentence, pause, repeat it with the same melody.', es: 'Shadowing: reproduce una frase, pausa y repítela con la misma melodía.', needs: 'm1l1' },
  { t: 'Watch with English subtitles, not Spanish. Spanish subtitles = reading, not listening.', es: 'Mira con subtítulos en inglés, no en español. Subtítulos en español = leer, no escuchar.', needs: 'm1l5' },
  { t: 'Talk to yourself while you cook: "Now I’m cutting the onion…"', es: 'Háblate a ti misma mientras cocinas: "Now I’m cutting the onion…"', needs: 'm4l1' },
  { t: 'Keep a "beautiful words" page in your notebook.', es: 'Ten en tu cuaderno una página de "palabras bonitas".', needs: 'm1l1' },
  { t: 'Read your favorite Allende chapter in English — you already know the story.', es: 'Lee tu capítulo favorito de Allende en inglés: ya conoces la historia.', needs: 'm5l3' },
  { t: 'Record a 30-second voice note in English. Listen to it in a month.', es: 'Graba una nota de voz de 30 segundos en inglés. Escúchala en un mes.', needs: 'm2l1' },
  { t: 'Follow 3 beauty or marketing accounts that post in English.', es: 'Sigue 3 cuentas de belleza o de marketing que publiquen en inglés.', needs: 'm1l5' },
  { t: 'Learn sentences, not words. "I’d like to…" is worth more than "like".', es: 'Aprende frases, no palabras sueltas. "I’d like to…" vale más que "like".', needs: 'm7l4' },
  { t: 'When you don’t know a word, describe it: "the thing you use to…".', es: 'Cuando no sepas una palabra, descríbela: "the thing you use to…".', needs: 'm4l4' },
  { t: 'Mistakes are proof you are trying. Celebrate them.', es: 'Los errores son prueba de que lo estás intentando. Celébralos.', needs: 'm1l1' },
  { t: 'Sing in the shower. Seriously — it trains rhythm and pronunciation.', es: 'Canta en la ducha. En serio: entrena el ritmo y la pronunciación.', needs: 'm1l1' },
  { t: 'Rewrite a LinkedIn post from a brand you admire in your own words.', es: 'Reescribe con tus palabras una publicación de LinkedIn de una marca que admires.', needs: 'm10l4' },
]

// Public-domain poems (all published before 1929). link = the lesson they illuminate
export const POEMS = [
  { title: 'What Is Pink?', author: 'Christina Rossetti', year: 1872, level: 'A1', link: 'm1l1', needs: 'm1l2', spotlight_es: 'Preguntas y respuestas con to be: What is pink? A rose is pink.', spotlight: 'Questions and answers with to be: What is pink? A rose is pink.',
    text: `What is pink? a rose is pink\nBy the fountain's brink.\nWhat is red? a poppy's red\nIn its barley bed.\nWhat is blue? the sky is blue\nWhere the clouds float thro'.\nWhat is white? a swan is white\nSailing in the light.\nWhat is yellow? pears are yellow,\nRich and ripe and mellow.\nWhat is green? the grass is green,\nWith small flowers between.\nWhat is violet? clouds are violet\nIn the summer twilight.\nWhat is orange? Why, an orange,\nJust an orange!`,
    glossary: [['brink', 'borde'], ['poppy', 'amapola'], ['swan', 'cisne'], ['ripe', 'maduro'], ['twilight', 'crepúsculo']] },
  { title: "I'm Nobody! Who are you?", author: 'Emily Dickinson', year: 1891, level: 'A2', link: 'm1l2', needs: 'm1l5', spotlight_es: 'Preguntas con to be — y una broma sobre la publicidad.', spotlight: 'Questions with to be — and a joke about advertising!',
    text: `I'm Nobody! Who are you?\nAre you – Nobody – too?\nThen there's a pair of us!\nDon't tell! they'd advertise – you know!\n\nHow dreary – to be – Somebody!\nHow public – like a Frog –\nTo tell one's name – the livelong June –\nTo an admiring Bog!`,
    glossary: [['a pair of us', 'un par'], ['advertise', 'anunciar / publicitar'], ['dreary', 'aburrido, triste'], ['livelong', 'entero'], ['bog', 'pantano']] },
  { title: 'Who Has Seen the Wind?', author: 'Christina Rossetti', year: 1872, level: 'A2', link: 'm4l1', needs: 'm4l1', spotlight_es: 'Presente continuo: the wind is passing through.', spotlight: 'Present continuous: the wind is passing through.',
    text: `Who has seen the wind?\nNeither I nor you:\nBut when the leaves hang trembling,\nThe wind is passing through.\n\nWho has seen the wind?\nNeither you nor I:\nBut when the trees bow down their heads,\nThe wind is passing by.`,
    glossary: [['neither… nor', 'ni… ni'], ['trembling', 'temblando'], ['bow down', 'inclinarse']] },
  { title: 'I Wandered Lonely as a Cloud (stanza 1)', author: 'William Wordsworth', year: 1807, level: 'A2', link: 'm5l3', needs: 'm5l3', spotlight_es: 'Pasado simple: I wandered, I saw.', spotlight: 'Past simple: I wandered, I saw.',
    text: `I wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils;\nBeside the lake, beneath the trees,\nFluttering and dancing in the breeze.`,
    glossary: [['wander', 'vagar'], ["o'er", 'over (sobre)'], ['vale', 'valle'], ['host', 'multitud'], ['daffodil', 'narciso'], ['breeze', 'brisa']] },
  { title: 'Barter', author: 'Sara Teasdale', year: 1917, level: 'B1', link: 'm4l4', needs: 'm5l5', spotlight_es: 'Imperativos: Spend all you have for loveliness, buy it…', spotlight: 'Imperatives: Spend all you have for loveliness, buy it…',
    text: `Life has loveliness to sell,\nAll beautiful and splendid things,\nBlue waves whitened on a cliff,\nSoaring fire that sways and sings,\nAnd children's faces looking up\nHolding wonder like a cup.\n\nLife has loveliness to sell,\nMusic like a curve of gold,\nScent of pine trees in the rain,\nEyes that love you, arms that hold,\nAnd for your spirit's still delight,\nHoly thoughts that star the night.\n\nSpend all you have for loveliness,\nBuy it and never count the cost;\nFor one white singing hour of peace\nCount many a year of strife well lost,\nAnd for a breath of ecstasy\nGive all you have been, or could be.`,
    glossary: [['loveliness', 'belleza'], ['cliff', 'acantilado'], ['sway', 'mecerse'], ['scent', 'aroma'], ['strife', 'lucha'], ['barter', 'trueque']] },
  { title: 'There Will Come Soft Rains', author: 'Sara Teasdale', year: 1918, level: 'B1', link: 'm7l2', needs: 'm7l2', spotlight_es: 'Futuro con will: there will come, robins will wear.', spotlight: 'Future with will: there will come, robins will wear.',
    text: `There will come soft rains and the smell of the ground,\nAnd swallows circling with their shimmering sound;\n\nAnd frogs in the pools singing at night,\nAnd wild plum trees in tremulous white;\n\nRobins will wear their feathery fire,\nWhistling their whims on a low fence-wire;\n\nAnd not one will know of the war, not one\nWill care at last when it is done.\n\nNot one would mind, neither bird nor tree,\nIf mankind perished utterly;\n\nAnd Spring herself, when she woke at dawn\nWould scarcely know that we were gone.`,
    glossary: [['swallow', 'golondrina'], ['shimmering', 'resplandeciente'], ['plum tree', 'ciruelo'], ['robin', 'petirrojo'], ['whim', 'capricho'], ['scarcely', 'apenas']] },
  { title: '"Hope" is the thing with feathers', author: 'Emily Dickinson', year: 1891, level: 'B1', link: 'm8l1', needs: 'm8l1', spotlight_es: 'Presente perfecto: I\'ve heard it in the chillest land.', spotlight: "Present perfect: I've heard it in the chillest land.",
    text: `"Hope" is the thing with feathers -\nThat perches in the soul -\nAnd sings the tune without the words -\nAnd never stops - at all -\n\nAnd sweetest - in the Gale - is heard -\nAnd sore must be the storm -\nThat could abash the little Bird\nThat kept so many warm -\n\nI've heard it in the chillest land -\nAnd on the strangest Sea -\nYet - never - in Extremity,\nIt asked a crumb - of me.`,
    glossary: [['feathers', 'plumas'], ['perch', 'posarse'], ['tune', 'melodía'], ['gale', 'vendaval'], ['abash', 'avergonzar / acallar'], ['crumb', 'migaja']] },
  { title: 'Sonnet 18', author: 'William Shakespeare', year: 1609, level: 'B1', link: 'm6l3', needs: 'm6l3', spotlight_es: 'Comparativos: more lovely and more temperate.', spotlight: 'Comparatives: more lovely and more temperate.',
    text: `Shall I compare thee to a summer's day?\nThou art more lovely and more temperate:\nRough winds do shake the darling buds of May,\nAnd summer's lease hath all too short a date;\nSometime too hot the eye of heaven shines,\nAnd often is his gold complexion dimm'd;\nAnd every fair from fair sometime declines,\nBy chance or nature's changing course untrimm'd;\nBut thy eternal summer shall not fade,\nNor lose possession of that fair thou ow'st;\nNor shall Death brag thou wander'st in his shade,\nWhen in eternal lines to time thou grow'st:\nSo long as men can breathe or eyes can see,\nSo long lives this, and this gives life to thee.`,
    glossary: [['thee / thou', 'te / tú (antiguo)'], ['art', 'are (antiguo)'], ['temperate', 'templado'], ['buds', 'capullos'], ['lease', 'arriendo, plazo'], ['fade', 'desvanecerse']] },
]

// Writing prompts for the studio. needs = lesson that gives her the grammar for it
export const PROMPTS = [
  { needs: 'm1l1', text: 'Write three sentences about you: "I am…", "I am from…", "I am… (a feeling)".', es: 'Escribe tres frases sobre ti: "I am…", "I am from…", "I am… (un sentimiento)".' },
  { needs: 'm1l3', text: 'Introduce yourself in 5 sentences: name, city, job, two things you love.', es: 'Preséntate en 5 frases: nombre, ciudad, trabajo y dos cosas que amas.' },
  { needs: 'm3l1', text: 'Describe your favorite room. Use there is / there are.', es: 'Describe tu habitación favorita. Usa there is / there are.' },
  { needs: 'm2l3', text: 'Write your morning routine with always, usually and sometimes.', es: 'Escribe tu rutina de la mañana con always, usually y sometimes.' },
  { needs: 'm4l4', text: 'Write an Instagram caption for a new perfume. Include a call to action.', es: 'Escribe un texto de Instagram para un perfume nuevo. Incluye un llamado a la acción.' },
  { needs: 'm5l3', text: 'Tell a childhood memory with your grandmother (past simple).', es: 'Cuenta un recuerdo de infancia con tu abuela (pasado simple).' },
  { needs: 'm6l3', text: 'Compare two beauty products you use. Which is better and why?', es: 'Compara dos productos de belleza que uses. ¿Cuál es mejor y por qué?' },
  { needs: 'm4l1', text: 'Write a 4-line poem about New York in autumn.', es: 'Escribe un poema de 4 líneas sobre Nueva York en otoño.' },
  { needs: 'm8l4', text: 'Write a short LinkedIn "About" section for a communication strategist.', es: 'Escribe una sección "Acerca de" corta de LinkedIn para una estratega de comunicación.' },
  { needs: 'm8l1', text: 'Answer the interview question: "Have you ever handled a difficult situation at work?"', es: 'Responde la pregunta de entrevista: "Have you ever handled a difficult situation at work?"' },
  { needs: 'm9l1', text: 'Write a polite email asking to reschedule a meeting.', es: 'Escribe un correo cortés pidiendo reprogramar una reunión.' },
  { needs: 'm11l3', text: 'If you worked at a beauty brand, what campaign would you create?', es: 'Si trabajaras en una marca de belleza, ¿qué campaña crearías?' },
]

// Painting of the day — public-domain works on Wikimedia Commons. link = lesson the describing task trains
const wm = file => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=800`
export const ART = [
  { title: 'Woman with a Parasol', artist: 'Claude Monet', year: 1875, img: wm('Claude Monet - Woman with a Parasol - Madame Monet and Her Son - Google Art Project.jpg'), link: 'm4l1', needs: 'm4l1', task: 'What is she doing? What is the wind doing? Use the present continuous.', task_es: '¿Qué está haciendo ella? ¿Qué hace el viento? Usa el presente continuo.' },
  { title: 'Luncheon of the Boating Party', artist: 'Pierre-Auguste Renoir', year: 1881, img: wm('Pierre-Auguste Renoir - Luncheon of the Boating Party - Google Art Project.jpg'), link: 'm4l1', needs: 'm4l1', task: 'Choose three people. What are they doing right now?', task_es: 'Elige a tres personas. ¿Qué están haciendo ahora mismo?' },
  { title: 'Girl with a Pearl Earring', artist: 'Johannes Vermeer', year: 1665, img: wm('1665 Girl with a Pearl Earring.jpg'), link: 'm3l3', needs: 'm3l3', task: 'Describe her: she has… Her eyes are… Her scarf is… (have/has + adjectives, possessives).', task_es: 'Descríbela: She has… Her eyes are… (have/has + adjetivos y posesivos).' },
  { title: "The Child's Bath", artist: 'Mary Cassatt', year: 1893, img: wm("Mary Cassatt - The Child's Bath - Google Art Project.jpg"), link: 'm3l1', needs: 'm3l1', task: 'There is… / There are… — list everything you can see.', task_es: 'There is… / There are… — enumera todo lo que veas.' },
  { title: 'Interior, Strandgade 30', artist: 'Vilhelm Hammershøi', year: 1900, img: wm('Vilhelm Hammershøi, Interiør fra Strandgade 30, 1900.jpg'), link: 'm3l2', needs: 'm3l2', task: 'Where is everything? Use in, on, next to, behind.', task_es: '¿Dónde está cada cosa? Usa in, on, next to, behind.' },
  { title: 'Almond Blossom', artist: 'Vincent van Gogh', year: 1890, img: wm('Amandelbloesem - s0176V1962 - Van Gogh Museum.jpg'), link: 'm5l3', needs: 'm5l3', task: 'Van Gogh painted this for his baby nephew. Write 3 sentences in the past.', task_es: 'Van Gogh pintó esto para su sobrino recién nacido. Escribe 3 frases en pasado.' },
  { title: 'The Bedroom', artist: 'Vincent van Gogh', year: 1888, img: wm('La Chambre à Arles, by Vincent van Gogh, from C2RMF.jpg'), link: 'm3l3', needs: 'm3l3', task: 'Describe the room with adjectives in the right order.', task_es: 'Describe la habitación con adjetivos en el orden correcto.' },
  { title: 'The Kiss', artist: 'Gustav Klimt', year: 1908, img: wm('The Kiss - Gustav Klimt - Google Cultural Institute.jpg'), link: 'm6l4', needs: 'm6l4', task: 'Is it the most romantic painting you know? Use superlatives.', task_es: '¿Es la pintura más romántica que conoces? Usa superlativos.' },
  { title: 'Water Lilies', artist: 'Claude Monet', year: 1906, img: wm('Claude Monet - Water Lilies - 1906, Ryerson.jpg'), link: 'm11l3', needs: 'm11l3', task: 'If you were in this garden, what would you do?', task_es: 'Si estuvieras en este jardín, ¿qué harías?' },
  { title: 'The Cradle', artist: 'Berthe Morisot', year: 1872, img: wm('Berthe Morisot - The Cradle - Google Art Project.jpg'), link: 'm10l1', needs: 'm10l1', task: 'Tell the scene: what was happening when the artist painted it?', task_es: 'Cuenta la escena: ¿qué estaba pasando cuando la artista la pintó?' },
  { title: 'Carnation, Lily, Lily, Rose', artist: 'John Singer Sargent', year: 1886, img: wm('John Singer Sargent - Carnation, Lily, Lily, Rose - Google Art Project.jpg'), link: 'm4l1', needs: 'm4l1', task: 'What are the girls doing? What time of day is it?', task_es: '¿Qué están haciendo las niñas? ¿Qué hora del día es?' },
  { title: 'The Swing', artist: 'Jean-Honoré Fragonard', year: 1767, img: wm('Joean Honoré Fragonard - The Swing.jpg'), link: 'm6l4', needs: 'm6l4', task: 'Compare this painting with The Kiss. Which is more…?', task_es: 'Compara esta pintura con El beso. ¿Cuál es más…?' },
  { title: 'The Great Wave off Kanagawa', artist: 'Katsushika Hokusai', year: 1831, img: wm('Great Wave off Kanagawa2.jpg'), link: 'm7l2', needs: 'm7l2', task: 'What will happen next? Make 3 predictions with will.', task_es: '¿Qué pasará después? Haz 3 predicciones con will.' },
  { title: 'Paris Street; Rainy Day', artist: 'Gustave Caillebotte', year: 1877, img: wm('Gustave Caillebotte - Paris Street; Rainy Day - Google Art Project.jpg'), link: 'm10l2', needs: 'm10l2', task: 'Write a story: they were walking when…', task_es: 'Escribe una historia: they were walking when…' },
  { title: 'The Milkmaid', artist: 'Johannes Vermeer', year: 1658, img: wm('Johannes Vermeer - Het melkmeisje - Google Art Project.jpg'), link: 'm2l1', needs: 'm2l1', task: 'Imagine her daily routine. Use the present simple.', task_es: 'Imagina su rutina diaria. Usa el presente simple.' },
  { title: 'A Bar at the Folies-Bergère', artist: 'Édouard Manet', year: 1882, img: wm('Edouard Manet, A Bar at the Folies-Bergère.jpg'), link: 'm8l1', needs: 'm8l1', task: 'Have you ever been to a place like this? What has she seen tonight?', task_es: '¿Has estado alguna vez en un lugar así? ¿Qué ha visto ella esta noche?' },
  { title: 'I Am Half-Sick of Shadows', artist: 'John William Waterhouse', year: 1915, img: wm('John William Waterhouse - I am half-sick of shadows, said the lady of shalott.JPG'), link: 'm9l3', needs: 'm9l3', task: 'Give her advice: she should… / she shouldn’t…', task_es: 'Dale un consejo: she should… / she shouldn’t…' },
]
