// Content format (all modules):
// theory block: { h, p, es, table?, anim?: [from, to], ex?: [] }
// vocab: [english, spanish, example]
// exercises (tuples):
//   ['mc', prompt, 'right|wrong|wrong', why]      ['fill', 'with ___', 'ans|alt', why]
//   ['fix', wrong sentence, 'right|alt', why]       ['order', sentence, spanish?]
//   ['listen', sentence]  ['speak', sentence]       ['read', question, 'right|wrong|wrong', why]
// links: earlier lessons this one builds on (the "threads")
export default {
  id: 'm1', level: 'A1+', title: "Hello, It's Me", subtitle: 'The verb to be · introductions',
  goal: 'Introduce yourself with confidence — name, origin, job and feelings.',
  lessons: [
    {
      id: 'm1l1', title: 'I am, you are', topic: 'to be: affirmative',
      intro: 'The most important verb in English. You already know it — let’s make it solid.',
      theory: [
        { h: 'One verb, three forms', p: 'The verb to be has three forms in the present: am, is, are. Each person has its own form.',
          es: 'El verbo to be (ser/estar) tiene tres formas: am (yo), is (él/ella/eso), are (tú, nosotros, ellos).',
          table: [['I', 'am', "I'm"], ['you', 'are', "you're"], ['he / she / it', 'is', "he's / she's / it's"], ['we / they', 'are', "we're / they're"]] },
        { h: 'Contractions sound natural', p: 'In conversation we join the words. It sounds softer and more natural.',
          es: 'En conversación casi siempre se contrae: I am → I’m.', anim: ['I am a communicator', "I'm a communicator"],
          ex: ["I'm Meri.", "She's in Paris.", "We're friends."] },
        { h: 'Ser and estar = to be', p: 'In Spanish you have ser and estar. In English, to be does both jobs.',
          es: 'Soy colombiana = I am Colombian. Estoy cansada = I am tired. Mismo verbo.',
          ex: ['I am Colombian. (ser)', 'I am tired. (estar)', 'The coffee is hot.'] },
      ],
      vocab: [['communicator', 'comunicadora', "I'm a social communicator."], ['happy', 'feliz', 'She is happy today.'], ['tired', 'cansada', "I'm tired after work."],
        ['friend', 'amiga / amigo', 'Laura is my friend.'], ['from', 'de (origen)', "I'm from Colombia."], ['beautiful', 'hermoso', 'The poem is beautiful.'],
        ['ready', 'lista', "I'm ready to learn."], ['excited', 'emocionada', "We're excited about the trip."]],
      ex: [
        ['mc', 'She ___ in New York.', 'is|am|are', 'He / she / it → is.'],
        ['mc', 'We ___ ready for the class.', 'are|is|am', 'We → are.'],
        ['fill', 'I ___ from Colombia.', "am|'m", 'I → am.'],
        ['fill', 'They ___ my friends.', "are|'re", 'They → are.'],
        ['fix', 'She are a designer.', 'She is a designer.|She’s a designer.', 'She → is, never are.'],
        ['mc', 'Which is the contraction of "it is"?', "it's|its|it'is", "It is = it's. (Its without apostrophe means 'su', possession.)"],
        ['order', "I'm a social communicator", 'Soy comunicadora social'],
        ['listen', "We're excited about New York."],
        ['speak', "Hello! I'm Meri and I'm from Colombia."],
      ],
      links: [],
    },
    {
      id: 'm1l2', title: "Is she…? She isn't…", topic: 'to be: negatives & questions',
      intro: 'Ask questions and say no — politely.',
      theory: [
        { h: 'Negative: add not', p: 'Put not after am / is / are. The contractions are isn’t and aren’t.',
          es: 'Negativo: am not, is not (isn’t), are not (aren’t). Ojo: no existe “amn’t”.',
          table: [['I', "am not", "I'm not"], ['he / she / it', 'is not', "isn't"], ['you / we / they', 'are not', "aren't"]] },
        { h: 'Questions: swap the order', p: 'To make a question, move am / is / are to the front. Watch it move:',
          es: 'Para preguntar, el verbo va al principio. No necesitas “do”.', anim: ['She is from Paris', 'Is she from Paris?'],
          ex: ['Are you tired?', 'Is it expensive?', 'Am I late?'] },
        { h: 'Short answers', p: 'Answer with yes or no + pronoun + verb. Never contract a positive short answer.',
          es: 'Respuestas cortas: Yes, I am. / No, I’m not. (Nunca “Yes, I’m.”)',
          ex: ['Are you ready? — Yes, I am.', 'Is he French? — No, he isn’t.'] },
      ],
      vocab: [['late', 'tarde', "Sorry, I'm late!"], ['busy', 'ocupada', 'Are you busy today?'], ['married', 'casada', 'Is she married?'],
        ['single', 'soltera', "No, she's single."], ['expensive', 'caro', 'Is it expensive?'], ['cheap', 'barato', "It isn't cheap."],
        ['right', 'correcto / tener razón', "You're right!"], ['wrong', 'equivocado', "I'm not wrong."]],
      ex: [
        ['mc', '___ you busy today?', 'Are|Is|Am', 'You → are. In questions it goes first.'],
        ['mc', 'Is Laura French? — No, she ___.', "isn't|aren't|not is", 'She → is not → isn’t.'],
        ['mc', 'Are you tired? — Yes, ___.', "I am|I'm|I'm am", 'Never contract a positive short answer.'],
        ['fill', 'The coffee ___ cheap here. It’s $8! (negative)', "isn't|is not", 'It → is not → isn’t.'],
        ['fix', 'You is late.', "You are late.|You're late.", 'You → are.'],
        ['fix', 'She not is married.', "She isn't married.|She is not married.|She's not married.", 'Not goes after the verb.'],
        ['order', 'Is the museum open today', '¿El museo está abierto hoy?'],
        ['order', "We aren't from Paris", 'No somos de París'],
        ['listen', 'Are you ready for the meeting?'],
        ['speak', "No, I'm not tired. I'm excited!"],
      ],
      links: ['m1l1'],
    },
    {
      id: 'm1l3', title: 'My name, her job', topic: 'possessives & a/an',
      intro: 'Talk about people: whose things, what job.',
      theory: [
        { h: 'Possessive adjectives', p: 'They go before a noun and never change for plural.',
          es: 'my (mi/mis), your (tu), his (su, de él), her (su, de ella), its (su, de eso), our (nuestro), their (su, de ellos).',
          table: [['I → my', 'my name'], ['you → your', 'your book'], ['he → his', 'his job'], ['she → her', 'her perfume'], ['we → our', 'our home'], ['they → their', 'their city']] },
        { h: "The 's of possession", p: "Add 's to a person to say what is theirs. The owner goes first.",
          es: 'El libro de Meri = Meri’s book. El dueño va primero.', anim: ['the book of Meri', "Meri's book"],
          ex: ["Laura's apartment", "my mother's name"] },
        { h: 'a / an + jobs', p: 'In English, jobs need a or an. Use an before a vowel sound.',
          es: 'Soy periodista = I am a journalist. Con sonido de vocal: an artist, an editor.',
          ex: ["She's a designer.", "He's an artist.", "I'm an English student."] },
      ],
      vocab: [['job', 'trabajo', "What's your job?"], ['journalist', 'periodista', "She's a journalist."], ['designer', 'diseñadora', 'Her sister is a designer.'],
        ['manager', 'gerente', 'Our manager is French.'], ['artist', 'artista', "He's an artist."], ['company', 'empresa', 'Their company is in New York.'],
        ['brand', 'marca', 'It is a beauty brand.'], ['surname', 'apellido', "What's your surname?"]],
      ex: [
        ['mc', 'Laura has a sister. ___ sister is a designer.', 'Her|His|Their', 'Laura is a woman → her.'],
        ['mc', 'Sam is from Boston. ___ job is in marketing.', 'His|Her|Its', 'Sam is a man → his.'],
        ['mc', "She's ___ editor at a magazine.", 'an|a|—', 'Editor starts with a vowel sound → an.'],
        ['fill', "I'm ___ journalist.", 'a', 'Jobs need a / an. Journalist starts with a consonant sound.'],
        ['fix', 'She is designer.', "She is a designer.|She's a designer.", 'Jobs always need a / an.'],
        ['fix', 'The perfume of Meri is French.', "Meri's perfume is French.", "Use 's: Meri's perfume."],
        ['mc', 'We love ___ new apartment.', 'our|we|us', 'We → our.'],
        ['order', "What's your surname", '¿Cuál es tu apellido?'],
        ['listen', "My friend's company is in New York."],
        ['speak', "I'm a communicator and I love my job."],
      ],
      links: ['m1l1'],
    },
    {
      id: 'm1l4', title: 'This, these & plurals', topic: 'this/that · plurals',
      intro: 'Point at things near and far — one or many.',
      theory: [
        { h: 'Near and far', p: 'This / these = near you. That / those = far from you.',
          es: 'this (este/esta), these (estos), that (ese/aquel), those (esos/aquellos).',
          table: [['', 'one', 'many'], ['near', 'this', 'these'], ['far', 'that', 'those']] },
        { h: 'Plurals', p: 'Most nouns add -s. Nouns ending in -s, -sh, -ch, -x add -es. Consonant + y → -ies.',
          es: 'book → books, dress → dresses, diary → diaries. Irregulares: woman → women, person → people.',
          anim: ['this lipstick is red', 'these lipsticks are red'] },
        { h: 'Adjectives never change', p: 'English adjectives have no plural and go before the noun.',
          es: 'Flores rojas = red flowers (no “reds”). El adjetivo va antes.',
          ex: ['beautiful flowers', 'old chairs', 'these white cups'] },
      ],
      vocab: [['notebook', 'cuaderno', 'This notebook is beautiful.'], ['pen', 'bolígrafo', 'Those pens are gold.'], ['flower', 'flor', 'These flowers are for you.'],
        ['chair', 'silla', 'That chair is antique.'], ['candle', 'vela', 'These candles smell nice.'], ['dress', 'vestido', 'Those dresses are expensive.'],
        ['diary', 'diario', 'My diaries are in the drawer.'], ['people', 'personas', 'These people are artists.']],
      ex: [
        ['mc', '___ flowers here are for you. (near, many)', 'These|This|Those', 'Near + many → these.'],
        ['mc', 'Look at ___ painting over there!', 'that|this|these', 'Far + one → that.'],
        ['mc', 'Plural of "diary":', 'diaries|diarys|diaryes', 'Consonant + y → -ies.'],
        ['mc', 'Plural of "woman":', 'women|womans|womens', 'Irregular plural.'],
        ['fill', 'Those ___ (dress) are beautiful.', 'dresses', 'Ends in -s → add -es.'],
        ['fix', 'These chairs are olds.', 'These chairs are old.', 'Adjectives have no plural.'],
        ['fix', 'This candles are white.', 'These candles are white.', 'Plural → these.'],
        ['order', 'Those antique chairs are beautiful', 'Esas sillas antiguas son hermosas'],
        ['listen', 'These notebooks are perfect for poems.'],
        ['speak', 'This candle smells like vanilla.'],
      ],
      links: ['m1l1', 'm1l3'],
    },
    {
      id: 'm1l5', title: 'Letters from New York · Ch.1', topic: 'story: to be', story: true,
      intro: 'Chapter 1 of Meri’s story. Read, listen, and see everything you learned in this module working together.',
      read: { title: 'Hello, it’s me', text:
`Hello! My name is Meri. I'm from Colombia and I'm a social communicator. I'm not a journalist — I'm a strategist. My favorite things are art, poetry, old furniture and quiet songs.

This is my notebook. It's small and white, and my English words are in it. My friend Laura is an English teacher. She's very patient.

My dream is simple: a job in communication at a beauty brand. Is it difficult? Yes, it is. Am I ready? Not yet. But I'm excited.

Today is day one.` },
      theory: [
        { h: 'Read like a writer', p: 'Notice the forms of to be, the possessives (my, her) and this / these. You learned all of them in this module.',
          es: 'Lee el texto buscando am / is / are, my / her, y this. Todo es del módulo 1.' },
      ],
      vocab: [['strategist', 'estratega', "I'm a strategist."], ['dream', 'sueño', 'My dream is simple.'], ['patient', 'paciente', "She's very patient."],
        ['quiet', 'tranquilo / suave', 'I love quiet songs.'], ['not yet', 'todavía no', 'Am I ready? Not yet.'], ['furniture', 'muebles', 'Old furniture is beautiful.']],
      ex: [
        ['read', 'Where is Meri from?', 'Colombia|France|New York', '"I\'m from Colombia."'],
        ['read', 'What is Meri’s job?', 'A social communicator|A journalist|An English teacher', 'She is a communicator and a strategist.'],
        ['read', 'Who is Laura?', 'Her friend, an English teacher|Her sister|Her manager', '"My friend Laura is an English teacher."'],
        ['read', 'Is Meri ready for her dream job?', 'Not yet|Yes, she is|She isn’t excited', '"Am I ready? Not yet."'],
        ['fix', 'Laura are very patient.', "Laura is very patient.|Laura's very patient.", 'Laura = she → is.'],
        ['mc', 'Meri: "___ notebook is small and white."', 'My|Me|I', 'Possessive → my.'],
        ['listen', "My dream is a job at a beauty brand."],
        ['speak', 'Today is day one.'],
      ],
      links: ['m1l1', 'm1l2', 'm1l3', 'm1l4'],
    },
  ],
  exam: [
    ['mc', 'They ___ from Medellín.', 'are|is|am', 'They → are.'],
    ['mc', '___ he an artist? — Yes, he is.', 'Is|Are|Does', 'Questions with to be: verb first.'],
    ['mc', 'This is Sam. ___ office is in Brooklyn.', 'His|Her|Your', 'Sam → his.'],
    ['mc', "She's ___ actress.", 'an|a|the', 'Vowel sound → an.'],
    ['mc', 'Plural of "person":', 'people|persons|peoples', 'Irregular plural.'],
    ['fill', 'I ___ not tired. (contraction)', "'m", "I am not → I'm not."],
    ['fill', '___ shoes over there are cute.', 'Those', 'Far + many → those.'],
    ['fix', 'My sister are a nurse.', "My sister is a nurse.|My sister's a nurse.", 'Sister = she → is.'],
    ['fix', 'Are you happy? — Yes, I’m.', 'Yes, I am.', 'No contraction in positive short answers.'],
    ['fix', 'Is she a engineer?', 'Is she an engineer?', 'Engineer → an.'],
    ['order', "Is your apartment far from here", '¿Tu apartamento está lejos de aquí?'],
    ['listen', "Their company isn't in Paris."],
  ],
}
