export default {
  id: 'm2', level: 'A1+', title: 'A Day in My Life', subtitle: 'Present simple · routines · time',
  goal: 'Describe your routine, your habits and how often you do things.',
  lessons: [
    {
      id: 'm2l1', title: 'I work, she works', topic: 'present simple: affirmative',
      intro: 'Habits, routines and facts. Watch out for the famous -s.',
      theory: [
        { h: 'Habits and facts', p: 'Use the present simple for things that are **always true** or that you do **regularly**.',
          es: 'Presente simple = **rutinas y verdades**. I **drink** coffee **every morning**.',
          ex: ['I drink coffee every morning.', 'Laura teaches English.', 'The museum opens at ten.'] },
        { h: 'He / she / it + s', p: 'With **he, she and it**, the verb takes **-s**. This is the most common mistake — make it yours!',
          es: 'Con **he/she/it** el verbo lleva **-s**. Es el error más común en español-hablantes.', anim: ['I work in marketing', 'She works in marketing'] },
        { h: 'Spelling of -s', p: 'Most verbs: **+s**. After -s, -sh, -ch, -x, -o: **+es**. Consonant + y: **-ies**. Have → **has**.',
          es: 'watch → **watches**, go → **goes**, study → **studies**, have → **has**.',
          table: [['work', 'works'], ['watch', 'watches'], ['go', 'goes'], ['study', 'studies'], ['have', 'has']] },
      ],
      vocab: [['wake up', 'despertarse', 'I wake up at six.'], ['get dressed', 'vestirse', 'She gets dressed quickly.'], ['have breakfast', 'desayunar', 'We have breakfast together.'],
        ['commute', 'viaje al trabajo', 'My commute is short.'], ['meeting', 'reunión', 'She has a meeting at nine.'], ['listen to', 'escuchar', 'He listens to jazz.'],
        ['study', 'estudiar', 'Meri studies English.'], ['go to bed', 'ir a dormir', 'I go to bed at eleven.']],
      ex: [
        ['mc', 'Meri ___ English every day.', 'studies|study|studys', 'She → -s; consonant + y → -ies.'],
        ['mc', 'I ___ coffee in the morning.', 'drink|drinks|drinking', 'I → no -s.'],
        ['mc', 'Laura ___ a cat.', 'has|have|haves', 'Have → has with she.'],
        ['fill', 'He ___ (watch) Emily in Paris on Fridays.', 'watches', 'Ends in -ch → -es.'],
        ['fill', 'The office ___ (open) at eight.', 'opens', 'It → -s.'],
        ['fix', 'She work in a beauty company.', 'She works in a beauty company.', 'She → works.'],
        ['fix', 'My mother go to the gym.', 'My mother goes to the gym.', 'Go → goes.'],
        ['order', 'She listens to quiet songs at night', 'Ella escucha canciones tranquilas de noche'],
        ['listen', 'He has a meeting every Monday.'],
        ['speak', 'I wake up at six and I drink coffee.'],
      ],
      links: ['m1l1'],
    },
    {
      id: 'm2l2', title: "Do you…? She doesn't…", topic: 'present simple: do/does',
      intro: 'The helper verbs do and does. They carry the -s for you.',
      theory: [
        { h: 'Negatives with don’t / doesn’t', p: 'Use **don’t** (do not) and **doesn’t** (does not) + the **base verb**. The -s moves to **doesn’t**!',
          es: 'Negativo: **don’t / doesn’t** + verbo **SIN -s**. She **doesn’t work** (no “doesn’t works”).', anim: ['She works on Sundays', "She doesn't work on Sundays"] },
        { h: 'Questions with do / does', p: 'Put **do or does** at the front. The main verb has **no -s**.',
          es: 'Pregunta: **Do/Does + sujeto + verbo base**. **Does she like** tea?', anim: ['She likes tea', 'Does she like tea?'] },
        { h: 'But not with to be!', p: 'Remember module 1: **to be** makes questions alone. Never “**Do you are…?**”',
          es: 'Con **to be NO** se usa do: **Are you tired?** (no “Do you are tired?”).', ex: ['Are you tired?', 'Do you feel tired?'] },
      ],
      vocab: [['like', 'gustar', 'Do you like poetry?'], ['live', 'vivir', 'Where do you live?'], ['work', 'trabajar', "She doesn't work on Sundays."],
        ['weekend', 'fin de semana', 'What do you do on the weekend?'], ['tea', 'té', 'Does he drink tea?'], ['need', 'necesitar', "I don't need help."],
        ['cook', 'cocinar', 'Do you cook?'], ['early', 'temprano', 'She gets up early.']],
      ex: [
        ['mc', '___ you like jazz?', 'Do|Does|Are', 'You → do.'],
        ['mc', 'Laura ___ eat meat.', "doesn't|don't|isn't", 'She → doesn’t.'],
        ['mc', 'Does Sam ___ in Brooklyn?', 'live|lives|living', 'After does → base verb.'],
        ['fill', 'We ___ work on weekends. (negative)', "don't|do not", 'We → don’t.'],
        ['fill', '___ your sister cook?', 'Does', 'Sister = she → does.'],
        ['fix', "She doesn't likes coffee.", "She doesn't like coffee.", 'The -s goes to doesn’t, not to the verb.'],
        ['fix', 'Do you are ready?', 'Are you ready?', 'To be never uses do.'],
        ['order', 'What do you do on the weekend', '¿Qué haces el fin de semana?'],
        ['listen', "He doesn't need a car in New York."],
        ['speak', 'Do you like poetry? Yes, I do.'],
      ],
      links: ['m2l1', 'm1l2'],
    },
    {
      id: 'm2l3', title: 'Always, sometimes, never', topic: 'adverbs of frequency',
      intro: 'How often? Words that make your routine sound real.',
      theory: [
        { h: 'From 100% to 0%', p: '**always** → **usually** → **often** → **sometimes** → **rarely** → **never**.',
          es: '**always** (siempre) **usually** (normalmente) **often** (a menudo) **sometimes** (a veces) **rarely** (casi nunca) **never** (nunca).',
          table: [['always', '100%'], ['usually', '80%'], ['often', '60%'], ['sometimes', '40%'], ['rarely', '10%'], ['never', '0%']] },
        { h: 'Before the main verb…', p: 'The adverb goes **before the main verb**.',
          es: 'Va **antes del verbo principal**: I **always drink** tea.', anim: ['I drink tea', 'I always drink tea'] },
        { h: '…but after to be', p: 'With **am / is / are**, the adverb goes **after the verb**.',
          es: 'Con **to be** va **después**: She **is always** late.', anim: ['She is late', 'She is always late'] },
      ],
      vocab: [['always', 'siempre', 'I always write in my diary.'], ['usually', 'normalmente', 'She usually takes the bus.'], ['often', 'a menudo', 'We often visit museums.'],
        ['sometimes', 'a veces', 'I sometimes read poetry.'], ['rarely', 'casi nunca', 'He rarely cooks.'], ['never', 'nunca', 'She is never late.'],
        ['once a week', 'una vez por semana', 'I go to yoga once a week.'], ['every day', 'todos los días', 'I study every day.']],
      ex: [
        ['mc', 'Choose the correct order:', 'I usually read at night.|I read usually at night.|Usually I read at night always.', 'Adverb before the main verb.'],
        ['mc', 'Choose the correct order:', 'She is never late.|She never is late.|Never she is late.', 'After to be.'],
        ['mc', '0% = ___', 'never|rarely|sometimes', 'Never = 0%.'],
        ['fill', 'I ___ drink coffee. I love it! (100%)', 'always', '100% = always.'],
        ['fix', 'He goes always to the gym.', 'He always goes to the gym.', 'Adverb before goes.'],
        ['fix', 'They usually are happy.', 'They are usually happy.', 'With to be, adverb after.'],
        ['order', 'We often visit art museums', 'A menudo visitamos museos de arte'],
        ['order', 'My coffee is always hot', 'Mi café siempre está caliente'],
        ['listen', 'She sometimes writes poems on the train.'],
        ['speak', 'I always study English in the morning.'],
      ],
      links: ['m2l1', 'm1l1'],
    },
    {
      id: 'm2l4', title: 'At seven, on Monday, in May', topic: 'time & prepositions',
      intro: 'Tell the time and organize your week.',
      theory: [
        { h: 'Telling the time', p: 'It’s seven **o’clock**. It’s **half past** seven (7:30). It’s **quarter to** eight (7:45).',
          es: '**o’clock** = en punto, **half past** = y media, **quarter past** = y cuarto, **quarter to** = menos cuarto.',
          ex: ["It's nine o'clock.", "It's quarter past three.", "It's 6:20 (six twenty)."] },
        { h: 'at / on / in', p: '**AT** for exact times, **ON** for days and dates, **IN** for months, years and parts of the day.',
          es: '**at** 7:00 · **on** Monday · **in** May · **in** the morning (pero: **at** night).',
          table: [['at', 'times · night · the weekend (UK)'], ['on', 'days · dates'], ['in', 'months · years · seasons · the morning']] },
        { h: 'Questions about time', p: '**What time do you…?** **When does…?** **How often do you…?** — they connect with lesson 2.2!',
          es: 'Las preguntas usan **do/does** (lección 2.2).', ex: ['What time do you wake up?', 'When does the store open?'] },
      ],
      vocab: [['o’clock', 'en punto', "It's ten o'clock."], ['half past', 'y media', "It's half past six."], ['quarter to', 'menos cuarto', "It's quarter to nine."],
        ['noon', 'mediodía', 'We have lunch at noon.'], ['schedule', 'horario', 'My schedule is busy.'], ['appointment', 'cita', 'I have an appointment on Friday.'],
        ['spring', 'primavera', 'Paris is beautiful in spring.'], ['tonight', 'esta noche', 'What do you do tonight?']],
      ex: [
        ['mc', 'My birthday is ___ June.', 'in|on|at', 'Months → in.'],
        ['mc', 'The meeting is ___ Tuesday.', 'on|in|at', 'Days → on.'],
        ['mc', 'I go to bed ___ 11 p.m.', 'at|on|in', 'Exact time → at.'],
        ['mc', '7:30 =', "half past seven|half to seven|seven and half", 'Half past = y media.'],
        ['fill', 'She reads ___ night.', 'at', 'Exception: at night.'],
        ['fill', 'I study ___ the morning.', 'in', 'Parts of the day → in.'],
        ['fix', 'What time you wake up?', 'What time do you wake up?', 'Questions need do (lesson 2.2).'],
        ['order', 'The museum opens at ten on Sundays', 'El museo abre a las diez los domingos'],
        ['listen', "It's quarter to nine. I'm late!"],
        ['speak', 'I have an appointment on Friday at three.'],
      ],
      links: ['m2l2'],
    },
    {
      id: 'm2l5', title: 'Letters from New York · Ch.2', topic: 'story: present simple', story: true,
      intro: 'Chapter 2: Meri’s mornings — and a strange shop on her street.',
      read: { title: 'My mornings', text:
`I usually wake up at six. I don't like alarms, so my phone plays a soft song. I have breakfast at half past six: coffee, bread and fruit.

Then I study English for twenty minutes. Laura says, "Practice is a habit, not a mood." She's right.

At eight I take the bus to work. My commute is forty minutes. I always read on the bus — right now it's a novel by Isabel Allende.

On Saturdays I walk to a small antique shop on my street. The owner is an old man. He never smiles, but he always says, "Good morning, writer." I don't know why he calls me that.` },
      theory: [
        { h: 'Spot the routine', p: 'Find the **present simple** verbs, the **adverbs of frequency** and the **time prepositions**. Everything from module 2 is in this chapter.',
          es: 'Busca los verbos en **presente simple**, **always/usually/never** y **at/on/in**.' },
      ],
      vocab: [['alarm', 'alarma', "I don't like alarms."], ['habit', 'hábito', 'Practice is a habit.'], ['mood', 'estado de ánimo', 'Not a mood.'],
        ['novel', 'novela', "It's a novel by Isabel Allende."], ['owner', 'dueño', 'The owner is an old man.'], ['smile', 'sonreír', 'He never smiles.']],
      ex: [
        ['read', 'What time does Meri have breakfast?', 'At half past six|At six|At eight', '"I have breakfast at half past six."'],
        ['read', 'What does she do on the bus?', 'She reads|She studies English|She sleeps', '"I always read on the bus."'],
        ['read', 'What does the old man call her?', '“Writer”|“Teacher”|“Meri”', '"Good morning, writer."'],
        ['read', 'How often does the owner smile?', 'Never|Always|On Saturdays', '"He never smiles."'],
        ['fix', 'Meri take the bus at eight.', 'Meri takes the bus at eight.', 'She → takes.'],
        ['fix', 'She reads always on the bus.', 'She always reads on the bus.', 'Adverb before the verb.'],
        ['mc', 'Laura: "Practice is a habit, ___ a mood."', 'not|no|don’t', 'Not + noun.'],
        ['listen', 'On Saturdays I walk to a small antique shop.'],
        ['speak', 'Practice is a habit, not a mood.'],
      ],
      links: ['m2l1', 'm2l3', 'm2l4', 'm1l5'],
    },
  ],
  exam: [
    ['mc', 'My brother ___ in a bank.', 'works|work|working', 'He → works.'],
    ['mc', '___ she speak French?', 'Does|Do|Is', 'She → does.'],
    ['mc', 'We ___ have class on Fridays.', "don't|doesn't|aren't", 'We → don’t.'],
    ['mc', 'Correct order:', 'He is often tired.|He often is tired.|Often he tired is.', 'After to be.'],
    ['mc', 'See you ___ Monday!', 'on|in|at', 'Days → on.'],
    ['fill', 'She ___ (fly) to Paris every summer.', 'flies', 'Consonant + y → -ies.'],
    ['fill', 'I rarely ___ TV. I prefer books.', 'watch', 'I → base verb.'],
    ['fix', 'Does he works on Saturday?', 'Does he work on Saturday?', 'After does → base verb.'],
    ['fix', 'I go to the cinema in Friday.', 'I go to the cinema on Friday.', 'Days → on.'],
    ['fix', "Laura don't drink coffee.", "Laura doesn't drink coffee.", 'She → doesn’t.'],
    ['order', 'How often do you go to museums', '¿Con qué frecuencia vas a museos?'],
    ['listen', 'She never studies after ten at night.'],
  ],
}
