export default {
  id: 'm3', level: 'A1→A2', title: 'Home Sweet Home', subtitle: 'There is/are · place · can',
  goal: 'Describe a beautiful room, where things are and what you can do.',
  lessons: [
    {
      id: 'm3l1', title: 'There is a vintage mirror', topic: 'there is / there are',
      intro: 'Describe your dream room, Pinterest-style.',
      theory: [
        { h: 'Say what exists', p: '**There is** + one thing. **There are** + many things.',
          es: 'Hay = **there is** (singular) / **there are** (plural).', anim: ['There is a lamp', 'There are two lamps'] },
        { h: 'Negatives and questions', p: '**There isn’t / there aren’t**. **Is there…? Are there…?** (Just like to be in module 1!)',
          es: 'Funciona igual que **to be**: **Is there** a sofa? — Yes, **there is**.', ex: ["There isn't a TV.", 'Are there any plants? — Yes, there are.'] },
        { h: 'some & any', p: 'Use **some** in positive sentences, **any** in negatives and questions.',
          es: '**some** (algunos) en afirmativo; **any** en negativo y preguntas.', ex: ['There are some books.', "There aren't any curtains.", 'Are there any candles?'] },
      ],
      vocab: [['mirror', 'espejo', 'There is a vintage mirror.'], ['shelf', 'repisa', 'There are books on the shelf.'], ['rug', 'tapete', 'There is a soft rug.'],
        ['curtains', 'cortinas', 'The curtains are white.'], ['plant', 'planta', 'Are there any plants?'], ['lamp', 'lámpara', 'There is a brass lamp.'],
        ['armchair', 'sillón', 'There is an old armchair.'], ['wardrobe', 'armario', 'The wardrobe is antique.']],
      ex: [
        ['mc', '___ a beautiful lamp in the living room.', 'There is|There are|It has', 'One lamp → there is.'],
        ['mc', '___ three candles on the table.', 'There are|There is|Is there', 'Many → there are.'],
        ['mc', 'Are there ___ plants in the kitchen?', 'any|some|a', 'Questions → any.'],
        ['fill', 'There ___ any curtains in my bedroom. (negative)', "aren't|are not", 'Plural negative.'],
        ['fill', '___ there a mirror in the bathroom?', 'Is', 'Singular question.'],
        ['fix', 'There is two armchairs.', 'There are two armchairs.', 'Plural → there are.'],
        ['fix', 'In my room have a rug.', 'In my room there is a rug.|There is a rug in my room.', 'Spanish “hay” = there is, not have.'],
        ['order', 'There are some old books on the shelf', 'Hay algunos libros viejos en la repisa'],
        ['listen', 'Is there a vintage mirror in the bedroom?'],
        ['speak', 'There are some flowers and a candle on my desk.'],
      ],
      links: ['m1l2', 'm1l4'],
    },
    {
      id: 'm3l2', title: 'On, under, next to', topic: 'prepositions of place',
      intro: 'Where is everything? Organize the room with words.',
      theory: [
        { h: 'Small words, exact places', p: '**in** (dentro), **on** (encima), **under** (debajo), **next to** (al lado), **between** (entre), **behind** (detrás), **in front of** (delante).',
          es: 'Las preposiciones de lugar van **después de to be**: The cat is **under** the bed.',
          table: [['in', 'in the drawer'], ['on', 'on the table'], ['under', 'under the bed'], ['next to', 'next to the window'], ['between', 'between the lamps'], ['behind', 'behind the door'], ['in front of', 'in front of the mirror']] },
        { h: 'Questions with where', p: '**Where is…? Where are…?** Answer with a **preposition**.',
          es: '**Where is** my pen? — It’s **on** the desk.', anim: ['The pen is on the desk', 'Where is the pen?'] },
      ],
      vocab: [['drawer', 'cajón', 'The letters are in the drawer.'], ['desk', 'escritorio', 'My desk is next to the window.'], ['window', 'ventana', 'The plant is in front of the window.'],
        ['wall', 'pared', 'There is a painting on the wall.'], ['floor', 'piso', 'The rug is on the floor.'], ['corner', 'esquina', 'The armchair is in the corner.'],
        ['bed', 'cama', 'The cat is under the bed.'], ['door', 'puerta', 'The coat is behind the door.']],
      ex: [
        ['mc', 'The painting is ___ the wall.', 'on|in|under', 'On a surface → on.'],
        ['mc', 'The letters are ___ the drawer.', 'in|on|between', 'Inside → in.'],
        ['mc', 'The sofa is ___ the two lamps.', 'between|next|behind', 'Between two things.'],
        ['fill', 'My desk is next ___ the window.', 'to', 'Next to.'],
        ['fill', 'The coat is ___ the door. (detrás)', 'behind', 'Behind = detrás.'],
        ['fix', 'The cat is in front the mirror.', 'The cat is in front of the mirror.', 'In front OF.'],
        ['fix', 'Where are my notebook?', 'Where is my notebook?', 'One notebook → is.'],
        ['order', 'There is a painting on the wall above the bed', 'Hay un cuadro en la pared encima de la cama'],
        ['listen', 'The armchair is in the corner, next to the lamp.'],
        ['speak', 'My plants are in front of the window.'],
      ],
      links: ['m3l1', 'm1l2'],
    },
    {
      id: 'm3l3', title: 'A small, cozy, white room', topic: 'have/has & adjectives',
      intro: 'Possessions and descriptions — with style.',
      theory: [
        { h: 'have / has', p: '**Have** = tener. He / she / it → **has** (like module 2!). Negatives: **don’t have / doesn’t have**.',
          es: '**have/has** para posesión: She **has** an antique wardrobe. Negativo con **do/does**.',
          ex: ['I have a small balcony.', 'She has three plants.', "He doesn't have a car."] },
        { h: 'Adjectives before nouns', p: '**Opinion → size → age → color → material** → noun.',
          es: 'Orden: **opinión, tamaño, edad, color, material**. A **lovely small old white wooden** chair.',
          anim: ['a chair', 'a lovely small white wooden chair'] },
        { h: 'very, really, quite', p: 'Make adjectives stronger or softer: **quite** (bastante) < **very** (muy) < **really** (realmente).',
          es: '**very** cozy, **really** beautiful, **quite** small.', ex: ['The room is very cozy.', "It's quite small but really bright."] },
      ],
      vocab: [['cozy', 'acogedor', 'My bedroom is very cozy.'], ['bright', 'luminoso', 'The kitchen is bright.'], ['wooden', 'de madera', 'a wooden table'],
        ['brass', 'de latón', 'a brass lamp'], ['velvet', 'terciopelo', 'a velvet armchair'], ['tidy', 'ordenado', 'Her room is always tidy.'],
        ['messy', 'desordenado', "My desk isn't messy."], ['balcony', 'balcón', 'We have a small balcony.']],
      ex: [
        ['mc', 'Meri ___ an antique desk.', 'has|have|is', 'She → has.'],
        ['mc', 'Correct order:', 'a beautiful old wooden table|a wooden old beautiful table|a table beautiful old wooden', 'Opinion → age → material.'],
        ['mc', 'Correct order:', 'a small white vase|a white small vase|a vase small white', 'Size → color.'],
        ['fill', "We ___ have a garden, but we have a balcony. (negative)", "don't|do not", 'We → don’t have.'],
        ['fill', "Does she ___ a velvet sofa?", 'have', 'After does → have.'],
        ['fix', 'She have a tidy room.', 'She has a tidy room.', 'She → has.'],
        ['fix', 'I have a lamp brass.', 'I have a brass lamp.', 'Adjective before the noun.'],
        ['order', 'Her bedroom is really cozy and bright', 'Su habitación es muy acogedora y luminosa'],
        ['listen', 'I have a small velvet armchair next to the window.'],
        ['speak', 'My room is small but very cozy.'],
      ],
      links: ['m2l1', 'm1l4', 'm3l1'],
    },
    {
      id: 'm3l4', title: 'I can paint, I can’t sew', topic: 'can / can’t',
      intro: 'Abilities and possibilities — talk about your talents.',
      theory: [
        { h: 'can + base verb', p: 'Can is the **same for all persons**. **No -s, no do**! **Can + verb** (no to).',
          es: '**can** no cambia: I can, she **can** (no “she cans”). Nunca “**can to**”.', anim: ['She paints', 'She can paint'] },
        { h: "can't and Can you…?", p: 'Negative: **can’t**. Question: **Can + subject + verb**?',
          es: 'Negativo **can’t**. Pregunta: **Can you swim?** — Yes, **I can**.', ex: ["I can't sew.", 'Can you speak French? — No, I can’t.'] },
        { h: 'Possibility & permission', p: 'Can also means it is **possible** or **allowed**.',
          es: 'También es **posibilidad/permiso**: You can sit here. **Can I** open the window?', ex: ['You can see the park from here.', 'Can I use your pen?'] },
      ],
      vocab: [['paint', 'pintar', 'She can paint flowers.'], ['sew', 'coser', "I can't sew."], ['sing', 'cantar', 'Can you sing?'],
        ['draw', 'dibujar', 'He can draw very well.'], ['decorate', 'decorar', 'She can decorate any room.'], ['fix', 'arreglar', 'Can you fix this lamp?'],
        ['dance', 'bailar', 'We can dance salsa.'], ['speak', 'hablar (idioma)', 'I can speak a little English.']],
      ex: [
        ['mc', 'Laura ___ speak three languages.', 'can|cans|can to', 'Can never changes.'],
        ['mc', '___ you help me with this shelf?', 'Can|Do|Are', 'Ability/request → can.'],
        ['mc', 'Can you draw? — Yes, I ___.', 'can|do|draw', 'Short answer with can.'],
        ['fill', "I ___ sew, but I can paint. (negative)", "can't|cannot", 'Negative → can’t.'],
        ['fix', 'She can to dance tango.', 'She can dance tango.', 'No “to” after can.'],
        ['fix', 'He cans fix lamps.', 'He can fix lamps.', 'No -s with can.'],
        ['fix', 'Do you can sing?', 'Can you sing?', 'Can makes its own questions.'],
        ['order', 'You can see the park from my window', 'Puedes ver el parque desde mi ventana'],
        ['listen', "I can't sing, but I can write poems."],
        ['speak', 'I can speak a little English.'],
      ],
      links: ['m2l2', 'm3l3'],
    },
    {
      id: 'm3l5', title: 'Letters from New York · Ch.3', topic: 'story: home', story: true,
      intro: 'Chapter 3: the antique desk — and what is inside it.',
      read: { title: 'The secret drawer', text:
`This Saturday there is something new in the antique shop: a small wooden desk with brass handles. It's old and a little messy, but it's beautiful. The owner looks at me. "It's for a writer," he says.

Now the desk is in my room, next to the window. There are some candles on it, my white notebook and a vase with three flowers.

Tonight I can't sleep. I open the drawers. They are empty… but there is a very small drawer behind the others. Inside it there is an envelope. It's yellow and very old.

The name on the envelope is "Rosa". The address is in New York. And the date is 1968.` },
      theory: [
        { h: 'A room in words', p: 'Notice **there is / there are**, the **prepositions of place**, the **adjectives** and **can’t**. That is module 3 in one scene.',
          es: 'Mira cómo se describe la habitación con todo lo del **módulo 3**.' },
      ],
      vocab: [['handle', 'manija', 'brass handles'], ['empty', 'vacío', 'The drawers are empty.'], ['envelope', 'sobre', 'There is an envelope.'],
        ['address', 'dirección', 'The address is in New York.'], ['inside', 'adentro', 'Inside it there is a letter.'], ['tonight', 'esta noche', "Tonight I can't sleep."]],
      ex: [
        ['read', 'Where is the desk now?', 'In Meri’s room, next to the window|In the shop|In New York', '"Now the desk is in my room, next to the window."'],
        ['read', 'What is inside the very small drawer?', 'An old envelope|Candles|A notebook', '"Inside it there is an envelope."'],
        ['read', 'What is the name on the envelope?', 'Rosa|Laura|Meri', '"The name on the envelope is Rosa."'],
        ['read', 'What year is on the envelope?', '1968|1986|1998', '"The date is 1968."'],
        ['mc', 'There ___ some candles on the desk.', 'are|is|has', 'Plural → are.'],
        ['fix', 'The desk has handles of brass old.', 'The desk has old brass handles.', 'Age → material → noun.'],
        ['listen', 'There is a very small drawer behind the others.'],
        ['speak', "Tonight I can't sleep."],
      ],
      links: ['m3l1', 'm3l2', 'm3l3', 'm3l4', 'm2l5'],
    },
  ],
  exam: [
    ['mc', '___ any towels in the bathroom?', 'Are there|Is there|There are', 'Plural question.'],
    ['mc', 'The keys are ___ the bag. (dentro)', 'in|on|at', 'Inside → in.'],
    ['mc', 'My parents ___ a big house.', 'have|has|haves', 'They → have.'],
    ['mc', 'Correct order:', 'a lovely old velvet sofa|a velvet lovely old sofa|an old lovely velvet sofa', 'Opinion → age → material.'],
    ['mc', 'Can she cook? — No, she ___.', "can't|doesn't|isn't", 'Short answer with can.'],
    ['fill', 'There ___ a cat behind the curtains.', 'is', 'One cat → is.'],
    ['fill', 'The lamp is ___ the sofa and the armchair.', 'between', 'Between two things.'],
    ['fix', 'There are a mirror on the wall.', 'There is a mirror on the wall.', 'Singular → there is.'],
    ['fix', "She doesn't has a balcony.", "She doesn't have a balcony.", 'After doesn’t → have.'],
    ['fix', 'I can to speak English.', 'I can speak English.', 'No “to”.'],
    ['order', 'Is there a bookstore next to your house', '¿Hay una librería al lado de tu casa?'],
    ['listen', 'There are some beautiful brass lamps in the shop.'],
  ],
}
