export default {
  id: 'm4', level: 'A2', title: 'Right Now in Paris', subtitle: 'Present continuous · stative verbs · imperatives',
  goal: 'Describe what is happening now, and write captions and calls to action.',
  lessons: [
    {
      id: 'm4l1', title: "I'm writing, she's reading", topic: 'present continuous: form',
      intro: 'Like Emily in Paris: what is happening right now?',
      theory: [
        { h: 'be + verb-ing', p: 'Use am / is / are (module 1!) + verb-ing for actions happening now.',
          es: 'Presente continuo = estar + -ando/-iendo. I am reading = estoy leyendo.', anim: ['I read', "I'm reading"] },
        { h: 'Spelling of -ing', p: 'Most verbs: +ing. Final -e: drop it (write → writing). Short verb CVC: double (sit → sitting).',
          es: 'write → writing, dance → dancing, sit → sitting, shop → shopping.',
          table: [['read', 'reading'], ['write', 'writing'], ['sit', 'sitting'], ['shop', 'shopping'], ['lie', 'lying']] },
        { h: 'Negatives and questions', p: 'Same as to be: She isn’t working. Are you listening?',
          es: 'Negativo y pregunta igual que to be.', anim: ['You are listening', 'Are you listening?'] },
      ],
      vocab: [['right now', 'ahora mismo', "I'm studying right now."], ['at the moment', 'en este momento', "She's working at the moment."], ['wear', 'llevar puesto', "She's wearing a red beret."],
        ['take a photo', 'tomar una foto', "He's taking a photo."], ['post', 'publicar', "I'm posting a story."], ['wait', 'esperar', "We're waiting for the train."],
        ['rain', 'llover', "It's raining in Paris."], ['walk', 'caminar', "They're walking by the river."]],
      ex: [
        ['mc', 'Look! It ___.', "'s raining|rains|raining", 'Now → be + -ing.'],
        ['mc', 'Spelling: write →', 'writing|writeing|writting', 'Drop the -e.'],
        ['mc', 'Spelling: shop →', 'shopping|shoping|shopeing', 'CVC → double consonant.'],
        ['fill', "She ___ wearing a beautiful dress tonight.", "is|'s", 'She → is.'],
        ['fill', '___ you listening to me?', 'Are', 'You → are.'],
        ['fix', 'I studying English now.', "I'm studying English now.|I am studying English now.", 'Don’t forget am.'],
        ['fix', "They isn't working today.", "They aren't working today.|They're not working today.", 'They → aren’t.'],
        ['order', "She's taking photos of the Eiffel Tower", 'Ella está tomando fotos de la Torre Eiffel'],
        ['listen', "We're waiting for the train to Paris."],
        ['speak', "Right now I'm learning English."],
      ],
      links: ['m1l1', 'm1l2'],
    },
    {
      id: 'm4l2', title: 'Every day vs. right now', topic: 'present simple vs continuous',
      intro: 'Your routine vs. this moment — two tenses, two ideas.',
      theory: [
        { h: 'Two different ideas', p: 'Present simple = habits (module 2). Present continuous = now or temporary.',
          es: 'Simple: rutina. Continuo: ahora / temporal.', ex: ['I usually drink coffee, but today I’m drinking tea.', 'She works in Bogotá, but this month she’s working in Paris.'] },
        { h: 'Signal words', p: 'Simple: always, usually, every day, on Mondays. Continuous: now, right now, at the moment, today, this week.',
          es: 'Palabras clave que te dicen qué tiempo usar.',
          table: [['simple', 'always · every day · on Mondays · often'], ['continuous', 'now · at the moment · today · this week']] },
        { h: 'Watch the change', p: 'Same verb, different time:',
          es: 'Mira cómo cambia.', anim: ['Emily works in Chicago', 'Emily is working in Paris'] },
      ],
      vocab: [['this week', 'esta semana', "I'm working from home this week."], ['usually', 'normalmente', 'I usually walk.'], ['temporary', 'temporal', "It's a temporary job."],
        ['abroad', 'en el extranjero', "She's living abroad."], ['project', 'proyecto', "We're working on a new project."], ['client', 'cliente', 'The client usually calls on Mondays.'],
        ['launch', 'lanzamiento', "We're preparing a launch."], ['team', 'equipo', 'My team meets every Monday.']],
      ex: [
        ['mc', 'I usually ___ the bus, but today I’m walking.', 'take|am taking|takes', 'Usually → simple.'],
        ['mc', 'Shh! The baby ___.', 'is sleeping|sleeps|sleep', 'Right now → continuous.'],
        ['mc', 'This week we ___ on a new campaign.', 'are working|work|works', 'This week (temporary) → continuous.'],
        ['mc', 'My team ___ every Monday.', 'meets|is meeting|meet', 'Every Monday → simple.'],
        ['fill', 'She ___ (live) in Paris at the moment.', "is living|'s living", 'At the moment → continuous.'],
        ['fill', 'He ___ (call) his mother every Sunday.', 'calls', 'Every Sunday → simple.'],
        ['fix', 'I am drinking coffee every morning.', 'I drink coffee every morning.', 'Habit → simple.'],
        ['order', "I usually work in Bogotá but now I'm working in Paris", 'Normalmente trabajo en Bogotá pero ahora estoy trabajando en París'],
        ['listen', "We're preparing a launch for a new perfume."],
        ['speak', "I usually drink coffee, but today I'm drinking tea."],
      ],
      links: ['m4l1', 'm2l1', 'm2l3'],
    },
    {
      id: 'm4l3', title: 'I love it (not “I’m loving”)', topic: 'stative verbs',
      intro: 'Some verbs describe states, not actions. They prefer the simple form.',
      theory: [
        { h: 'States, not actions', p: 'Verbs of feelings, thoughts and possession are usually NOT continuous: like, love, hate, want, need, know, understand, believe, have (possession), remember.',
          es: 'Estos verbos casi nunca van con -ing: I know (no “I’m knowing”).',
          table: [['feelings', 'like · love · hate · prefer · want · need'], ['mind', 'know · understand · believe · remember · think (= opinion)'], ['having', 'have (possess) · own · belong']] },
        { h: 'Correct the instinct', p: 'Even when you mean “right now”, use the simple form.',
          es: 'Aunque sea ahora, usa simple.', anim: ["I'm not understanding", "I don't understand"] },
        { h: 'Marketing exception', p: 'You see “I’m lovin’ it” in ads. Ads break rules to sound fresh — a great detail for a communicator!',
          es: 'La publicidad rompe reglas a propósito. En exámenes, usa la forma correcta.', ex: ["I love this song.", 'She wants a new notebook.'] },
      ],
      vocab: [['understand', 'entender', "I don't understand this word."], ['believe', 'creer', 'I believe in you.'], ['prefer', 'preferir', 'I prefer tea.'],
        ['remember', 'recordar', 'Do you remember her name?'], ['belong', 'pertenecer', 'This desk belongs to me.'], ['hate', 'odiar', 'I hate alarms.'],
        ['smell', 'oler (a)', 'This perfume smells amazing.'], ['seem', 'parecer', 'She seems happy.']],
      ex: [
        ['mc', 'I ___ what you mean.', 'understand|am understanding|understanding', 'Stative → simple.'],
        ['mc', 'She ___ a new laptop for work.', 'needs|is needing|need', 'Need is stative.'],
        ['mc', 'This perfume ___ like roses.', 'smells|is smelling|smell', 'State → simple.'],
        ['fill', 'I ___ (not / know) the answer.', "don't know|do not know", 'Know is stative.'],
        ['fill', 'Do you ___ (remember) the name of the shop?', 'remember', 'After do → base verb.'],
        ['fix', "I'm wanting a coffee.", 'I want a coffee.', 'Want is stative.'],
        ['fix', 'This notebook is belonging to Meri.', 'This notebook belongs to Meri.', 'Belong is stative.'],
        ['order', 'I prefer quiet songs when I study', 'Prefiero canciones tranquilas cuando estudio'],
        ['listen', "I don't understand, but I believe you."],
        ['speak', 'I love this song. It sounds like a poem.'],
      ],
      links: ['m4l2', 'm2l2'],
    },
    {
      id: 'm4l4', title: 'Shop now. Don’t miss it.', topic: 'imperatives & let’s',
      intro: 'The language of instructions, captions and calls to action.',
      theory: [
        { h: 'Imperative = base verb', p: 'Give instructions or invitations with the base verb. No subject.',
          es: 'Imperativo: verbo base sin sujeto. Open the door. Try it now.', ex: ['Discover the new collection.', 'Try it today.', 'Sit down, please.'] },
        { h: 'Negative: Don’t + verb', p: 'Don’t + base verb, for everyone.',
          es: 'Negativo: Don’t + verbo.', anim: ['Miss the launch', "Don't miss the launch"] },
        { h: 'Let’s = invitation', p: 'Let’s + base verb = suggestion for us.',
          es: 'Let’s = vamos a… / hagamos…', ex: ["Let's start!", "Let's not be late."] },
      ],
      vocab: [['discover', 'descubrir', 'Discover your glow.'], ['try', 'probar', 'Try it today.'], ['miss', 'perderse', "Don't miss it!"],
        ['shop', 'comprar', 'Shop the look.'], ['share', 'compartir', 'Share with a friend.'], ['follow', 'seguir', 'Follow us for more.'],
        ['caption', 'pie de foto', 'Write a short caption.'], ['call to action', 'llamado a la acción', 'Every post needs a call to action.']],
      ex: [
        ['mc', 'Choose the best call to action:', 'Discover your glow.|You discovering your glow.|To discover your glow.', 'Imperative = base verb.'],
        ['mc', '___ forget your umbrella!', "Don't|Not|No", 'Negative imperative → don’t.'],
        ['mc', '___ go to the Louvre on Sunday!', "Let's|Let|Lets us", 'Suggestion → let’s.'],
        ['fill', "___ the link in bio. (click)", 'Click', 'Imperative → base verb.'],
        ['fix', 'Not touch the paintings.', "Don't touch the paintings.|Do not touch the paintings.", 'Negative → don’t.'],
        ['fix', 'Tries our new serum!', 'Try our new serum!', 'Base verb, no -s.'],
        ['order', 'Share this post with a friend', 'Comparte esta publicación con una amiga'],
        ['listen', "Don't miss the launch. Follow us for more."],
        ['speak', "Let's practice English every day."],
      ],
      links: ['m2l2', 'm1l5'],
    },
    {
      id: 'm4l5', title: 'Letters from New York · Ch.4', topic: 'story: right now', story: true,
      intro: 'Chapter 4: Meri opens Rosa’s letter — and her inbox.',
      read: { title: 'Two letters', text:
`It's Sunday night. I'm sitting at the antique desk and I'm holding Rosa's letter. My hands are shaking.

The letter says: "New York, May 1968. Dear sister, I'm writing from the office. Right now everyone is working on the new perfume. I love this city. Don't worry about me. — Rosa."

I don't know who Rosa is. But I want to know.

Suddenly my phone rings. It's an email from Maison Lumière, a beauty company in New York: "We are looking for communication strategists for our Latin American team. Apply now. Don't miss this opportunity."

I'm reading the email again and again. Am I dreaming?` },
      theory: [
        { h: 'Two times in one scene', p: 'Find present continuous (now), stative verbs (love, know, want) and imperatives (Apply now, Don’t worry).',
          es: 'Todo el módulo 4 en una escena.' },
      ],
      vocab: [['hold', 'sostener', "I'm holding the letter."], ['shake', 'temblar', 'My hands are shaking.'], ['Dear', 'Querida (en cartas)', 'Dear sister,'],
        ['suddenly', 'de repente', 'Suddenly my phone rings.'], ['apply', 'postularse', 'Apply now.'], ['look for', 'buscar', 'We are looking for strategists.']],
      ex: [
        ['read', 'Who is Rosa writing to?', 'Her sister|Meri|Her boss', '"Dear sister"'],
        ['read', 'What is everyone in Rosa’s office working on?', 'A new perfume|A magazine|A painting', '"…working on the new perfume."'],
        ['read', 'What is Maison Lumière?', 'A beauty company in New York|A shop in Colombia|A perfume from 1968', '"…a beauty company in New York."'],
        ['read', 'Does Meri know who Rosa is?', 'No, but she wants to know|Yes, she is her sister|Yes, she is her boss', '"I don\'t know who Rosa is. But I want to know."'],
        ['fix', "I'm knowing this city.", 'I know this city.', 'Know is stative.'],
        ['mc', 'The email: "___ this opportunity."', "Don't miss|Not miss|Doesn't miss", 'Negative imperative.'],
        ['listen', "I'm reading the email again and again."],
        ['speak', 'Am I dreaming?'],
      ],
      links: ['m4l1', 'm4l3', 'm4l4', 'm3l5'],
    },
  ],
  exam: [
    ['mc', 'Listen! Someone ___ the piano.', 'is playing|plays|play', 'Now → continuous.'],
    ['mc', 'She ___ to the gym three times a week.', 'goes|is going|go', 'Habit → simple.'],
    ['mc', 'I ___ this song!', 'love|am loving|loving', 'Stative → simple.'],
    ['mc', '___ late for the meeting, please.', "Don't be|Not be|Don't being", 'Negative imperative.'],
    ['mc', 'Spelling: swim →', 'swimming|swiming|swimmming', 'CVC → double.'],
    ['fill', 'What ___ you doing right now?', 'are', 'You → are.'],
    ['fill', 'He ___ (not / understand) the question.', "doesn't understand|does not understand", 'Stative + negative simple.'],
    ['fix', 'Look! It snows.', "Look! It's snowing.|Look! It is snowing.", 'Now → continuous.'],
    ['fix', 'She is needing help.', 'She needs help.', 'Need is stative.'],
    ['fix', "Let's to go!", "Let's go!", 'Let’s + base verb.'],
    ['order', "This week I'm working on a beauty campaign", 'Esta semana estoy trabajando en una campaña de belleza'],
    ['listen', "Try our new collection. Don't miss it!"],
  ],
}
