export default {
  id: 'm5', level: 'A2', title: 'Once Upon a Time', subtitle: 'Past simple · was/were · irregular verbs',
  goal: 'Tell stories and memories — like Isabel Allende.',
  lessons: [
    {
      id: 'm5l1', title: 'It was a beautiful day', topic: 'was / were',
      intro: 'The past of to be: only two forms.',
      theory: [
        { h: 'am / is → was · are → were', p: 'I / he / she / it → **was**. You / we / they → **were**.',
          es: 'Pasado de to be: **was** (yo, él, ella) y **were** (tú, nosotros, ellos).', anim: ['She is in Paris', 'She was in Paris'],
          table: [['I / he / she / it', 'was', "wasn't"], ['you / we / they', 'were', "weren't"]] },
        { h: 'Questions and answers', p: 'Like module 1: **move the verb to the front**.',
          es: '**Was she happy?** — Yes, she **was**. / No, she **wasn’t**.', anim: ['It was expensive', 'Was it expensive?'] },
        { h: 'Time words', p: '**yesterday**, **last night**, **last week**, **in 1968**, **two years ago**.',
          es: '**ago** = hace (two years ago = hace dos años). Va **después del tiempo**.', ex: ['I was at home last night.', 'She was born in 1968.', 'We were in Cartagena two years ago.'] },
      ],
      vocab: [['yesterday', 'ayer', 'I was tired yesterday.'], ['last night', 'anoche', 'Where were you last night?'], ['ago', 'hace (tiempo)', 'It was ten years ago.'],
        ['born', 'nacida', 'She was born in Cali.'], ['childhood', 'infancia', 'My childhood was happy.'], ['grandmother', 'abuela', 'My grandmother was a teacher.'],
        ['young', 'joven', 'They were young.'], ['century', 'siglo', 'The desk is from the last century.']],
      ex: [
        ['mc', 'Rosa ___ in New York in 1968.', 'was|were|is', 'She → was.'],
        ['mc', 'We ___ at the museum yesterday.', 'were|was|are', 'We → were.'],
        ['mc', '___ you at home last night?', 'Were|Was|Did', 'You → were.'],
        ['fill', 'The film ___ very good. I didn’t like it. (negative)', "wasn't|was not", 'It → wasn’t.'],
        ['fill', 'I was in Paris three years ___.', 'ago', 'Hace tres años = three years ago.'],
        ['fix', 'They was very happy.', 'They were very happy.', 'They → were.'],
        ['fix', 'I was born on 1995.', 'I was born in 1995.', 'Years → in.'],
        ['order', 'My grandmother was a very elegant woman', 'Mi abuela era una mujer muy elegante'],
        ['listen', 'Where were you two years ago?'],
        ['speak', 'My childhood was simple and happy.'],
      ],
      links: ['m1l1', 'm1l2', 'm2l4'],
    },
    {
      id: 'm5l2', title: 'I walked, she danced', topic: 'past simple: regular verbs',
      intro: 'Add -ed and travel in time.',
      theory: [
        { h: 'verb + -ed', p: 'Regular verbs add **-ed** for ALL persons. **No -s problems** in the past!',
          es: 'Regular: **+ed para todos**. She **worked**, they **worked**.', anim: ['She works in Paris', 'She worked in Paris'] },
        { h: 'Spelling', p: 'Final -e: **+d** (love → **loved**). Consonant + y: **-ied** (study → **studied**). Short CVC: **double** (stop → **stopped**).',
          es: 'love → **loved**, study → **studied**, stop → **stopped**, play → **played**.',
          table: [['walk', 'walked'], ['love', 'loved'], ['study', 'studied'], ['stop', 'stopped'], ['play', 'played']] },
        { h: 'Three sounds of -ed', p: '**/t/** after voiceless sounds (walked), **/d/** after voiced (played), **/ɪd/** after t or d (wanted, decided).',
          es: 'La -ed suena **/t/**, **/d/** o **/id/**. Solo suena “id” después de **t o d**: wanted, needed.', ex: ['walked /t/', 'loved /d/', 'wanted /ɪd/'] },
      ],
      vocab: [['travel', 'viajar', 'She traveled to Italy.'], ['decide', 'decidir', 'I decided to study English.'], ['visit', 'visitar', 'We visited the Met.'],
        ['arrive', 'llegar', 'They arrived late.'], ['move', 'mudarse', 'She moved to New York.'], ['call', 'llamar', 'I called my mother.'],
        ['open', 'abrir', 'She opened the letter.'], ['watch', 'ver', 'We watched a romantic movie.']],
      ex: [
        ['mc', 'Last year Rosa ___ to New York.', 'moved|move|moves', 'Past → -ed.'],
        ['mc', 'Past of "study":', 'studied|studyed|studed', 'Consonant + y → -ied.'],
        ['mc', 'Past of "stop":', 'stopped|stoped|stopt', 'CVC → double.'],
        ['mc', 'Which -ed sounds /ɪd/?', 'wanted|played|walked', 'After t or d → /ɪd/.'],
        ['fill', 'I ___ (visit) the Met last summer.', 'visited', 'Regular → -ed.'],
        ['fill', 'She ___ (open) the envelope slowly.', 'opened', 'Regular → -ed.'],
        ['fix', 'Yesterday she call me.', 'Yesterday she called me.', 'Yesterday → past.'],
        ['order', 'We watched a romantic movie last night', 'Vimos una película romántica anoche'],
        ['listen', 'She decided to move to New York.'],
        ['speak', 'I studied English yesterday.'],
      ],
      links: ['m5l1', 'm2l1'],
    },
    {
      id: 'm5l3', title: 'I went, I saw, I wrote', topic: 'past simple: irregular verbs',
      intro: 'The rebels. Learn them in families and they become easy.',
      theory: [
        { h: 'Irregular = memorize', p: 'The most common verbs are **irregular**. They have their own past form — still the same for all persons.',
          es: 'Los verbos más comunes son **irregulares**. Hay que aprenderlos, pero **sin -s ni cambios por persona**.',
          table: [['go', 'went'], ['have', 'had'], ['see', 'saw'], ['write', 'wrote'], ['buy', 'bought'], ['find', 'found'], ['make', 'made'], ['take', 'took'], ['give', 'gave'], ['feel', 'felt']] },
        { h: 'Learn them in families', p: 'Some sound alike: buy → **bought**, bring → **brought**, think → **thought**. Write → **wrote**, drive → **drove**.',
          es: 'Agrúpalos por sonido: **bought / brought / thought**.', anim: ['I buy flowers', 'I bought flowers'] },
      ],
      vocab: [['went', 'fue (go)', 'She went to Paris.'], ['saw', 'vio (see)', 'I saw a beautiful painting.'], ['wrote', 'escribió (write)', 'Rosa wrote a letter.'],
        ['bought', 'compró (buy)', 'I bought an antique desk.'], ['found', 'encontró (find)', 'Meri found an envelope.'], ['made', 'hizo (make)', 'They made a perfume.'],
        ['felt', 'sintió (feel)', 'I felt nervous.'], ['took', 'tomó (take)', 'She took the bus.']],
      ex: [
        ['mc', 'Past of "go":', 'went|goed|gone', 'Irregular.'],
        ['mc', 'Rosa ___ letters to her sister every month.', 'wrote|writed|writes', 'Write → wrote.'],
        ['mc', 'Past of "think":', 'thought|thinked|taught', 'Family: bought, brought, thought.'],
        ['fill', 'I ___ (buy) a vintage mirror yesterday.', 'bought', 'Buy → bought.'],
        ['fill', 'She ___ (find) an old photo in the book.', 'found', 'Find → found.'],
        ['fill', 'We ___ (see) the Mona Lisa in 2019.', 'saw', 'See → saw.'],
        ['fix', 'I goed to the antique shop.', 'I went to the antique shop.', 'Go → went.'],
        ['fix', 'She feeled happy.', 'She felt happy.', 'Feel → felt.'],
        ['order', 'Meri found a letter in the old desk', 'Meri encontró una carta en el escritorio viejo'],
        ['listen', 'They made a perfume in 1968.'],
        ['speak', 'I bought flowers and wrote a poem.'],
      ],
      links: ['m5l2', 'm3l5'],
    },
    {
      id: 'm5l4', title: "Did you…? I didn't…", topic: 'past simple: did / didn’t',
      intro: 'Questions and negatives in the past — the helper is did.',
      theory: [
        { h: 'did = the past of do', p: 'Remember do / does (module 2)? In the past, it’s **did** for everyone. The main verb goes **back to the base form**!',
          es: '**did / didn’t + verbo BASE**. She **didn’t go** (no “didn’t went”).', anim: ['She went to the party', "She didn't go to the party"] },
        { h: 'Questions with did', p: '**Did + subject + base verb**?',
          es: '**Did you see it?** — Yes, I **did**.', anim: ['You saw the movie', 'Did you see the movie?'] },
        { h: 'Not with was / were', p: 'Like the present: **to be** makes questions alone. **Were you tired?** (not “Did you were…”).',
          es: 'Con **was/were** no se usa **did**.', ex: ['Were you tired?', 'Did you feel tired?'] },
      ],
      vocab: [['did', 'auxiliar pasado', 'Did you like it?'], ['enjoy', 'disfrutar', 'Did you enjoy the concert?'], ['forget', 'olvidar (forgot)', "I didn't forget your birthday."],
        ['lose', 'perder (lost)', 'She lost her keys.'], ['meet', 'conocer (met)', 'Where did you meet?'], ['leave', 'salir/dejar (left)', 'When did they leave?'],
        ['say', 'decir (said)', 'What did she say?'], ['get', 'recibir/conseguir (got)', 'Did you get my message?']],
      ex: [
        ['mc', '___ you enjoy the concert?', 'Did|Were|Do', 'Past question → did.'],
        ['mc', "She didn't ___ the letter.", 'read|reads|readed', 'After didn’t → base verb.'],
        ['mc', 'Did he call you? — No, he ___.', "didn't|wasn't|don't", 'Short answer with did.'],
        ['fill', 'Where ___ you meet your best friend?', 'did', 'Past question → did.'],
        ['fill', 'I ___ go out last night. I stayed home. (negative)', "didn't|did not", 'Past negative → didn’t.'],
        ['fix', 'Did you went to the museum?', 'Did you go to the museum?', 'After did → base verb.'],
        ['fix', "She didn't felt well.", "She didn't feel well.", 'After didn’t → base verb.'],
        ['fix', 'Did you were at home?', 'Were you at home?', 'To be doesn’t use did.'],
        ['order', 'What did Rosa write in the letter', '¿Qué escribió Rosa en la carta?'],
        ['listen', "I didn't forget. I just lost my phone."],
        ['speak', 'Did you get my message?'],
      ],
      links: ['m5l3', 'm2l2', 'm5l1'],
    },
    {
      id: 'm5l5', title: 'Letters from New York · Ch.5', topic: 'story: the past', story: true,
      intro: 'Chapter 5: Meri visits her grandmother — and the past answers back.',
      read: { title: 'Abuela Inés remembers', text:
`On Sunday I visited my grandmother, Inés. I showed her Rosa's letter. She was quiet for a long time. Then she touched the paper and smiled.

"Rosa was my aunt," she said. "She left Colombia in 1966. She was only twenty-two. She found a job in New York, at a perfume company. She wrote to my mother every month."

"Did she come back?" I asked.

"No, she didn't. In 1969 the letters stopped. Nobody knew why." My grandmother looked at the window. "But she always said one thing: write your own story."

That night I didn't sleep. I opened my laptop and I wrote my application for Maison Lumière.` },
      theory: [
        { h: 'A family story', p: 'Find **was/were**, **regular and irregular** past verbs, and **did/didn’t** questions. That’s all of module 5.',
          es: 'Busca el pasado **regular**, **irregular** y **did/didn’t**.' },
      ],
      vocab: [['aunt', 'tía', 'Rosa was my aunt.'], ['show', 'mostrar (showed)', 'I showed her the letter.'], ['touch', 'tocar', 'She touched the paper.'],
        ['come back', 'volver', 'Did she come back?'], ['nobody', 'nadie', 'Nobody knew why.'], ['application', 'postulación', 'I wrote my application.']],
      ex: [
        ['read', 'Who was Rosa?', 'Inés’s aunt|Meri’s mother|Inés’s sister', '"Rosa was my aunt."'],
        ['read', 'When did Rosa leave Colombia?', 'In 1966|In 1968|In 1969', '"She left Colombia in 1966."'],
        ['read', 'What happened in 1969?', 'The letters stopped|Rosa came back|Rosa got married', '"In 1969 the letters stopped."'],
        ['read', 'What did Meri do that night?', 'She wrote her application|She slept|She called Rosa', '"I wrote my application."'],
        ['fix', 'Did Rosa came back?', 'Did Rosa come back?', 'After did → base verb.'],
        ['mc', 'Rosa ___ only twenty-two.', 'was|were|did', 'She → was.'],
        ['mc', 'She ___ to my mother every month.', 'wrote|writed|write', 'Write → wrote.'],
        ['listen', 'Write your own story.'],
        ['speak', 'Rosa left Colombia in 1966.'],
      ],
      links: ['m5l1', 'm5l2', 'm5l3', 'm5l4', 'm4l5'],
    },
  ],
  exam: [
    ['mc', 'The concert ___ amazing!', 'was|were|did', 'It → was.'],
    ['mc', 'Past of "bring":', 'brought|bringed|brang', 'Family: bought, brought.'],
    ['mc', '___ she like the gift?', 'Did|Was|Does', 'Past question → did.'],
    ['mc', 'We ___ to Cartagena last December.', 'went|go|goed', 'Go → went.'],
    ['mc', 'Which -ed sounds /ɪd/?', 'needed|loved|stopped', 'After d → /ɪd/.'],
    ['fill', 'I ___ (not / see) the message.', "didn't see|did not see", 'didn’t + base verb.'],
    ['fill', 'They ___ (arrive) two hours ago.', 'arrived', 'Regular → -ed.'],
    ['fix', 'Where you were yesterday?', 'Where were you yesterday?', 'Verb before subject in questions.'],
    ['fix', 'She didn’t wrote back.', "She didn't write back.", 'After didn’t → base verb.'],
    ['fix', 'I meeted her in 2020.', 'I met her in 2020.', 'Meet → met.'],
    ['order', 'My grandmother told me a beautiful story', 'Mi abuela me contó una historia hermosa'],
    ['listen', 'She was born in Cali and moved to Bogotá.'],
  ],
}
