export default {
  id: 'm6', level: 'A2', title: 'The Beauty Counter', subtitle: 'Quantities · comparatives · superlatives',
  goal: 'Compare products, talk about quantities and analyze a brand.',
  lessons: [
    {
      id: 'm6l1', title: 'Some serum, any perfume?', topic: 'countable / uncountable',
      intro: 'Some things you can count. Others you can’t — and English cares.',
      theory: [
        { h: 'Count or not?', p: 'Countable: **one bottle, two bottles**. Uncountable: **water, perfume, information, advice, makeup** — **no plural, no a/an**.',
          es: 'Incontables: no llevan **-s ni a/an**. **information** (no “informations”), advice, makeup, hair.',
          table: [['countable', 'a lipstick · two bottles · some products'], ['uncountable', 'some water · perfume · information · advice · makeup']] },
        { h: 'Make them countable', p: 'Use a container or unit: **a bottle of** perfume, **a piece of** advice, **a cup of** coffee.',
          es: 'Para contarlos usa un recipiente: **a bottle of**, **a piece of**, **a cup of**.', anim: ['an advice', 'a piece of advice'] },
        { h: 'some / any again', p: 'Module 3 thread: **some (+)**, **any (− and ?)**. Both work with countable plurals and uncountables.',
          es: 'Igual que en el módulo 3.', ex: ['I need some information.', "We don't have any samples.", 'Is there any coffee?'] },
      ],
      vocab: [['serum', 'sérum', 'This serum is light.'], ['sample', 'muestra', 'Can I have a sample?'], ['skin', 'piel', 'My skin is dry.'],
        ['makeup', 'maquillaje', 'She wears natural makeup.'], ['advice', 'consejo(s)', 'Can you give me some advice?'], ['information', 'información', 'I need some information.'],
        ['bottle', 'frasco/botella', 'a bottle of perfume'], ['skincare', 'cuidado de la piel', 'Her skincare routine is simple.']],
      ex: [
        ['mc', 'Which is uncountable?', 'advice|bottle|lipstick', 'Advice has no plural.'],
        ['mc', 'Can you give me ___ information?', 'some|an|many', 'Uncountable → some.'],
        ['mc', "We don't have ___ samples today.", 'any|some|a', 'Negative → any.'],
        ['fill', 'I bought a ___ of perfume.', 'bottle', 'A bottle of…'],
        ['fill', 'She gave me a great piece of ___.', 'advice', 'A piece of advice.'],
        ['fix', 'I need some informations.', 'I need some information.', 'Information is uncountable.'],
        ['fix', 'She gave me an advice.', 'She gave me some advice.|She gave me a piece of advice.', 'No a/an with advice.'],
        ['order', 'Is there any serum for dry skin', '¿Hay algún sérum para piel seca?'],
        ['listen', 'Can I have a sample of this perfume?'],
        ['speak', 'I need some advice about skincare.'],
      ],
      links: ['m3l1', 'm1l4'],
    },
    {
      id: 'm6l2', title: 'How much? How many?', topic: 'much / many / a lot of',
      intro: 'Quantities for budgets, products and campaigns.',
      theory: [
        { h: 'many vs much', p: '**Many** + countable plural. **Much** + uncountable. Mostly in questions and negatives.',
          es: '**many** (contables), **much** (incontables). **How many** bottles? **How much** money?',
          table: [['many', 'many products · how many followers?'], ['much', 'much time · how much money?'], ['a lot of', 'both! a lot of products · a lot of time']] },
        { h: 'a lot of = the safe choice', p: 'In positive sentences, **a lot of** sounds most natural for both types.',
          es: 'En afirmativo, **a lot of** es lo más natural.', ex: ['She has a lot of followers.', "We don't have much time.", 'How many posts do we need?'] },
        { h: 'a few / a little', p: '**A few** (countable) and **a little** (uncountable) = a small amount.',
          es: '**a few** (unos pocos) / **a little** (un poco).', anim: ['many ideas', 'a few ideas'] },
      ],
      vocab: [['budget', 'presupuesto', "We don't have much budget."], ['followers', 'seguidores', 'How many followers does she have?'], ['price', 'precio', 'How much is it?'],
        ['cost', 'costar', 'How much does it cost?'], ['a few', 'unos pocos', 'I have a few ideas.'], ['a little', 'un poco', 'Add a little cream.'],
        ['enough', 'suficiente', 'Do we have enough time?'], ['too much', 'demasiado', 'This is too much money.']],
      ex: [
        ['mc', 'How ___ is this lipstick?', 'much|many|lot', 'Price → how much.'],
        ['mc', 'How ___ followers does the brand have?', 'many|much|lot of', 'Followers are countable.'],
        ['mc', "We don't have ___ time.", 'much|many|a few', 'Time is uncountable.'],
        ['mc', 'I have ___ ideas for the campaign. (small number)', 'a few|a little|much', 'Countable → a few.'],
        ['fill', 'She has a ___ of experience in social media.', 'lot', 'A lot of.'],
        ['fill', 'Add a ___ water to the mask.', 'little', 'Uncountable → a little.'],
        ['fix', 'How many money do you need?', 'How much money do you need?', 'Money is uncountable.'],
        ['order', 'How much does this perfume cost', '¿Cuánto cuesta este perfume?'],
        ['listen', "We don't have much budget, but we have a lot of ideas."],
        ['speak', 'How many products do you use every day?'],
      ],
      links: ['m6l1', 'm2l2'],
    },
    {
      id: 'm6l3', title: 'Softer, lighter, better', topic: 'comparatives',
      intro: 'Compare two things — the heart of every product launch.',
      theory: [
        { h: 'Short adjectives: -er than', p: 'One syllable: **+er** (soft → **softer**). Ending in -y: **-ier** (easy → **easier**).',
          es: 'Cortos: **+er**. light → **lighter**, pretty → **prettier**. Siempre con **than**.', anim: ['This cream is soft', 'This cream is softer than that one'] },
        { h: 'Long adjectives: more … than', p: 'Two or more syllables (not -y): **more + adjective**.',
          es: 'Largos: **more** elegant, **more** expensive.', ex: ['This bottle is more elegant than the old one.', 'Paris is more expensive than Bogotá.'] },
        { h: 'Irregular', p: 'good → **better**, bad → **worse**, far → **farther**.',
          es: 'Irregulares: **better** (mejor), **worse** (peor).', table: [['good', 'better'], ['bad', 'worse'], ['far', 'farther']] },
      ],
      vocab: [['soft', 'suave', 'Your skin is softer.'], ['light', 'ligero', 'This serum is lighter.'], ['smooth', 'liso/terso', 'It makes your skin smoother.'],
        ['elegant', 'elegante', 'The new design is more elegant.'], ['affordable', 'asequible', 'It is more affordable.'], ['long-lasting', 'duradero', 'This lipstick is more long-lasting.'],
        ['than', 'que (comparación)', 'better than before'], ['packaging', 'empaque', 'The packaging is prettier.']],
      ex: [
        ['mc', 'The new formula is ___ than the old one.', 'lighter|more light|lightest', 'Short → -er.'],
        ['mc', 'This perfume is ___ than that one.', 'more elegant|elegant-er|most elegant', 'Long → more.'],
        ['mc', 'Her English is ___ than last year!', 'better|gooder|more good', 'Good → better.'],
        ['fill', 'This packaging is ___ (pretty) than the other.', 'prettier', '-y → -ier.'],
        ['fill', 'My skin is ___ (bad) in winter than in summer.', 'worse', 'Bad → worse.'],
        ['fix', 'This cream is more soft than that one.', 'This cream is softer than that one.', 'Short → -er.'],
        ['fix', 'It is cheaper that the original.', 'It is cheaper than the original.', 'Compare with than.'],
        ['order', 'The new bottle is more elegant than the old one', 'La botella nueva es más elegante que la vieja'],
        ['listen', 'This lipstick is more long-lasting and more affordable.'],
        ['speak', 'My English is better than last month.'],
      ],
      links: ['m3l3', 'm6l2'],
    },
    {
      id: 'm6l4', title: 'The most iconic', topic: 'superlatives & as…as',
      intro: 'The best, the most beautiful, the most iconic — superlatives sell.',
      theory: [
        { h: 'the + -est / the most', p: 'Superlatives compare one thing with all the group. Short: **the softest**. Long: **the most iconic**.',
          es: 'Superlativo: **the + -est / the most**. Siempre con **the**.', anim: ['softer than the others', 'the softest of all'] },
        { h: 'Irregular', p: 'good → better → **the best**. bad → worse → **the worst**.',
          es: '**the best** (el mejor), **the worst** (el peor).', table: [['soft', 'softer', 'the softest'], ['iconic', 'more iconic', 'the most iconic'], ['good', 'better', 'the best'], ['bad', 'worse', 'the worst']] },
        { h: 'as … as', p: 'Equal: **as soft as**. Not equal: **not as expensive as**.',
          es: 'tan … como = **as … as**.', ex: ['This is as good as the original.', 'It is not as expensive as I thought.'] },
      ],
      vocab: [['iconic', 'icónico', 'the most iconic perfume'], ['best-seller', 'más vendido', "It's our best-seller."], ['popular', 'popular', 'the most popular color'],
        ['shade', 'tono', 'This is the darkest shade.'], ['customer', 'cliente', 'our happiest customers'], ['review', 'reseña', 'It has the best reviews.'],
        ['range', 'línea (productos)', 'the newest range'], ['worldwide', 'mundial', 'the biggest brand worldwide']],
      ex: [
        ['mc', 'It’s ___ perfume in the store.', 'the most iconic|the iconicest|most iconic', 'Long → the most.'],
        ['mc', 'This is ___ day of my life!', 'the best|the better|the goodest', 'Good → the best.'],
        ['mc', 'This shade is ___ dark ___ that one. (equal)', 'as / as|more / than|so / that', 'Equal → as … as.'],
        ['fill', "It's the ___ (cheap) option.", 'cheapest', 'Short → -est.'],
        ['fill', 'That was the ___ (bad) review we had.', 'worst', 'Bad → the worst.'],
        ['fix', 'She is the most young in the team.', 'She is the youngest in the team.', 'Short → -est.'],
        ['fix', 'This serum is as good than the original.', 'This serum is as good as the original.', 'as … as.'],
        ['order', "It's the most popular shade worldwide", 'Es el tono más popular del mundo'],
        ['listen', 'Our best-seller has the best reviews.'],
        ['speak', 'Paris is the most romantic city in the world.'],
      ],
      links: ['m6l3'],
    },
    {
      id: 'm6l5', title: 'Letters from New York · Ch.6', topic: 'story: brand analysis', story: true,
      intro: 'Chapter 6: Meri studies Maison Lumière like a strategist.',
      read: { title: 'A strategist at the counter', text:
`For my application I needed a lot of information about Maison Lumière, so I went to a beauty store in the city center.

There were many brands, but Maison Lumière's counter was the most elegant. The packaging was simpler than the others: white bottles, gold letters, no extra decoration. "It's our best-seller," the saleswoman said, and she gave me some samples.

At home I compared everything. Their serum was lighter than the competition and not as expensive as I thought. But their Instagram had fewer stories and much less emotion.

I wrote my first idea in my white notebook: "The products are beautiful. The brand needs a story." I looked at Rosa's letter on my desk and I smiled.` },
      theory: [
        { h: 'Analysis in English', p: 'Spot **quantities** (a lot of, many, some), **comparatives and superlatives**. You just read a mini brand analysis!',
          es: 'Una mini auditoría de marca con todo el módulo 6.' },
      ],
      vocab: [['counter', 'mostrador', 'the Maison Lumière counter'], ['saleswoman', 'vendedora', 'The saleswoman was kind.'], ['competition', 'competencia', 'lighter than the competition'],
        ['fewer', 'menos (contables)', 'fewer stories'], ['less', 'menos (incontables)', 'less emotion'], ['decoration', 'decoración', 'no extra decoration']],
      ex: [
        ['read', 'Why did Meri go to the store?', 'She needed information for her application|She wanted a new perfume|She works there', '"I needed a lot of information…"'],
        ['read', 'How was the Maison Lumière packaging?', 'Simpler than the others|More decorated|The cheapest', '"The packaging was simpler than the others."'],
        ['read', 'What did the brand need, according to Meri?', 'A story|More products|Lower prices', '"The brand needs a story."'],
        ['read', 'How was their Instagram?', 'Fewer stories and less emotion|The best in the market|More expensive', '"…fewer stories and much less emotion."'],
        ['fix', 'The packaging was more simple than the others.', 'The packaging was simpler than the others.', 'Simple → simpler.'],
        ['mc', 'There were ___ brands in the store.', 'many|much|a little', 'Countable → many.'],
        ['listen', "It's our best-seller."],
        ['speak', 'The products are beautiful. The brand needs a story.'],
      ],
      links: ['m6l1', 'm6l3', 'm6l4', 'm5l5'],
    },
  ],
  exam: [
    ['mc', 'Which is uncountable?', 'furniture|chair|lamp', 'Furniture is uncountable (a piece of furniture).'],
    ['mc', 'How ___ coffee do you drink?', 'much|many|lot', 'Coffee is uncountable.'],
    ['mc', 'There are only ___ tickets left.', 'a few|a little|much', 'Countable → a few.'],
    ['mc', 'This is ___ than I expected.', 'better|best|more good', 'Good → better.'],
    ['mc', 'She is ___ person in the office.', 'the funniest|the most funny|funnier', '-y → -iest.'],
    ['fill', 'New York is ___ (big) than Paris.', 'bigger', 'CVC → double + er.'],
    ['fill', 'It’s not as expensive ___ the original.', 'as', 'as … as.'],
    ['fix', 'Can you give me an information?', 'Can you give me some information?', 'Information is uncountable.'],
    ['fix', 'It is the more beautiful painting here.', 'It is the most beautiful painting here.', 'Superlative → the most.'],
    ['fix', 'I have much friends in Bogotá.', 'I have a lot of friends in Bogotá.|I have many friends in Bogotá.', 'Countable positive → a lot of / many.'],
    ['order', 'This is the best serum for dry skin', 'Este es el mejor sérum para piel seca'],
    ['listen', 'The new range is lighter and more affordable.'],
  ],
}
