export default {
  id: 'm7', level: 'A2', title: 'Plans & Dreams', subtitle: 'going to · will · future arrangements',
  goal: 'Talk about your plans, predictions, promises and career goals.',
  lessons: [
    {
      id: 'm7l1', title: "I'm going to apply", topic: 'be going to',
      intro: 'Plans and intentions you already decided.',
      theory: [
        { h: 'be + going to + verb', p: 'Use **am / is / are + going to + base verb** for **plans you already made**.',
          es: '**Planes ya decididos**: I’m **going to study** = voy a estudiar.', anim: ['I apply for the job', "I'm going to apply for the job"] },
        { h: 'Evidence predictions', p: 'Also for **predictions with evidence** you can see now.',
          es: '**Predicción con evidencia**: Look at the clouds! It’s **going to rain**.', ex: ["Look at those clouds. It's going to rain.", "She's going to love this gift."] },
        { h: 'Negatives & questions', p: 'Just like **to be**: She **isn’t going to…** / **Are you going to…?**',
          es: 'Igual que **to be** (módulo 1).', ex: ["I'm not going to give up.", 'What are you going to wear?'] },
      ],
      vocab: [['plan', 'plan / planear', "What's your plan?"], ['give up', 'rendirse', "I'm not going to give up."], ['prepare', 'preparar', "I'm going to prepare my CV."],
        ['CV / résumé', 'hoja de vida', 'She is going to update her CV.'], ['portfolio', 'portafolio', 'I am going to show my portfolio.'], ['goal', 'meta', 'My goal is B1.'],
        ['save money', 'ahorrar', "We're going to save money."], ['next year', 'el próximo año', "I'm going to travel next year."]],
      ex: [
        ['mc', 'I ___ apply for the job tomorrow.', "'m going to|going to|go to", 'be + going to.'],
        ['mc', 'Look at the sky! It ___ rain.', "'s going to|will|is go to", 'Evidence → going to.'],
        ['mc', 'What ___ you going to wear?', 'are|do|will', 'You → are.'],
        ['fill', "She ___ going to update her CV tonight.", "is|'s", 'She → is.'],
        ['fill', "I'm not going ___ give up.", 'to', 'going TO + verb.'],
        ['fix', 'We going to travel next year.', "We're going to travel next year.|We are going to travel next year.", 'Don’t forget are.'],
        ['fix', "He's going to prepares the slides.", "He's going to prepare the slides.", 'Base verb after to.'],
        ['order', "I'm going to update my portfolio this weekend", 'Voy a actualizar mi portafolio este fin de semana'],
        ['listen', "She's going to love this gift."],
        ['speak', "I'm going to reach B1 this year."],
      ],
      links: ['m4l1', 'm1l2'],
    },
    {
      id: 'm7l2', title: "I'll help you, I promise", topic: 'will',
      intro: 'Instant decisions, promises, offers and predictions.',
      theory: [
        { h: 'will + base verb', p: '**Will** is the same for everyone (like can!). Contraction: **’ll**. Negative: **won’t**.',
          es: '**will** no cambia por persona. **I’ll**, **she’ll**. Negativo: **won’t** (will not).', anim: ['I help you', "I'll help you"] },
        { h: 'When to use will', p: '**Decisions you make NOW**, **promises**, **offers**, and **predictions based on opinion**.',
          es: '**Decisión en el momento**, **promesas**, **ofrecimientos** y **predicciones por opinión**.',
          ex: ["The phone is ringing — I'll answer it!", "I'll always remember this.", 'I think you’ll get the job.'] },
        { h: 'going to vs will', p: 'Decided before → **going to**. Decided now → **will**.',
          es: 'Ya lo decidí → **going to**. Lo decido ahora → **will**.', table: [['plan already made', "I'm going to call her tonight."], ['decision now', "Oh, it's late! I'll call her tomorrow."]] },
      ],
      vocab: [['promise', 'prometer', 'I promise I’ll write.'], ['probably', 'probablemente', "I'll probably be late."], ['maybe', 'tal vez', "Maybe she'll call."],
        ['I think', 'creo que', "I think it'll be great."], ['offer', 'ofrecer', "I'll carry it for you."], ['answer', 'contestar', "I'll answer the phone."],
        ['won’t', 'no (futuro)', "I won't forget."], ['future', 'futuro', 'The future will be bright.']],
      ex: [
        ['mc', 'The phone is ringing. — I ___ answer it!', "'ll|'m going to|will to", 'Decision now → will.'],
        ['mc', 'I promise I ___ forget your birthday.', "won't|don't|am not going", 'Promise → won’t.'],
        ['mc', 'I think you ___ get the job.', 'will|are|going', 'Opinion prediction → will.'],
        ['mc', "We bought the tickets. We ___ to Paris in May.", "'re going to fly|'ll fly|fly will", 'Plan already made → going to.'],
        ['fill', 'She ___ probably call you later.', 'will', 'Prediction → will.'],
        ['fix', 'She wills help you.', 'She will help you.', 'No -s with will.'],
        ['fix', "I'll to call you tomorrow.", "I'll call you tomorrow.", 'No “to” after will.'],
        ['order', "I think the campaign will be a success", 'Creo que la campaña será un éxito'],
        ['listen', "Don't worry. I'll help you with the presentation."],
        ['speak', "I promise I won't give up."],
      ],
      links: ['m7l1', 'm3l4'],
    },
    {
      id: 'm7l3', title: "I'm meeting her on Friday", topic: 'present continuous for future',
      intro: 'Arrangements in your calendar — with a time and a place.',
      theory: [
        { h: 'Calendar = continuous', p: 'For **fixed arrangements** (with a date, time, other people), use the **present continuous** (module 4!).',
          es: '**Citas fijas** en tu agenda: I’m **meeting** the director on Friday.', anim: ['I meet the director', "I'm meeting the director on Friday"] },
        { h: 'Future time words', p: '**tomorrow**, **tonight**, **next week**, **on Friday**, **in two days**, **the day after tomorrow**.',
          es: '**in two days** = en dos días. **the day after tomorrow** = pasado mañana.', ex: ["I'm flying to New York next week.", 'We are having dinner tonight.'] },
        { h: 'Timetables: simple', p: 'Schedules (trains, flights, events) use the **present simple**.',
          es: '**Horarios oficiales**: The flight **leaves** at 6.', ex: ['The flight leaves at 6:40.', 'The exhibition opens on Monday.'] },
      ],
      vocab: [['arrangement', 'acuerdo/cita', 'I have an arrangement.'], ['interview', 'entrevista', "I'm having an interview tomorrow."], ['flight', 'vuelo', 'The flight leaves at six.'],
        ['the day after tomorrow', 'pasado mañana', "We're meeting the day after tomorrow."], ['calendar', 'agenda', 'Check your calendar.'], ['exhibition', 'exposición', 'The exhibition opens on Monday.'],
        ['book', 'reservar', "I'm booking a table."], ['call (n.)', 'llamada', 'I have a video call at ten.']],
      ex: [
        ['mc', "I ___ the HR manager tomorrow at ten.", "'m meeting|meet|will meeting", 'Arrangement → continuous.'],
        ['mc', 'The train ___ at 7:15.', 'leaves|is leaving tomorrow|leave', 'Timetable → simple.'],
        ['mc', 'What ___ you doing this weekend?', 'are|do|will', 'Arrangements → are you doing.'],
        ['fill', "We ___ having dinner with Laura on Saturday.", "are|'re", 'Arrangement.'],
        ['fill', "The exhibition ___ (open) on Monday.", 'opens', 'Timetable → simple.'],
        ['fix', 'I meet the director on Friday at 3.', "I'm meeting the director on Friday at 3.|I am meeting the director on Friday at 3.", 'Fixed arrangement → continuous.'],
        ['order', "I'm having a video interview the day after tomorrow", 'Tengo una entrevista por video pasado mañana'],
        ['listen', "We're flying to New York next week."],
        ['speak', "I'm meeting my friend tonight."],
      ],
      links: ['m7l1', 'm4l2', 'm2l4'],
    },
    {
      id: 'm7l4', title: 'I would like to work in…', topic: 'want to / would like to / hope to',
      intro: 'The vocabulary of ambition — perfect for interviews.',
      theory: [
        { h: 'verb + to + verb', p: 'Some verbs are followed by **to + base verb**: **want, would like, hope, plan, decide, need, learn**.',
          es: 'Verbos que van con **to**: I **want to grow**, I **hope to work**…', ex: ['I want to grow in strategic communication.', 'She decided to learn English.'] },
        { h: 'would like = polite want', p: '**I’d like to…** is softer and more professional than I want to…',
          es: '**I’d like to** = me gustaría. Más **formal** que want.', anim: ['I want to work here', "I'd like to work here"] },
        { h: 'like vs would like', p: '**I like** = in general. **I would like** = a wish now.',
          es: '**I like** coffee (en general) vs **I’d like** a coffee (quiero uno ahora).', ex: ['I like Paris.', "I'd like to visit Paris."] },
      ],
      vocab: [['would like', 'me gustaría', "I'd like to join your team."], ['hope', 'esperar (deseo)', 'I hope to work abroad.'], ['grow', 'crecer', 'I want to grow professionally.'],
        ['join', 'unirse', "I'd like to join the team."], ['career', 'carrera profesional', 'My career is important to me.'], ['strategic', 'estratégico', 'strategic communication'],
        ['opportunity', 'oportunidad', 'Thank you for this opportunity.'], ['improve', 'mejorar', 'I want to improve my English.']],
      ex: [
        ['mc', "I'd like ___ your team.", 'to join|join|joining', 'would like + to.'],
        ['mc', 'More polite:', "I'd like to talk to the manager.|I want talk the manager.|I like talk to the manager.", 'Would like = polite.'],
        ['mc', '"Me gustaría un café" =', "I'd like a coffee.|I like a coffee.|I would a coffee.", 'Wish now → would like.'],
        ['fill', 'She hopes ___ work for an international brand.', 'to', 'hope + to.'],
        ['fill', 'I want to ___ (improve) my presentation skills.', 'improve', 'Base verb after to.'],
        ['fix', 'I would like work in New York.', 'I would like to work in New York.|I’d like to work in New York.', 'would like TO.'],
        ['fix', 'She wants grow in her career.', 'She wants to grow in her career.', 'want TO.'],
        ['order', "I'd like to grow in strategic communication", 'Me gustaría crecer en comunicación estratégica'],
        ['listen', 'Thank you for this opportunity. I hope to join your team.'],
        ['speak', "I'd like to work for an international beauty brand."],
      ],
      links: ['m7l1', 'm4l3', 'm1l3'],
    },
    {
      id: 'm7l5', title: 'Letters from New York · Ch.7', topic: 'story: future', story: true,
      intro: 'Chapter 7: The answer from Maison Lumière arrives.',
      read: { title: 'An invitation', text:
`Two weeks later I got an email: "Dear Meri, thank you for your application. We would like to invite you to a video interview with our Communication Director, Claire Dubois. Are you available next Thursday at 10 a.m.?"

I read it three times. Then I called Laura. "I'm having an interview on Thursday! In English!"

"You're going to be great," she said. "And I'll help you. Tomorrow we're going to practice every question."

That night I made a plan in my notebook: On Monday I'm going to update my portfolio. On Tuesday I'm going to research Claire Dubois. On Wednesday I'll rest… or maybe I won't.

Before sleeping, I looked at Rosa's letter. "I'd like to find you," I whispered. "Maybe New York will help me."` },
      theory: [
        { h: 'Futures everywhere', p: 'Find **going to** (plans), **will** (promises/predictions), **present continuous** (arrangement) and **would like**. Module 7 is all here.',
          es: 'Cuatro formas de futuro en una escena.' },
      ],
      vocab: [['invite', 'invitar', 'We would like to invite you.'], ['available', 'disponible', 'Are you available on Thursday?'], ['director', 'directora', 'Communication Director'],
        ['research', 'investigar', "I'm going to research the company."], ['rest', 'descansar', "On Wednesday I'll rest."], ['whisper', 'susurrar', 'I whispered her name.']],
      ex: [
        ['read', 'Who is Claire Dubois?', 'The Communication Director|Laura’s sister|Rosa’s friend', '"…our Communication Director, Claire Dubois."'],
        ['read', 'When is the interview?', 'Next Thursday at 10 a.m.|On Monday|Tomorrow at 10', '"…next Thursday at 10 a.m."'],
        ['read', 'What is Meri going to do on Tuesday?', 'Research Claire Dubois|Update her portfolio|Rest', '"On Tuesday I\'m going to research Claire Dubois."'],
        ['read', 'What did Laura promise?', "She'll help Meri|She'll go to New York|She'll call Claire", '"And I\'ll help you."'],
        ['fix', 'I would like find you.', "I would like to find you.|I'd like to find you.", 'would like TO.'],
        ['mc', '"I ___ an interview on Thursday!" (arrangement)', "'m having|have will|going have", 'Arrangement → continuous.'],
        ['listen', "You're going to be great. And I'll help you."],
        ['speak', 'Maybe New York will help me.'],
      ],
      links: ['m7l1', 'm7l2', 'm7l3', 'm7l4', 'm6l5'],
    },
  ],
  exam: [
    ['mc', "I've decided. I ___ study marketing.", "'m going to|will to|going", 'Decided plan → going to.'],
    ['mc', "It's cold. — I ___ close the window.", "'ll|'m going|am", 'Decision now → will.'],
    ['mc', "We ___ lunch with the client tomorrow at 1.", "'re having|have will|having", 'Arrangement.'],
    ['mc', 'The concert ___ at 8 p.m. (timetable)', 'starts|will starting|is start', 'Timetable → simple.'],
    ['mc', "I'd like ___ more about the position.", 'to know|knowing|know', 'would like + to.'],
    ['fill', "I promise I ___ be late. (negative)", "won't|will not", 'Promise → won’t.'],
    ['fill', 'Are you going ___ apply?', 'to', 'going to.'],
    ['fix', 'She will goes to Paris.', 'She will go to Paris.', 'Will + base verb.'],
    ['fix', 'I hope get the job.', 'I hope to get the job.', 'hope TO.'],
    ['fix', 'They going to move next month.', "They're going to move next month.|They are going to move next month.", 'Don’t forget are.'],
    ['order', "I think you'll love New York", 'Creo que amarás Nueva York'],
    ['listen', "I'd like to invite you to an interview next Thursday."],
  ],
}
