export default {
  id: 'm8', level: 'A2+', title: 'Have You Ever?', subtitle: 'Present perfect · experiences · for/since',
  goal: 'Talk about your experience and achievements — the language of interviews and CVs.',
  lessons: [
    {
      id: 'm8l1', title: 'I have visited, I have never seen', topic: 'present perfect: experiences',
      intro: 'Life experiences — without saying exactly when.',
      theory: [
        { h: 'have / has + past participle', p: 'The participle of regular verbs = **-ed** (visited). Irregular ones have their own form: be → **been**, see → **seen**, write → **written**.',
          es: '**have/has + participio**. Es como “he visitado”. He/she/it → **has**.', anim: ['I visited Paris', 'I have visited Paris'],
          table: [['be', 'was/were', 'been'], ['go', 'went', 'gone / been'], ['see', 'saw', 'seen'], ['write', 'wrote', 'written'], ['do', 'did', 'done'], ['make', 'made', 'made'], ['lead', 'led', 'led']] },
        { h: 'ever & never', p: '**Have you ever…?** = ¿Alguna vez has…? **Never** = nunca (with a positive verb).',
          es: '**Have you ever been** to New York? — No, I’ve **never been** there.', anim: ['You have been to New York', 'Have you ever been to New York?'] },
        { h: 'been vs gone', p: 'She has **been** to Paris = she went and came back. She has **gone** to Paris = she is there now.',
          es: '**been** = fue y volvió. **gone** = se fue y sigue allá.', ex: ["I've been to Cartagena twice.", "Laura isn't here. She's gone to the bank."] },
      ],
      vocab: [['ever', 'alguna vez', 'Have you ever led a team?'], ['never', 'nunca', "I've never been to Paris."], ['experience', 'experiencia', 'I have experience in PR.'],
        ['lead (led)', 'liderar', "I've led three campaigns."], ['twice', 'dos veces', "I've been there twice."], ['achievement', 'logro', 'My biggest achievement'],
        ['award', 'premio', 'Our campaign has won an award.'], ['manage', 'gestionar', "I've managed social media accounts."]],
      ex: [
        ['mc', 'Have you ever ___ to New York?', 'been|went|go', 'Participle of be → been.'],
        ['mc', 'She ___ three campaigns.', 'has led|have led|has lead', 'She → has + participle.'],
        ['mc', 'Participle of "write":', 'written|wrote|writed', 'write → wrote → written.'],
        ['fill', "I've ___ seen snow. (0%)", 'never', 'never = nunca.'],
        ['fill', '___ she ever worked abroad?', 'Has', 'She → has.'],
        ['fix', 'I have saw that movie.', 'I have seen that movie.|I’ve seen that movie.', 'Participle → seen.'],
        ['fix', 'He have managed big accounts.', 'He has managed big accounts.|He’s managed big accounts.', 'He → has.'],
        ['order', 'Have you ever led a communication team', '¿Alguna vez has liderado un equipo de comunicación?'],
        ['listen', "I've been to Cartagena twice, but I've never been to Paris."],
        ['speak', "I've managed social media accounts for two brands."],
      ],
      links: ['m5l3', 'm1l2'],
    },
    {
      id: 'm8l2', title: 'Just, already, yet', topic: 'present perfect: just/already/yet',
      intro: 'Recent news and to-do lists — very common at work.',
      theory: [
        { h: 'just = a moment ago', p: '**Just** goes between have and the participle.',
          es: '**just** = acabo de. I’ve **just sent** the email.', anim: ['I have sent the email', 'I have just sent the email'] },
        { h: 'already = sooner than expected', p: '**Already** also goes in the middle.',
          es: '**already** = ya. She’s **already finished**!', ex: ["She's already finished the report.", "We've already booked the flights."] },
        { h: 'yet = until now (− and ?)', p: '**Yet** goes at the end, only in negatives and questions.',
          es: '**yet** al final: Have you finished **yet**? — Not yet. I haven’t finished **yet**.', ex: ['Have you replied yet?', "I haven't decided yet."] },
      ],
      vocab: [['just', 'acabar de', "I've just arrived."], ['already', 'ya', "I've already done it."], ['yet', 'todavía / ya (pregunta)', "I haven't finished yet."],
        ['send (sent)', 'enviar', "I've just sent it."], ['reply', 'responder', "She hasn't replied yet."], ['finish', 'terminar', 'Have you finished yet?'],
        ['deadline', 'fecha límite', "We've already met the deadline."], ['update', 'actualizar', "I've just updated the file."]],
      ex: [
        ['mc', "I've ___ sent you the file. Check your inbox!", 'just|yet|ever', 'A moment ago → just.'],
        ['mc', 'Have you finished the slides ___?', 'yet|already|just', 'Question at the end → yet.'],
        ['mc', "She hasn't replied ___.", 'yet|already|just', 'Negative at the end → yet.'],
        ['fill', "Don't worry, we've ___ booked the hotel.", 'already', 'Sooner than expected → already.'],
        ['fix', "I haven't finished already.", "I haven't finished yet.", 'Negative → yet.'],
        ['fix', 'I have yet sent it.', 'I have already sent it.|I have just sent it.', 'Yet goes at the end in − and ?.'],
        ['order', "She's just updated the presentation", 'Ella acaba de actualizar la presentación'],
        ['order', "Have you replied to the client yet", '¿Ya le respondiste al cliente?'],
        ['listen', "We've already met the deadline."],
        ['speak', "I've just finished my English lesson!"],
      ],
      links: ['m8l1'],
    },
    {
      id: 'm8l3', title: 'For three years, since 2022', topic: 'for / since / how long',
      intro: 'Things that started in the past and continue now.',
      theory: [
        { h: 'Past → now', p: 'Present perfect connects the **past with now**. In Spanish you often use the present: “Trabajo aquí hace 3 años”.',
          es: 'Trabajo aquí desde hace 3 años = I **have worked** here **for** three years (¡no “I work here since”!).', anim: ['I work here for three years', 'I have worked here for three years'] },
        { h: 'for vs since', p: '**For** + a period (three years, two months). **Since** + a starting point (2022, March, I was a child).',
          es: '**for** = durante (periodo). **since** = desde (momento).', table: [['for', 'two weeks · five years · a long time'], ['since', '2022 · Monday · I was 18']] },
        { h: 'How long…?', p: '**How long have you** + participle…?',
          es: '¿Cuánto tiempo llevas…? = **How long have you…?**', ex: ['How long have you lived here?', 'How long has she known Laura?'] },
      ],
      vocab: [['how long', 'cuánto tiempo', 'How long have you studied English?'], ['for', 'durante', 'for six months'], ['since', 'desde', 'since 2020'],
        ['know (known)', 'conocer', "I've known her for years."], ['live', 'vivir', "I've lived here since 2019."], ['a long time', 'mucho tiempo', 'for a long time'],
        ['position', 'cargo', "I've had this position since May."], ['field', 'campo/área', "I've worked in this field for five years."]],
      ex: [
        ['mc', "I've lived here ___ 2019.", 'since|for|from', 'Starting point → since.'],
        ['mc', "She's worked in PR ___ five years.", 'for|since|during', 'Period → for.'],
        ['mc', '"Conozco a Laura desde hace 10 años" =', "I've known Laura for ten years.|I know Laura since ten years.|I knew Laura for ten years.", 'Past → now = present perfect + for.'],
        ['fill', 'How ___ have you studied English?', 'long', 'How long…?'],
        ['fill', "We've been friends ___ we were children.", 'since', 'Starting point → since.'],
        ['fix', 'I work here since 2021.', "I've worked here since 2021.|I have worked here since 2021.", 'Since → present perfect.'],
        ['fix', "She's had this position since two years.", "She's had this position for two years.", 'Period → for.'],
        ['order', "I've worked in communication for six years", 'He trabajado en comunicación durante seis años'],
        ['listen', 'How long have you known Claire?'],
        ['speak', "I've studied English since this year."],
      ],
      links: ['m8l1', 'm5l1'],
    },
    {
      id: 'm8l4', title: 'I have led… / Last year I led…', topic: 'present perfect vs past simple',
      intro: 'The most important difference for a job interview.',
      theory: [
        { h: 'When? → past simple', p: 'If you say WHEN (yesterday, in 2022, last year), use the **past simple**. If time is not important, use **present perfect**.',
          es: 'Con fecha → **pasado simple**. Sin fecha (experiencia) → **present perfect**.',
          table: [['present perfect', "I've led a national campaign. (no time)"], ['past simple', 'I led it in 2023. (time!)']] },
        { h: 'Interview pattern', p: 'Open with the **experience**, then give **details in the past**.',
          es: 'Patrón de entrevista: **experiencia → detalle en pasado**.', anim: ["I've worked with beauty brands", 'In 2023 I worked with a beauty brand'] },
        { h: 'Never with ago', p: '**Ago, yesterday, last…** always go with the **past simple**.',
          es: 'Nunca: “**I have visited Paris two years ago**”.', ex: ['I visited Paris two years ago.', "I've visited Paris twice."] },
      ],
      vocab: [['launch', 'lanzar', 'We launched a new product.'], ['increase', 'aumentar', 'Engagement increased by 40%.'], ['result', 'resultado', 'The results were great.'],
        ['engagement', 'interacción', 'We increased engagement.'], ['handle', 'manejar', "I've handled crisis communication."], ['crisis', 'crisis', 'a reputation crisis'],
        ['press release', 'comunicado de prensa', 'I wrote the press release.'], ['stakeholder', 'grupo de interés', 'We met the stakeholders.']],
      ex: [
        ['mc', 'I ___ a campaign for a beauty brand in 2023.', 'led|have led|lead', 'In 2023 → past simple.'],
        ['mc', "___ you ever handled a crisis?", 'Have|Did|Were', 'Ever (no time) → present perfect.'],
        ['mc', 'We ___ the product two months ago.', 'launched|have launched|launch', 'Ago → past simple.'],
        ['fill', "I ___ written many press releases. (experience)", 'have|’ve', 'Experience → have + participle.'],
        ['fill', 'Last year engagement ___ (increase) by 40%.', 'increased', 'Last year → past simple.'],
        ['fix', 'I have met the CEO yesterday.', 'I met the CEO yesterday.', 'Yesterday → past simple.'],
        ['fix', 'Did you ever work with influencers?', 'Have you ever worked with influencers?', 'Ever → present perfect.'],
        ['order', "I've handled crisis communication for two brands", 'He manejado comunicación de crisis para dos marcas'],
        ['listen', 'Have you ever launched a product? Yes, I launched one last year.'],
        ['speak', "I've worked with brands. Last year I led a campaign."],
      ],
      links: ['m8l1', 'm8l3', 'm5l4'],
    },
    {
      id: 'm8l5', title: 'Letters from New York · Ch.8', topic: 'story: the interview', story: true,
      intro: 'Chapter 8: Thursday, 10 a.m. Claire Dubois is on the screen.',
      read: { title: 'Thursday, 10 a.m.', text:
`Claire Dubois appeared on the screen. She had short silver hair and a red scarf. "Bonjour, Meri. Have you ever worked with a beauty brand?"

"Yes, I have," I said. "Last year I led a social media campaign for a small cosmetics company. Engagement increased by forty percent."

"Impressive. And have you ever lived abroad?"

"No, I haven't. But I've wanted to live in New York for a long time." Then I took a breath. "Can I show you something?" I held up Rosa's letter. "My great-aunt worked for a perfume company in New York in 1968. I think your brand needs stories like hers."

Claire was quiet. Then she leaned closer to the camera. "Where did you get that letter?" she asked. "I've seen that handwriting before."` },
      theory: [
        { h: 'Interview English', p: 'See how Meri mixes **present perfect** (experiences) and **past simple** (details with a time). That’s the winning pattern.',
          es: '**Experiencia en present perfect**, **detalles en pasado**: el patrón ganador.' },
      ],
      vocab: [['appear', 'aparecer', 'She appeared on the screen.'], ['scarf', 'bufanda/pañuelo', 'a red scarf'], ['impressive', 'impresionante', 'Impressive!'],
        ['take a breath', 'respirar hondo', 'I took a breath.'], ['great-aunt', 'tía abuela', 'my great-aunt Rosa'], ['handwriting', 'letra (escrita)', "I've seen that handwriting before."]],
      ex: [
        ['read', 'What did Meri do last year?', 'She led a social media campaign|She lived in New York|She met Claire', '"Last year I led a social media campaign…"'],
        ['read', 'Has Meri ever lived abroad?', "No, she hasn't|Yes, in New York|Yes, in Paris", '"No, I haven\'t."'],
        ['read', 'What did Meri show Claire?', 'Rosa’s letter|Her portfolio|Her notebook', '"I held up Rosa\'s letter."'],
        ['read', 'Why was Claire surprised?', 'She has seen that handwriting before|She knows Laura|She hates letters', '"I\'ve seen that handwriting before."'],
        ['fix', 'I have led a campaign last year.', 'I led a campaign last year.', 'Last year → past simple.'],
        ['mc', "I ___ to live in New York for a long time.", "'ve wanted|want|wanted since", 'Past → now + for → present perfect.'],
        ['listen', "Have you ever worked with a beauty brand?"],
        ['speak', 'Engagement increased by forty percent.'],
      ],
      links: ['m8l1', 'm8l3', 'm8l4', 'm7l5'],
    },
  ],
  exam: [
    ['mc', 'Have you ever ___ sushi?', 'eaten|ate|eat', 'Participle of eat → eaten.'],
    ['mc', "She's lived in Bogotá ___ she was a child.", 'since|for|from', 'Starting point → since.'],
    ['mc', 'I ___ to Mexico in 2019.', 'went|have gone|have been', 'In 2019 → past simple.'],
    ['mc', "Have you done it ___? — No, not yet.", 'yet|already|just', 'Question → yet.'],
    ['mc', 'Laura is not here. She ___ to the gym.', 'has gone|has been|went yet', 'Still there → gone.'],
    ['fill', "I've ___ finished. It was a second ago!", 'just', 'A moment ago → just.'],
    ['fill', "They've been married ___ ten years.", 'for', 'Period → for.'],
    ['fix', 'I know her since 2015.', "I've known her since 2015.|I have known her since 2015.", 'Since → present perfect.'],
    ['fix', 'She has visited London last summer.', 'She visited London last summer.', 'Last summer → past simple.'],
    ['fix', 'Have you ever went to Paris?', 'Have you ever been to Paris?', 'Participle → been.'],
    ['order', "How long have you worked in communication", '¿Cuánto tiempo llevas trabajando en comunicación?'],
    ['listen', "I've never lived abroad, but I've traveled a lot."],
  ],
}
