export default {
  id: 'm9', level: 'A2+', title: 'Office Rules', subtitle: 'Modals · requests · obligation · advice',
  goal: 'Make polite requests, understand rules and give advice at work.',
  lessons: [
    {
      id: 'm9l1', title: 'Could you…? May I…?', topic: 'polite requests',
      intro: 'Polite English opens doors — literally.',
      theory: [
        { h: 'From casual to polite', p: 'Can you…? (friendly) → Could you…? (polite) → Would you mind + -ing? (very polite).',
          es: 'Could you…? es más educado que Can you…? Ideal para el trabajo.', anim: ['Can you send me the file?', 'Could you send me the file, please?'] },
        { h: 'Asking permission', p: 'Can I…? → Could I…? → May I…? (formal).',
          es: 'May I come in? = ¿Puedo pasar? (formal).', ex: ['Could I ask a question?', 'May I come in?'] },
        { h: 'Answering', p: 'Sure! / Of course. / Certainly. / I’m afraid I can’t.',
          es: 'I’m afraid… = me temo que… (negativa amable).', ex: ['Of course, here you are.', "I'm afraid I can't today."] },
      ],
      vocab: [['could', 'podría', 'Could you help me?'], ['may', 'puedo (formal)', 'May I come in?'], ['would you mind', '¿te molestaría…?', 'Would you mind closing the door?'],
        ['of course', 'por supuesto', 'Of course!'], ["I'm afraid", 'me temo que', "I'm afraid I can't."], ['borrow', 'tomar prestado', 'Could I borrow your pen?'],
        ['lend', 'prestar', 'Could you lend me your charger?'], ['explain', 'explicar', 'Could you explain that again?']],
      ex: [
        ['mc', 'The most polite request:', 'Could you send me the report, please?|Send me the report.|You send me the report?', 'Could + please.'],
        ['mc', '___ I come in?', 'May|Would|Do', 'Formal permission → may.'],
        ['mc', 'Would you mind ___ the window?', 'opening|open|to open', 'Would you mind + -ing.'],
        ['mc', 'A kind “no”:', "I'm afraid I can't.|No, I don't want.|Never.", "I'm afraid…"],
        ['fill', '___ you explain that again, please?', 'Could|Can', 'Request.'],
        ['fix', 'Could you to repeat that?', 'Could you repeat that?', 'Could + base verb.'],
        ['fix', 'Can you borrow me your pen?', 'Can you lend me your pen?|Could you lend me your pen?', 'Lend = dar prestado; borrow = pedir prestado.'],
        ['order', 'Could I ask you a quick question', '¿Podría hacerte una pregunta rápida?'],
        ['listen', "Would you mind sending me the slides?"],
        ['speak', 'Could you explain that again, please?'],
      ],
      links: ['m3l4', 'm7l4'],
    },
    {
      id: 'm9l2', title: 'You must, you don’t have to', topic: 'must / have to / mustn’t',
      intro: 'Rules, obligations and freedom.',
      theory: [
        { h: 'Obligation', p: 'Must = strong rule (often written or personal). Have to = external obligation (most common in conversation).',
          es: 'must y have to = tener que. Have to es más común al hablar.', ex: ['Visitors must wear a badge.', 'I have to finish this today.'] },
        { h: 'The big trap', p: 'Mustn’t = prohibited. Don’t have to = not necessary (you are free).',
          es: '¡Cuidado! mustn’t = prohibido. don’t have to = no es necesario.',
          table: [["mustn't", 'You mustn’t share the password. (prohibido)'], ["don't have to", 'You don’t have to wear a suit. (opcional)']] },
        { h: 'have to changes!', p: 'Have to works like a normal verb: she has to, did you have to, I had to.',
          es: 'have to se conjuga: she has to, I had to (pasado).', anim: ['I have to work', 'She has to work'] },
      ],
      vocab: [['must', 'deber (fuerte)', 'You must sign here.'], ['have to', 'tener que', 'I have to leave early.'], ["mustn't", 'no se debe (prohibido)', "You mustn't smoke here."],
        ["don't have to", 'no hace falta', "You don't have to come."], ['badge', 'carné', 'Wear your badge.'], ['dress code', 'código de vestimenta', 'The dress code is casual.'],
        ['confidential', 'confidencial', 'This is confidential.'], ['sign', 'firmar', 'You must sign the contract.']],
      ex: [
        ['mc', "Friday is casual. You ___ wear a suit.", "don't have to|mustn't|must", 'Not necessary → don’t have to.'],
        ['mc', "This is confidential. You ___ share it.", "mustn't|don't have to|have to", 'Prohibited → mustn’t.'],
        ['mc', 'She ___ work late tonight.', 'has to|have to|must to', 'She → has to.'],
        ['fill', 'Yesterday I ___ to stay until 8 p.m.', 'had', 'Past of have to → had to.'],
        ['fill', 'Do you ___ to wear a uniform?', 'have', 'Question with do + have to.'],
        ['fix', 'You must to sign here.', 'You must sign here.', 'Must + base verb.'],
        ['fix', 'She have to leave early.', 'She has to leave early.', 'She → has to.'],
        ['order', "You don't have to answer emails on weekends", 'No tienes que contestar correos los fines de semana'],
        ['listen', "Visitors must wear a badge at all times."],
        ['speak', "I have to finish this today, but I don't have to stay late."],
      ],
      links: ['m9l1', 'm2l2', 'm4l4'],
    },
    {
      id: 'm9l3', title: 'You should try it', topic: 'should / shouldn’t',
      intro: 'Advice and recommendations — a strategist’s favorite modal.',
      theory: [
        { h: 'should = advice', p: 'Should + base verb. Same for everyone. Softer than must.',
          es: 'should = deberías (consejo).', anim: ['You must rest', 'You should rest'] },
        { h: 'Questions & opinions', p: 'Should I…? = ¿Debería…? I think you should… / I don’t think you should…',
          es: 'Para opinar: I think we should… (muy útil en reuniones).', ex: ['Should I send it now?', 'I think we should post at 7 p.m.', "I don't think we should use that photo."] },
        { h: 'Recommendation language', p: 'Why don’t you…? · You could… · If I were you, I’d… (module 11 preview!).',
          es: 'Otras formas de aconsejar.', ex: ["Why don't you try a carousel?", 'You could add a call to action.'] },
      ],
      vocab: [['should', 'debería', 'You should rest.'], ['advice', 'consejo', 'Thanks for the advice.'], ['recommend', 'recomendar', 'I recommend this book.'],
        ['suggest', 'sugerir', 'I suggest a new format.'], ['carousel', 'carrusel', 'Try a carousel post.'], ['audience', 'audiencia', 'Know your audience.'],
        ['tone', 'tono', 'The tone should be warm.'], ['avoid', 'evitar', 'You should avoid jargon.']],
      ex: [
        ['mc', "You look tired. You ___ go to bed early.", 'should|must to|should to', 'Advice → should.'],
        ['mc', '___ I wear a dress or a suit?', 'Should|Do|Must I to', 'Asking for advice.'],
        ['mc', 'Best for a meeting:', 'I think we should post in the evening.|We post evening, must.|You should to post.', 'I think we should…'],
        ['fill', "You ___ eat so much sugar. (negative advice)", "shouldn't|should not", 'Negative → shouldn’t.'],
        ['fill', "Why ___ you try a carousel?", "don't", "Why don't you…?"],
        ['fix', 'She shoulds call the client.', 'She should call the client.', 'No -s.'],
        ['fix', 'You should to avoid jargon.', 'You should avoid jargon.', 'No “to”.'],
        ['order', 'I think the tone should be warmer', 'Creo que el tono debería ser más cálido'],
        ['listen', "You should know your audience before you write."],
        ['speak', 'I think we should tell a story.'],
      ],
      links: ['m9l2', 'm6l3'],
    },
    {
      id: 'm9l4', title: 'It might rain, it may work', topic: 'might / may · emails',
      intro: 'Possibility — and the polite phrases of professional email.',
      theory: [
        { h: 'might / may = maybe', p: 'Might and may + base verb = something is possible (not sure).',
          es: 'might/may = puede que, quizás.', anim: ['Maybe it will rain', 'It might rain'] },
        { h: 'Certainty scale', p: 'will (100%) → should / probably (80%) → may / might (50%) → might not → won’t (0%).',
          es: 'Escala de certeza.', table: [['100%', 'It will work.'], ['50%', 'It might / may work.'], ['0%', "It won't work."]] },
        { h: 'Email toolkit', p: 'Professional emails love modals: I would like to… / Could you…? / Please find attached… / I look forward to hearing from you.',
          es: 'Frases clave para correos formales.', ex: ['I hope this email finds you well.', 'Please find attached my portfolio.', 'I look forward to hearing from you.'] },
      ],
      vocab: [['might', 'puede que', 'It might be late.'], ['possible', 'posible', "It's possible."], ['attached', 'adjunto', 'Please find attached the file.'],
        ['look forward to', 'esperar con gusto', 'I look forward to hearing from you.'], ['regards', 'saludos', 'Best regards,'], ['follow up', 'hacer seguimiento', "I'm writing to follow up."],
        ['reschedule', 'reprogramar', 'Could we reschedule?'], ['delay', 'retraso', 'There might be a delay.']],
      ex: [
        ['mc', "Take an umbrella. It ___ rain.", 'might|must|should to', 'Possible → might.'],
        ['mc', 'Correct email phrase:', 'I look forward to hearing from you.|I look forward to hear from you.|I wait your answer.', 'look forward to + -ing.'],
        ['mc', 'Possible, not sure:', 'The client may call today.|The client must calls today.|The client mays call.', 'may + base verb.'],
        ['fill', 'Please find ___ my CV.', 'attached', 'Please find attached…'],
        ['fill', "She ___ not come. She's sick. (possibility)", 'might|may', 'might not.'],
        ['fix', 'It might to be a problem.', 'It might be a problem.', 'No “to”.'],
        ['fix', 'Best regard,', 'Best regards,', 'Regards with -s.'],
        ['order', "I'm writing to follow up on our meeting", 'Escribo para hacer seguimiento a nuestra reunión'],
        ['listen', 'There might be a delay. Could we reschedule?'],
        ['speak', 'I look forward to hearing from you.'],
      ],
      links: ['m9l1', 'm7l2'],
    },
    {
      id: 'm9l5', title: 'Letters from New York · Ch.9', topic: 'story: first day', story: true,
      intro: 'Chapter 9: an offer, a flight and a first day in Manhattan.',
      read: { title: 'Welcome to Maison Lumière', text:
`One week after the interview, the email arrived: "We are happy to offer you the position." Two months later I was in New York.

On my first day, a guy with curly hair and a coffee in each hand met me at reception. "Hi, I'm Sam! You must be Meri. This one's for you."

Sam showed me the office. "Okay, the rules. You have to wear your badge. You mustn't post anything about new products before the launch. And you don't have to wear heels — Claire hates them." He laughed. "My advice? You should always bring ideas to the Monday meeting."

At five o'clock Claire called me into her office. On her desk there was an old black-and-white photo of three young women in front of a perfume factory.

"Could you sit down, Meri?" she said. "I think you should see this. The woman on the left might be your Rosa."` },
      theory: [
        { h: 'Modals at work', p: 'Find must, have to, mustn’t, don’t have to, should, could and might. Module 9 in an office.',
          es: 'Todos los modales del módulo en un primer día de trabajo.' },
      ],
      vocab: [['offer', 'oferta / ofrecer', 'We are happy to offer you the position.'], ['reception', 'recepción', 'He met me at reception.'], ['curly', 'rizado', 'curly hair'],
        ['heels', 'tacones', "You don't have to wear heels."], ['factory', 'fábrica', 'a perfume factory'], ['on the left', 'a la izquierda', 'The woman on the left.']],
      ex: [
        ['read', 'What mustn’t Meri do?', 'Post about new products before the launch|Wear her badge|Bring ideas', '"You mustn\'t post anything about new products…"'],
        ['read', 'Does Meri have to wear heels?', "No, she doesn't|Yes, she must|Only on Mondays", '"…you don\'t have to wear heels."'],
        ['read', 'What was on Claire’s desk?', 'An old photo of three women|Rosa’s letter|A new perfume', '"…an old black-and-white photo of three young women…"'],
        ['read', 'What does Claire think?', 'The woman on the left might be Rosa|Sam is Rosa’s son|Meri should go home', '"The woman on the left might be your Rosa."'],
        ['fix', "You don't have to post before the launch. (= prohibited)", "You mustn't post before the launch.", 'Prohibited → mustn’t.'],
        ['mc', 'Sam: "You ___ always bring ideas."', 'should|mustn’t|might not', 'Advice → should.'],
        ['listen', 'You must be Meri. This one is for you.'],
        ['speak', 'Could you sit down, please?'],
      ],
      links: ['m9l1', 'm9l2', 'm9l3', 'm9l4', 'm8l5'],
    },
  ],
  exam: [
    ['mc', 'Most polite:', 'Would you mind waiting a moment?|Wait.|You wait a moment?', 'Would you mind + -ing.'],
    ['mc', "It's optional. You ___ come.", "don't have to|mustn't|must", 'Not necessary.'],
    ['mc', "Don't touch that! You ___ touch the samples.", "mustn't|don't have to|should", 'Prohibited.'],
    ['mc', "I'm not sure. It ___ be true.", 'might|must to|should to', 'Possibility.'],
    ['mc', 'Last week we ___ work on Saturday.', 'had to|must|have to', 'Past obligation → had to.'],
    ['fill', 'You look stressed. You ___ take a break.', 'should', 'Advice.'],
    ['fill', 'Please find ___ the presentation.', 'attached', 'Email phrase.'],
    ['fix', 'He must to arrive at 9.', 'He must arrive at 9.', 'No “to” after must.'],
    ['fix', 'Could you borrow me your notes?', 'Could you lend me your notes?', 'Lend.'],
    ['fix', 'I look forward to meet you.', 'I look forward to meeting you.', 'look forward to + -ing.'],
    ['order', 'Should I send the press release today', '¿Debería enviar el comunicado hoy?'],
    ['listen', "You don't have to wear a suit, but you must wear your badge."],
  ],
}
