export default {
  id: 'm10', level: 'B1', title: 'Tell Me a Story', subtitle: 'Past continuous · used to · linking words',
  goal: 'Tell rich stories: background, interruptions, old habits and smooth connections.',
  lessons: [
    {
      id: 'm10l1', title: 'I was walking in the rain', topic: 'past continuous: form',
      intro: 'The background of a story — what was happening.',
      theory: [
        { h: 'was / were + -ing', p: 'Module 5 (was/were) + module 4 (-ing) = **past continuous**. An action **in progress** in the past.',
          es: '**estaba + -ando**: I **was walking** = estaba caminando.', anim: ['I am walking in the rain', 'I was walking in the rain'] },
        { h: 'Setting the scene', p: 'Writers use it to paint the **background** of a scene, like a camera.',
          es: 'Se usa para describir el **ambiente** de una historia.', ex: ['The sun was setting. People were walking by the river. A violinist was playing.'] },
        { h: 'At a specific time', p: '**What were you doing** at 8 p.m. last night? — **I was reading.**',
          es: '**¿Qué estabas haciendo** a las 8? — **Estaba leyendo.**', anim: ['You were reading', 'Were you reading?'] },
      ],
      vocab: [['set (sun)', 'ponerse (el sol)', 'The sun was setting.'], ['shine', 'brillar', 'The sun was shining.'], ['crowd', 'multitud', 'A crowd was waiting.'],
        ['violinist', 'violinista', 'A violinist was playing.'], ['fall (snow)', 'caer', 'Snow was falling.'], ['whole', 'entero', 'the whole afternoon'],
        ['street', 'calle', 'People were crossing the street.'], ['background', 'fondo / contexto', 'the background of the story']],
      ex: [
        ['mc', 'At 9 p.m. I ___ a movie.', 'was watching|were watching|watched at', 'I → was + -ing.'],
        ['mc', 'They ___ by the river when we saw them.', 'were walking|was walking|walking', 'They → were.'],
        ['mc', 'What ___ you doing at midnight?', 'were|was|did', 'You → were.'],
        ['fill', 'The sun ___ shining and the birds were singing.', 'was', 'It → was.'],
        ['fill', "We ___ sleeping when you called. (negative)", "weren't|were not", 'We → weren’t.'],
        ['fix', 'She was study at 8 p.m.', 'She was studying at 8 p.m.', 'was + -ing.'],
        ['fix', 'They was waiting outside.', 'They were waiting outside.', 'They → were.'],
        ['order', 'Snow was falling on the quiet street', 'La nieve caía sobre la calle tranquila'],
        ['listen', 'A violinist was playing and people were dancing.'],
        ['speak', 'At eight I was reading a novel.'],
      ],
      links: ['m5l1', 'm4l1'],
    },
    {
      id: 'm10l2', title: 'When the phone rang…', topic: 'past continuous vs past simple',
      intro: 'Interruptions — the moment a story changes.',
      theory: [
        { h: 'Long action + short action', p: 'Long background action → **past continuous**. Short action that interrupts → **past simple**.',
          es: 'Acción larga (**continuo**) interrumpida por una corta (**simple**).', anim: ['I was reading. The phone rang.', 'I was reading when the phone rang.'] },
        { h: 'when vs while', p: '**When** + short action (past simple). **While** + long action (past continuous).',
          es: '**when + simple** · **while + continuo**.', table: [['when', 'I was cooking when she arrived.'], ['while', 'While I was cooking, she arrived.']] },
        { h: 'Two actions together', p: '**While** A **was happening**, B **was happening** (both continuous).',
          es: 'Dos acciones largas a la vez: **while + continuo**.', ex: ['While I was working, Sam was making coffee.'] },
      ],
      vocab: [['when', 'cuando', 'when the phone rang'], ['while', 'mientras', 'while I was cooking'], ['suddenly', 'de repente', 'Suddenly the lights went out.'],
        ['ring (rang)', 'sonar', 'The phone rang.'], ['break (broke)', 'romperse', 'My heel broke.'], ['drop', 'dejar caer', 'I dropped my coffee.'],
        ['notice', 'notar', 'I noticed a strange man.'], ['happen', 'pasar/suceder', 'What happened?']],
      ex: [
        ['mc', 'I was cooking when Laura ___.', 'called|was calling|calls', 'Short interruption → simple.'],
        ['mc', '___ I was walking home, it started to rain.', 'While|When|During', 'Long action → while.'],
        ['mc', 'She ___ her coffee while she was running to the meeting.', 'dropped|was dropping|drop', 'Short action → simple.'],
        ['fill', 'What ___ you doing when the lights went out?', 'were', 'Background question.'],
        ['fill', 'While Meri was talking, Sam ___ taking notes.', 'was', 'Two long actions.'],
        ['fix', 'I read when you called me.', 'I was reading when you called me.', 'Background → continuous.'],
        ['fix', 'While I watched TV, the doorbell was ringing.', 'While I was watching TV, the doorbell rang.', 'Long = continuous, short = simple.'],
        ['order', 'My heel broke while I was crossing the street', 'Se me rompió el tacón mientras cruzaba la calle'],
        ['listen', 'I was sleeping when the phone rang.'],
        ['speak', 'What were you doing when it happened?'],
      ],
      links: ['m10l1', 'm5l3'],
    },
    {
      id: 'm10l3', title: 'I used to write poems', topic: 'used to',
      intro: 'Old habits and states that are not true anymore.',
      theory: [
        { h: 'used to + base verb', p: 'For **past habits** or **states** that are **finished now**.',
          es: '**solía = used to**. I **used to live** in Cali (ya no).', anim: ['I lived in Cali as a child', 'I used to live in Cali'] },
        { h: 'Negatives & questions', p: 'With did: **didn’t use to** / **Did you use to…?** (no -d!).',
          es: 'Con did se quita la **-d**: **didn’t use to**.', ex: ["I didn't use to like coffee.", 'Did you use to play the piano?'] },
        { h: 'Story language', p: 'Used to is perfect for **memories and nostalgia** — very Allende.',
          es: 'Ideal para **recuerdos y nostalgia**.', ex: ['My grandmother used to tell us stories every night.', 'There used to be a cinema on this street.'] },
      ],
      vocab: [['used to', 'solía', 'I used to write poems.'], ['anymore', 'ya no', "I don't do it anymore."], ['nostalgia', 'nostalgia', 'full of nostalgia'],
        ['as a child', 'de niña', 'As a child, I used to draw.'], ['tell stories', 'contar historias', 'She used to tell stories.'], ['neighborhood', 'barrio', 'my old neighborhood'],
        ['record player', 'tocadiscos', 'We used to have a record player.'], ['habit', 'hábito', 'an old habit']],
      ex: [
        ['mc', 'I ___ write poems when I was a teenager.', 'used to|use to|was used to', 'Past habit → used to.'],
        ['mc', '___ you use to have a pet?', 'Did|Were|Used', 'Question with did.'],
        ['mc', "I didn't ___ like coffee, but now I love it.", 'use to|used to|using', 'With didn’t → use to.'],
        ['fill', 'There ___ to be a bookstore here.', 'used', 'There used to be…'],
        ['fill', "She doesn't smoke ___. She stopped years ago.", 'anymore', 'Not anymore.'],
        ['fix', 'I use to live in Cali.', 'I used to live in Cali.', 'Affirmative → used to.'],
        ['fix', 'Did you used to dance?', 'Did you use to dance?', 'With did → use to.'],
        ['order', 'My grandmother used to tell us stories every night', 'Mi abuela solía contarnos historias cada noche'],
        ['listen', 'We used to have a record player in the living room.'],
        ['speak', 'As a child, I used to draw flowers.'],
      ],
      links: ['m5l4', 'm2l3'],
    },
    {
      id: 'm10l4', title: 'However, although, so', topic: 'linking words',
      intro: 'Connect ideas like a writer — and like a strategist.',
      theory: [
        { h: 'Sequence', p: '**First**, … **Then**, … **After that**, … **Finally**, …',
          es: 'Para ordenar: **primero**, **luego**, **después de eso**, **finalmente**.', ex: ['First, we research the audience. Then, we write the message. Finally, we measure the results.'] },
        { h: 'Contrast', p: '**but** (informal, middle) · **however** (formal, new sentence) · **although** (+ full clause).',
          es: '**but** = pero. **However** = sin embargo. **Although** = aunque.', anim: ['It was expensive. We bought it.', 'Although it was expensive, we bought it.'] },
        { h: 'Cause & result', p: '**because** (cause) · **so** (result).',
          es: '**because** = porque · **so** = así que.', ex: ['I study every day because I want the job.', 'I wanted the job, so I studied every day.'] },
      ],
      vocab: [['first', 'primero', 'First, we listen.'], ['then', 'luego', 'Then, we write.'], ['after that', 'después de eso', 'After that, we test it.'],
        ['finally', 'finalmente', 'Finally, we launch.'], ['however', 'sin embargo', 'However, the budget is small.'], ['although', 'aunque', 'Although it was late, we stayed.'],
        ['so', 'así que', 'It was late, so I left.'], ['because', 'porque', 'because I love it']],
      ex: [
        ['mc', 'The idea is great. ___, the budget is small.', 'However|Because|So', 'Contrast (formal) → however.'],
        ['mc', "___ she was tired, she finished the report.", 'Although|However|So', 'Although + clause.'],
        ['mc', 'It was raining, ___ we took a taxi.', 'so|because|although', 'Result → so.'],
        ['mc', 'I love New York ___ it has amazing museums.', 'because|so|however', 'Cause → because.'],
        ['fill', 'First we research. ___ that, we write the message.', 'After', 'After that.'],
        ['fix', 'Although it was expensive, but we bought it.', 'Although it was expensive, we bought it.', 'Don’t use although + but together.'],
        ['fix', 'I was tired, because I went to bed early.', 'I was tired, so I went to bed early.', 'Result → so.'],
        ['order', 'Finally we measure the results of the campaign', 'Finalmente medimos los resultados de la campaña'],
        ['listen', "The product is beautiful. However, the brand needs a story."],
        ['speak', 'First I study, then I listen to music, and finally I sleep.'],
      ],
      links: ['m10l2', 'm6l5'],
    },
    {
      id: 'm10l5', title: 'Letters from New York · Ch.10', topic: 'story: the truth', story: true,
      intro: 'Chapter 10: Claire tells the story of the three women.',
      read: { title: "Claire's story", text:
`"My mother used to work in that factory," Claire said. "She was the woman in the middle. Her best friend was a young Colombian woman. Her name was Rosa."

I couldn't breathe.

"In 1968 they were creating a new perfume together. Rosa used to write the descriptions — little poems for each scent. However, in 1969 something happened. One night the women were working late when a fire started in the factory. Everyone escaped, but the perfume formula and Rosa's poems were lost."

"And Rosa?" I asked.

"After the fire, she moved to Paris. She became a writer, although she never published under her real name. My mother received one letter from her, so we know she was happy." Claire looked at me. "She never forgot Colombia. And I think, Meri, that perfume was never finished."` },
      theory: [
        { h: 'A story with layers', p: 'Find **used to**, **past continuous with when**, **past simple** events and the **linking words** (however, although, so, after).',
          es: 'Todo el módulo 10 en la revelación.' },
      ],
      vocab: [['breathe', 'respirar', "I couldn't breathe."], ['scent', 'aroma', 'a poem for each scent'], ['fire', 'incendio', 'A fire started.'],
        ['escape', 'escapar', 'Everyone escaped.'], ['formula', 'fórmula', 'the perfume formula'], ['publish', 'publicar', 'She never published.']],
      ex: [
        ['read', 'Who was Claire’s mother?', 'Rosa’s best friend|Rosa’s sister|Inés', '"Her best friend was a young Colombian woman… Rosa."'],
        ['read', 'What did Rosa use to write?', 'Little poems for each scent|Emails|Press releases', '"Rosa used to write the descriptions — little poems for each scent."'],
        ['read', 'What happened while the women were working late?', 'A fire started|Rosa arrived|They finished the perfume', '"…working late when a fire started…"'],
        ['read', 'Where did Rosa go after the fire?', 'To Paris|Back to Colombia|To Boston', '"After the fire, she moved to Paris."'],
        ['fix', 'They worked late when a fire was starting.', 'They were working late when a fire started.', 'Long = continuous, short = simple.'],
        ['mc', 'She became a writer, ___ she never used her real name.', 'although|so|because', 'Contrast.'],
        ['listen', 'That perfume was never finished.'],
        ['speak', 'My mother used to work in that factory.'],
      ],
      links: ['m10l1', 'm10l2', 'm10l3', 'm10l4', 'm9l5'],
    },
  ],
  exam: [
    ['mc', 'At 7 a.m. I ___ breakfast.', 'was having|had at|have', 'In progress → past continuous.'],
    ['mc', 'I was driving ___ I saw the accident.', 'when|while|during', 'Short → when.'],
    ['mc', 'We ___ go to the beach every summer as kids.', 'used to|use to|were used', 'Past habit.'],
    ['mc', 'The plan was good. ___, it didn’t work.', 'However|Because|So', 'Contrast.'],
    ['mc', '___ it was late, she kept writing.', 'Although|So|Because', 'Although + clause.'],
    ['fill', 'While I ___ cooking, the lights went out.', 'was', 'While + continuous.'],
    ['fill', "Did you ___ to live in Bogotá?", 'use', 'Did + use to.'],
    ['fix', 'I was walk home when it started to rain.', 'I was walking home when it started to rain.', 'was + -ing.'],
    ['fix', 'When I was arriving, they left.', 'When I arrived, they were leaving.|When I arrived, they left.', 'Short action → simple.'],
    ['fix', 'I was hungry, because I ate a sandwich.', 'I was hungry, so I ate a sandwich.', 'Result → so.'],
    ['order', 'What were you doing when I called you', '¿Qué estabas haciendo cuando te llamé?'],
    ['listen', 'First we listened, then we wrote, and finally we launched.'],
  ],
}
