export default {
  id: 'm11', level: 'B1', title: 'If I Were You', subtitle: 'Conditionals · time clauses · unless',
  goal: 'Talk about conditions, consequences and imaginary situations — the logic of strategy.',
  lessons: [
    {
      id: 'm11l1', title: 'If you heat ice, it melts', topic: 'zero conditional',
      intro: 'Facts and rules that are always true.',
      theory: [
        { h: 'If + present, present', p: 'For general truths, scientific facts and rules: if (or when) + present simple, present simple.',
          es: 'Verdades generales: If you heat ice, it melts.', ex: ['If you heat ice, it melts.', 'If customers feel emotion, they remember the brand.'] },
        { h: 'if = when here', p: 'In the zero conditional, if and when mean almost the same.',
          es: 'Aquí if y when son casi iguales.', anim: ['If I drink coffee late, I can’t sleep', 'When I drink coffee late, I can’t sleep'] },
        { h: 'Comma rule', p: 'If the if-clause goes first, use a comma. If it goes second, no comma.',
          es: 'Coma solo si el if va primero.', ex: ['If it rains, the park closes.', 'The park closes if it rains.'] },
      ],
      vocab: [['heat', 'calentar', 'If you heat water, it boils.'], ['melt', 'derretirse', 'Ice melts.'], ['boil', 'hervir', 'Water boils at 100 °C.'],
        ['customer', 'cliente', 'If customers are happy, they come back.'], ['trust', 'confiar', 'If people trust you, they buy.'], ['remember', 'recordar', 'People remember stories.'],
        ['emotion', 'emoción', 'Emotion sells.'], ['fade', 'desvanecerse', 'If you leave perfume in the sun, it fades.']],
      ex: [
        ['mc', 'If you mix red and white, you ___ pink.', 'get|will got|got', 'Zero conditional: present + present.'],
        ['mc', 'If customers ___ a brand, they buy more.', 'trust|trusts|trusted', 'Customers → trust.'],
        ['mc', 'Correct punctuation:', 'If it rains, the park closes.|If it rains the park, closes.|The park closes, if it rains.', 'Comma after the if-clause when it’s first.'],
        ['fill', 'If you heat ice, it ___.', 'melts', 'It → melts.'],
        ['fill', '___ I drink coffee at night, I can’t sleep. (= when)', 'If|When', 'If / when.'],
        ['fix', 'If you will leave perfume in the sun, it fades.', 'If you leave perfume in the sun, it fades.', 'No will in the if-clause.'],
        ['order', 'If people feel emotion they remember the brand', 'Si la gente siente emoción, recuerda la marca'],
        ['listen', 'If you heat water to one hundred degrees, it boils.'],
        ['speak', 'If I listen to music, I feel calm.'],
      ],
      links: ['m2l1', 'm10l4'],
    },
    {
      id: 'm11l2', title: 'If we tell her story, they will listen', topic: 'first conditional',
      intro: 'Real possibilities in the future — the grammar of plans and pitches.',
      theory: [
        { h: 'If + present, will + verb', p: 'For real, possible future situations. Present in the if-clause, will (module 7) in the result.',
          es: 'Si + presente, will + verbo. ¡Nunca will después de if!', anim: ['If we will tell the story, people will listen', 'If we tell the story, people will listen'] },
        { h: 'Other results', p: 'The result can also be can, might, should or an imperative.',
          es: 'Resultado también con can/might/should o imperativo.', ex: ["If you finish early, you can leave.", 'If it rains, take an umbrella.', 'If we post at 7, we might get more views.'] },
        { h: 'unless = if not', p: 'Unless = except if.',
          es: 'unless = a menos que. Unless you hurry = if you don’t hurry.', ex: ["We'll miss the train unless we hurry.", "Unless the client approves, we won't launch."] },
      ],
      vocab: [['unless', 'a menos que', "unless you hurry"], ['approve', 'aprobar', 'If the client approves…'], ['hurry', 'apurarse', 'If we hurry, we’ll make it.'],
        ['miss', 'perder (tren)', "We'll miss the train."], ['views', 'visualizaciones', 'more views'], ['reach', 'alcance / alcanzar', 'We will reach more people.'],
        ['succeed', 'tener éxito', "If you practice, you'll succeed."], ['campaign', 'campaña', 'the new campaign']],
      ex: [
        ['mc', 'If we ___ the video tonight, we’ll get more views.', 'post|will post|posted', 'If + present.'],
        ['mc', "If you practice every day, you ___ B1.", "'ll reach|reach will|reaching", 'Result → will.'],
        ['mc', "We'll be late ___ we leave now.", 'unless|if|when not', 'Unless = if not.'],
        ['fill', "If the client ___ (approve), we will launch in May.", 'approves', 'If + present (she/it → -s).'],
        ['fill', "If it rains, ___ an umbrella. (imperative)", 'take', 'Imperative result.'],
        ['fix', 'If you will call me, I will answer.', 'If you call me, I will answer.|If you call me, I’ll answer.', 'No will after if.'],
        ['fix', "Unless you don't hurry, you'll miss it.", "Unless you hurry, you'll miss it.|If you don't hurry, you'll miss it.", 'Unless already means “if not”.'],
        ['order', 'If we tell her story people will feel something', 'Si contamos su historia la gente sentirá algo'],
        ['listen', "If you finish early, you can leave."],
        ['speak', "If I practice every day, I'll reach B1."],
      ],
      links: ['m11l1', 'm7l2'],
    },
    {
      id: 'm11l3', title: 'If I were you…', topic: 'second conditional',
      intro: 'Imaginary situations, dreams and elegant advice.',
      theory: [
        { h: 'If + past, would + verb', p: 'For unreal or unlikely situations. Past simple in the if-clause (it isn’t past time!), would in the result.',
          es: 'Situaciones imaginarias: If I had money, I would travel. (Si tuviera…, viajaría).', anim: ['If I have time, I will paint', 'If I had time, I would paint'] },
        { h: 'were for everyone', p: 'With be, use were for all persons — especially in “If I were you”.',
          es: 'If I were you (yo en tu lugar) = consejo elegante.', ex: ['If I were you, I would accept the offer.', 'If she were here, she would love this.'] },
        { h: 'First vs second', p: 'Real/possible → first (will). Imaginary/unlikely → second (would).',
          es: 'Posible → will. Imaginario → would.', table: [['first', 'If I get the job, I will move.'], ['second', 'If I won the lottery, I would buy a castle.']] },
      ],
      vocab: [['would', 'condicional (-ría)', 'I would travel.'], ['win (won)', 'ganar', 'If I won the lottery…'], ['lottery', 'lotería', 'the lottery'],
        ['accept', 'aceptar', "I'd accept the offer."], ['castle', 'castillo', 'a castle in France'], ['imagine', 'imaginar', 'Imagine if…'],
        ['wish', 'desear', 'I wish I could fly.'], ['brave', 'valiente', 'If I were braver…']],
      ex: [
        ['mc', 'If I ___ rich, I would buy an old house in Paris.', 'were|am|will be', 'Second conditional → were.'],
        ['mc', 'If I were you, I ___ the offer.', 'would accept|will accept|accepted', 'Advice → would.'],
        ['mc', 'Real possibility:', 'If I get the job, I will move to New York.|If I got the job, I will move.|If I get the job, I would moved.', 'Possible → first conditional.'],
        ['fill', 'If she ___ (have) more time, she would paint.', 'had', 'If + past.'],
        ['fill', 'What ___ you do if you won the lottery?', 'would', 'Imaginary question.'],
        ['fix', 'If I would have money, I would travel.', 'If I had money, I would travel.', 'No would in the if-clause.'],
        ['fix', 'If I was you, I would call her.', 'If I were you, I would call her.|If I were you, I’d call her.', 'If I were you.'],
        ['order', 'If I were you I would tell the truth', 'Yo en tu lugar diría la verdad'],
        ['listen', 'If Rosa were here, she would love this.'],
        ['speak', 'If I lived in Paris, I would visit museums every week.'],
      ],
      links: ['m11l2', 'm9l3', 'm5l1'],
    },
    {
      id: 'm11l4', title: 'As soon as I arrive…', topic: 'time clauses',
      intro: 'when, before, after, as soon as, until — with a future meaning.',
      theory: [
        { h: 'Present after time words', p: 'After when, before, after, as soon as, until — use the present, even for the future (like if!).',
          es: 'Después de when/as soon as/until: presente, aunque sea futuro.', anim: ["I'll call you when I will arrive", "I'll call you when I arrive"] },
        { h: 'The connectors', p: 'as soon as (en cuanto), until (hasta que), before (antes de que), after (después de que).',
          es: 'Conectores de tiempo.', table: [['as soon as', "I'll text you as soon as I land."], ['until', "Wait until I'm ready."], ['before', 'Read it before you sign.'], ['after', "We'll eat after the meeting ends."]] },
      ],
      vocab: [['as soon as', 'en cuanto', 'as soon as I land'], ['until', 'hasta que', "until I'm ready"], ['land', 'aterrizar', 'when the plane lands'],
        ['text', 'escribir (mensaje)', "I'll text you."], ['get back', 'volver', 'when I get back'], ['ready', 'lista', "when you're ready"],
        ['approval', 'aprobación', 'after the approval'], ['meanwhile', 'mientras tanto', 'Meanwhile, I’ll prepare the slides.']],
      ex: [
        ['mc', "I'll text you as soon as I ___.", 'land|will land|landed', 'Present after as soon as.'],
        ['mc', "Don't sign anything ___ you read it.", 'until|as soon|when will', 'until = hasta que.'],
        ['mc', 'We’ll start the meeting when everyone ___.', 'arrives|will arrive|arrive will', 'Present after when.'],
        ['fill', "I'll call you when I ___ back. (get)", 'get', 'Present after when.'],
        ['fill', 'Wait here ___ I come back.', 'until', 'until.'],
        ['fix', "She'll be happy when she will see it.", "She'll be happy when she sees it.", 'Present after when.'],
        ['fix', "Before you will leave, close the window.", 'Before you leave, close the window.', 'Present after before.'],
        ['order', "I'll call you as soon as the meeting ends", 'Te llamo en cuanto termine la reunión'],
        ['listen', "We'll launch the campaign after the client approves it."],
        ['speak', "I'll celebrate when I finish this course."],
      ],
      links: ['m11l2', 'm7l3'],
    },
    {
      id: 'm11l5', title: 'Letters from New York · Ch.11', topic: 'story: the idea', story: true,
      intro: 'Chapter 11: Meri brings an idea to the Monday meeting.',
      read: { title: 'The Monday meeting', text:
`On Monday I stood in front of the whole team. My hands were cold, but my voice was clear.

"If we tell Rosa's story, people will feel something real. When people feel something, they remember the brand. So here is my idea: we finish the perfume from 1968. We call it Rosa. And every bottle comes with one of her poems."

Silence. Then Sam said, "But we don't have the poems. They burned in the fire."

"Not all of them," I said. I opened my bag and took out an old notebook. "My grandmother found this last week. Rosa sent it to her sister in 1969, after the fire. She rewrote every poem from memory."

Claire stood up. "If I were you, Meri, I would start working on the pitch today. As soon as it's ready, we will present it to the board."` },
      theory: [
        { h: 'Strategy grammar', p: 'Find zero conditional (when people feel…), first conditional (If we tell…), second conditional (If I were you…) and time clauses (As soon as it’s ready…).',
          es: 'Cada condicional cumple una función en el pitch.' },
      ],
      vocab: [['stand (stood)', 'estar de pie', 'I stood in front of the team.'], ['voice', 'voz', 'My voice was clear.'], ['burn (burned)', 'quemarse', 'They burned in the fire.'],
        ['rewrite (rewrote)', 'reescribir', 'She rewrote every poem.'], ['from memory', 'de memoria', 'from memory'], ['board', 'junta directiva', 'present it to the board']],
      ex: [
        ['read', 'What is Meri’s idea?', 'Finish the 1968 perfume and call it Rosa|Open a store in Paris|Write a novel', '"…we finish the perfume from 1968. We call it Rosa."'],
        ['read', 'What problem did Sam mention?', 'The poems burned in the fire|There is no budget|Claire said no', '"They burned in the fire."'],
        ['read', 'What was in the old notebook?', 'Rosa’s poems, rewritten from memory|The perfume formula|Photos', '"She rewrote every poem from memory."'],
        ['read', 'What did Claire advise?', 'To start working on the pitch today|To wait a month|To call the board', '"If I were you… I would start working on the pitch today."'],
        ['fix', "As soon as it will be ready, we will present it.", "As soon as it's ready, we will present it.|As soon as it is ready, we will present it.", 'Present after as soon as.'],
        ['mc', 'If we ___ Rosa’s story, people will feel something.', 'tell|will tell|told', 'First conditional.'],
        ['listen', 'If I were you, I would start working on the pitch today.'],
        ['speak', 'If we tell her story, people will remember the brand.'],
      ],
      links: ['m11l1', 'm11l2', 'm11l3', 'm11l4', 'm10l5'],
    },
  ],
  exam: [
    ['mc', 'If you don’t water plants, they ___.', 'die|will died|died', 'Zero conditional.'],
    ['mc', 'If it ___ tomorrow, we’ll stay home.', 'rains|will rain|rained', 'First conditional: if + present.'],
    ['mc', 'If I ___ you, I’d take the job.', 'were|am|will be', 'If I were you.'],
    ['mc', "We won't finish ___ we work together.", 'unless|if|when', 'Unless = if not.'],
    ['mc', "I'll call you when I ___ home.", 'get|will get|got', 'Present after when.'],
    ['fill', 'If I ___ (speak) perfect English, I would work in London.', 'spoke', 'Second conditional.'],
    ['fill', "If you mix blue and yellow, you ___ green.", 'get', 'Zero conditional.'],
    ['fix', 'If I will see her, I will tell her.', "If I see her, I will tell her.|If I see her, I'll tell her.", 'No will after if.'],
    ['fix', 'If I had a car, I will drive to the coast.', 'If I had a car, I would drive to the coast.', 'Second conditional → would.'],
    ['fix', 'Wait until I will finish.', 'Wait until I finish.', 'Present after until.'],
    ['order', 'What would you do if you lived in New York', '¿Qué harías si vivieras en Nueva York?'],
    ['listen', "If we post the video tonight, we'll reach more people."],
  ],
}
