export default {
  id: 'm12', level: 'B1', title: 'The Big Pitch', subtitle: 'Passive voice · relative clauses · reported speech',
  goal: 'Present ideas like a professional: processes, descriptions and what people said.',
  lessons: [
    {
      id: 'm12l1', title: 'It is made in France', topic: 'passive: present',
      intro: 'Focus on the product, not on who does the action.',
      theory: [
        { h: 'be + past participle', p: 'Passive = **am/is/are + participle** (module 8!). The **object becomes the subject**.',
          es: 'Voz pasiva: **se hace / es hecho**. It **is made** in France.', anim: ['They make the perfume in Grasse', 'The perfume is made in Grasse'] },
        { h: 'Why use it?', p: 'When the **action or product** is more important than the person. Perfect for brands, processes and reports.',
          es: 'Cuando importa el **producto/proceso**, no quién lo hace.', ex: ['Our products are tested by dermatologists.', 'Every bottle is filled by hand.'] },
        { h: 'by + agent', p: 'Add **by + person** only if it’s important.',
          es: '**by** = por (quién lo hace), solo si importa.', ex: ['The poems are written by Rosa.', 'English is spoken worldwide.'] },
      ],
      vocab: [['made', 'hecho', 'made in France'], ['test', 'probar/testear', 'tested by dermatologists'], ['fill', 'llenar', 'filled by hand'],
        ['ingredient', 'ingrediente', 'natural ingredients'], ['produce', 'producir', 'It is produced in Grasse.'], ['package', 'empacar', 'Each bottle is packaged by hand.'],
        ['ship', 'enviar', 'Orders are shipped in 24 hours.'], ['by hand', 'a mano', 'made by hand']],
      ex: [
        ['mc', 'The bottles ___ by hand.', 'are filled|are fill|fill', 'Passive: are + participle.'],
        ['mc', 'English ___ in many countries.', 'is spoken|speaks|is speak', 'Speak → spoken.'],
        ['mc', 'Our products ___ on animals.', "aren't tested|don't tested|isn't tested", 'Plural negative passive.'],
        ['fill', 'This serum is ___ (make) with natural ingredients.', 'made', 'Participle of make.'],
        ['fill', 'Orders ___ shipped in 24 hours.', 'are', 'Plural → are.'],
        ['fix', 'The perfume is produce in Grasse.', 'The perfume is produced in Grasse.', 'Participle → produced.'],
        ['fix', 'The poems are write by Rosa.', 'The poems are written by Rosa.', 'Participle → written.'],
        ['order', 'Every bottle is packaged by hand', 'Cada botella es empacada a mano'],
        ['listen', 'Our products are tested by dermatologists.'],
        ['speak', 'This perfume is made in France.'],
      ],
      links: ['m8l1', 'm6l5'],
    },
    {
      id: 'm12l2', title: 'It was created in 1968', topic: 'passive: past',
      intro: 'History and heritage — brand storytelling in the passive.',
      theory: [
        { h: 'was / were + participle', p: 'Module 5 **(was/were) + participle** = **past passive**.',
          es: 'Pasado pasivo: **was/were + participio**. It **was created** in 1968.', anim: ['Rosa created the perfume', 'The perfume was created by Rosa'] },
        { h: 'Heritage language', p: 'Brands use it to tell their **history**.',
          es: 'Las marcas lo usan para contar su historia.', ex: ['The company was founded in 1920.', 'The formula was lost in a fire.', 'The poems were found in an old notebook.'] },
      ],
      vocab: [['found (founded)', 'fundar', 'It was founded in 1920.'], ['create', 'crear', 'It was created in 1968.'], ['lose (lost)', 'perder', 'It was lost in a fire.'],
        ['find (found)', 'encontrar', 'They were found last year.'], ['heritage', 'herencia/legado', 'our heritage'], ['design', 'diseñar', 'The bottle was designed in Paris.'],
        ['inspire', 'inspirar', 'It was inspired by poetry.'], ['rediscover', 'redescubrir', 'It was rediscovered.']],
      ex: [
        ['mc', 'The company ___ in 1920.', 'was founded|founded|is founded', 'Past passive.'],
        ['mc', 'The poems ___ in a notebook.', 'were found|was found|found', 'Plural → were.'],
        ['mc', 'The bottle was ___ by a French artist.', 'designed|design|designing', 'Participle.'],
        ['fill', 'The formula was ___ (lose) in a fire.', 'lost', 'Lose → lost.'],
        ['fill', 'The fragrance ___ inspired by poetry.', 'was', 'Singular → was.'],
        ['fix', 'The perfume was create in 1968.', 'The perfume was created in 1968.', 'Participle → created.'],
        ['fix', 'The letters was written in New York.', 'The letters were written in New York.', 'Plural → were.'],
        ['order', 'The fragrance was inspired by a Colombian poet', 'La fragancia fue inspirada por una poeta colombiana'],
        ['listen', 'The formula was lost in a fire in 1969.'],
        ['speak', 'The poems were rediscovered last year.'],
      ],
      links: ['m12l1', 'm5l3'],
    },
    {
      id: 'm12l3', title: 'The woman who wrote poems', topic: 'relative clauses',
      intro: 'Join ideas elegantly: who, which, that, where.',
      theory: [
        { h: 'Who, which, where', p: '**who** → people · **which** → things · **where** → places · **that** → people or things (informal).',
          es: '**who** (personas), **which** (cosas), **where** (lugares), **that** (ambos).', anim: ['Rosa was a poet. She worked in New York.', 'Rosa was a poet who worked in New York.'] },
        { h: 'Define with precision', p: 'Relative clauses give **essential information** about the noun.',
          es: 'Dan información clave sobre el sustantivo.', ex: ['This is the perfume that changed everything.', 'New York is the city where Rosa lived.', 'Claire is the director who believed in me.'] },
        { h: 'No extra pronoun', p: '**Don’t repeat the subject** after who/which.',
          es: 'Nunca: “**the woman who she wrote**”.', ex: ['the woman who wrote the poems ✓', 'the woman who she wrote ✗'] },
      ],
      vocab: [['who', 'que/quien (personas)', 'the woman who wrote'], ['which', 'que (cosas)', 'the bottle which…'], ['where', 'donde', 'the city where…'],
        ['that', 'que', 'the idea that changed everything'], ['believe in', 'creer en', 'the director who believed in me'], ['change', 'cambiar', 'the perfume that changed everything'],
        ['poet', 'poeta', 'a poet who loved the sea'], ['fragrance', 'fragancia', 'a fragrance which smells of roses']],
      ex: [
        ['mc', 'Rosa was a poet ___ worked in New York.', 'who|which|where', 'Person → who.'],
        ['mc', 'This is the bottle ___ was designed in Paris.', 'which|who|where', 'Thing → which.'],
        ['mc', 'Grasse is the town ___ perfumes are made.', 'where|which|who', 'Place → where.'],
        ['fill', 'Claire is the director ___ believed in me.', 'who|that', 'Person → who / that.'],
        ['fill', 'It was an idea ___ changed everything.', 'that|which', 'Thing → that / which.'],
        ['fix', 'The woman who she wrote the poems was Rosa.', 'The woman who wrote the poems was Rosa.', 'Don’t repeat the subject.'],
        ['fix', 'The city which I was born is Cali.', 'The city where I was born is Cali.', 'Place → where.'],
        ['order', 'This is the perfume that changed my life', 'Este es el perfume que cambió mi vida'],
        ['listen', 'New York is the city where Rosa wrote her poems.'],
        ['speak', 'I want a job which uses my creativity.'],
      ],
      links: ['m12l2', 'm10l4'],
    },
    {
      id: 'm12l4', title: 'She said that…', topic: 'reported speech',
      intro: 'Tell people what others said — in meetings, emails and stories.',
      theory: [
        { h: 'One step back in time', p: 'When you report past words, the tense usually **moves back**: present → **past**, will → **would**, can → **could**.',
          es: 'Al reportar, el tiempo **retrocede**: is → **was**, will → **would**, can → **could**.', anim: ['"I love the idea," Claire said.', 'Claire said that she loved the idea.'],
          table: [['"I am ready."', 'She said she was ready.'], ['"We will launch."', 'He said they would launch.'], ['"I can help."', 'She said she could help.']] },
        { h: 'say vs tell', p: '**Say** + (that) … · **Tell + PERSON** + (that) …',
          es: '**tell** necesita a quién: She **told me**… / She **said**…', ex: ['She said that it was perfect.', 'She told me that it was perfect.'] },
        { h: 'Pronouns change too', p: '**I → she/he**, **my → her/his**, **we → they**.',
          es: 'Cambian los **pronombres** según quién habla.', ex: ['"My idea is new." → She said her idea was new.'] },
      ],
      vocab: [['say (said)', 'decir', 'She said it was great.'], ['tell (told)', 'decirle a', 'He told me the truth.'], ['ask', 'preguntar', 'She asked if I was ready.'],
        ['explain', 'explicar', 'He explained that…'], ['agree', 'estar de acuerdo', 'The board agreed.'], ['announce', 'anunciar', 'They announced the launch.'],
        ['feedback', 'retroalimentación', 'She gave great feedback.'], ['quote', 'cita (textual)', 'a quote from the CEO']],
      ex: [
        ['mc', '"I am tired." → She said she ___ tired.', 'was|is|were', 'Present → past.'],
        ['mc', '"We will call you." → They said they ___ call me.', 'would|will|can', 'will → would.'],
        ['mc', 'Claire ___ me that the board loved it.', 'told|said|says to', 'Tell + person.'],
        ['fill', '"I can help." → Sam said he ___ help.', 'could', 'can → could.'],
        ['fill', 'She ___ that the launch was in May.', 'said|explained|announced', 'Say + that.'],
        ['fix', 'She said me that she was ready.', 'She told me that she was ready.|She said that she was ready.', 'Say has no person after it.'],
        ['fix', '"I love it." → He said he love it.', 'He said he loved it.|He said that he loved it.', 'Present → past.'],
        ['order', 'The director told me that she loved my idea', 'La directora me dijo que le encantó mi idea'],
        ['listen', 'She said the campaign would launch in spring.'],
        ['speak', 'Laura told me that I was ready.'],
      ],
      links: ['m12l3', 'm10l2', 'm7l2'],
    },
    {
      id: 'm12l5', title: 'Letters from New York · Ch.12', topic: 'story: the pitch', story: true,
      intro: 'The final chapter. Meri presents to the board — in English.',
      read: { title: 'Rosa, 1968', text:
`The boardroom was full. Twelve people were looking at me. I took a breath and started.

"This perfume was created in 1968 by three women who believed in beauty and words. The formula was lost in a fire, and the poems were almost forgotten. Last year they were found in a notebook which traveled from New York to Colombia — and back."

I showed the bottle: white glass, gold letters, one poem inside each box. "Rosa is not only a fragrance. It's a story that people will want to tell."

When I finished, nobody spoke. Then the CEO stood up and said that it was the most beautiful pitch she had ever heard. The board agreed to launch Rosa in the spring.

That night I wrote a letter to my grandmother, at my antique desk by the window. I didn't need a dictionary. "Dear Abuela," I wrote. "I'm writing from New York. Right now everyone is working on a new perfume. I love this city. Don't worry about me."

And I smiled, because Rosa had written the same words fifty-eight years before.` },
      theory: [
        { h: 'The full journey', p: 'This chapter uses **passives**, **relative clauses**, **reported speech** — and echoes Rosa’s letter from module 4. You understood all of it. That is B1.',
          es: 'Todo el camino en un capítulo. Si lo entendiste, estás en B1.' },
      ],
      vocab: [['boardroom', 'sala de juntas', 'The boardroom was full.'], ['almost', 'casi', 'almost forgotten'], ['glass', 'vidrio', 'white glass'],
        ['CEO', 'directora ejecutiva', 'The CEO stood up.'], ['dictionary', 'diccionario', "I didn't need a dictionary."], ['echo', 'eco', 'an echo of the past']],
      ex: [
        ['read', 'Who created the perfume in 1968?', 'Three women|The CEO|Meri and Sam', '"…by three women who believed in beauty and words."'],
        ['read', 'What is inside each box?', 'One of Rosa’s poems|A letter from Meri|A photo', '"…one poem inside each box."'],
        ['read', 'What did the board decide?', 'To launch Rosa in the spring|To wait a year|To sell the formula', '"The board agreed to launch Rosa in the spring."'],
        ['read', 'Why did Meri smile at the end?', 'Rosa wrote the same words decades before|She got a raise|Sam called her', '"…Rosa had written the same words…"'],
        ['fix', 'The formula was lose in a fire.', 'The formula was lost in a fire.', 'Participle → lost.'],
        ['mc', 'The CEO said that it ___ the most beautiful pitch.', 'was|is|will be', 'Reported → past.'],
        ['listen', "It's a story that people will want to tell."],
        ['speak', 'This perfume was created in 1968 by three women who believed in words.'],
      ],
      links: ['m12l1', 'm12l2', 'm12l3', 'm12l4', 'm4l5', 'm11l5'],
    },
  ],
  exam: [
    ['mc', 'Coffee ___ in Colombia.', 'is grown|grows by|is grow', 'Present passive.'],
    ['mc', 'The Mona Lisa ___ by Leonardo da Vinci.', 'was painted|painted|is painting', 'Past passive.'],
    ['mc', 'She is the designer ___ created the logo.', 'who|which|where', 'Person → who.'],
    ['mc', '"I will be there." → He said he ___ be there.', 'would|will|could', 'will → would.'],
    ['mc', 'Grasse is the place ___ my favorite perfume is made.', 'where|which|who', 'Place → where.'],
    ['fill', 'The letters ___ written in 1968.', 'were', 'Plural past passive.'],
    ['fill', 'She ___ me that she was proud of me.', 'told', 'Tell + person.'],
    ['fix', 'The campaign was launch in May.', 'The campaign was launched in May.', 'Participle → launched.'],
    ['fix', 'The book which I read it was amazing.', 'The book which I read was amazing.|The book that I read was amazing.', 'Don’t repeat the object.'],
    ['fix', 'He said me the meeting was cancelled.', 'He told me the meeting was cancelled.|He said the meeting was cancelled.', 'Say vs tell.'],
    ['order', 'This is the story that changed my career', 'Esta es la historia que cambió mi carrera'],
    ['listen', 'The perfume was created by three women who believed in words.'],
  ],
}
